### ISSUE TITLE
Taxes Report Testing

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1524]
For the Sprint 13 focus of QA/Testing, this issue is to test all aspects of the Taxes Report. 

## Testing Background

__🙌The More Clicks The Better__
This issue welcomes multi-assignees! The more people that complete the issue and recording findings the better.

__🐛Log and/or Squash em__
As you perform the tests, please log any bugs you find and reference this issue in the report so we can see if a bug has already been found / logged. If you feel so inclined, feel free to make a PR and fix a bug straight away if it is an easy fix.

__✅Record Findings__
After performing the tests, please fill out the [Testing Form](https://docs.google.com/forms/d/e/1FAIpQLSe42rfMDxeaSvRWKnP3ixy5sW6XXKlI-SnsC1-sMyVNNrsbkQ/viewform) so we can track findings from everyone in one place.

__📲Devices/Browsers__
Bonus points for performing the test in multiple browsers/devices.

__⏳Data Sets__
Feel free to test against your normal wc-admin env. But I also encourage anyone to test against the woocommerce.com developer data set, or a similar large data set which can help raise memory-intensive queries/bottlenecks better than smaller data samples.

If your current test env does not have taxes setup, or orders where taxes have been paid, you will need to do that first. 

## Taxes Report Checklist

- [ ] Verify the numbers/data match what is shown in the legacy report (/wp-admin/admin.php?page=wc-reports&tab=taxes#/ ) 
- [ ] Chart interactions. Hover the data points, verify the tooltips are correct.
- [ ] Click on all summary numbers, verify the chart updates as expected
- [ ] Change the intervals, verify the axis ticks look good
- [ ] Try a comparison between two or more tax codes using the advanced filters https://github.com/woocommerce/wc-admin/issues/1554
- [ ] Does Download CSV work
- [ ] Clicking a tax code currently goes nowhere ( where should this link to @LevinMedia / @josemarques  )?
- [ ] Change table sorting - do they all work as expected?
- [ ] Play with pagination
- [ ] Turn on a11y tools, tab through the page. Can you navigate without a mouse?
- [ ] Record your findings in the [Testing Form](https://docs.google.com/forms/d/e/1FAIpQLSe42rfMDxeaSvRWKnP3ixy5sW6XXKlI-SnsC1-sMyVNNrsbkQ/viewform)

**Comment by joshuatf** [comment]
I have more notes from testing that weren't applicable to the testing form, so I'll post them here.

### Differences in data
Found discrepancy in tax amounts, due 2 reasons:
* Refunds aren’t entirely accounted for in old reports
* Old reports only track statuses of `completed’, `processing`, and `refunded` which is odd because this doesn’t match the statuses tracked in order reports of `completed`, `processing`, and `on-hold`.  There’s a comment that mentions why on-hold is excluded (“We exlude on-hold orders are they are still pending payment”) but that doesn’t align with order reports and doesn’t explain the reason for including refunded statuses.

Seems like the new reports are more accurate here and what I’d expect, but curious if there are other reasons for having different order statuses in different reports.

### Comparisons

Labels, comparison, and segmenting were broken but should be resolved by new PRs.
https://github.com/woocommerce/wc-admin/pull/1571
https://github.com/woocommerce/wc-admin/pull/1671
https://github.com/woocommerce/wc-admin/pull/1672

### Deleted data

It looks like the wc.com example data does not include tax data in the `woocommerce_tax_rates` table, so this made testing more strenuous data difficult.

Also interesting to note here is that tax rate information is taken directly from the order item data, so even if a tax rate is deleted, it's still visible in the reports.  We pull this information from the `woocommerce_tax_rates` table, so if it's deleted there, we won't see it in the tax report, however, orders will continue to show the correct amount of tax in the orders report.

**Comment by timmyc** [comment]
closing out the sweep issues as they have been swept.
