### ISSUE TITLE
Setup: Expose Number of Pending Batch Jobs via wcSettings

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1692]
The lookup table population works by creating "batch" jobs to populate first the [Customers](https://github.com/woocommerce/wc-admin/blob/aaa26118425e555c1e5e406739d76f3f3f0e15ba/includes/class-wc-admin-reports-sync.php#L379) lookup table, then the [Orders](https://github.com/woocommerce/wc-admin/blob/aaa26118425e555c1e5e406739d76f3f3f0e15ba/includes/class-wc-admin-reports-sync.php#L196) ( and supporting ) lookup tables.

While you can view pending jobs within the _Status_ section of WooCommerce, that view is a bit cryptic and doesn't really give a good sense of how much work is left - as batch jobs enqueue more jobs... and really the table of jobs looks a bit confusing.

As such, we are hoping to eventually create an interface for users to see how the lookup table population is progressing. For this issue I'm hoping we can look at finding a way to query the jobs table for the total batch jobs, and total completed for both the Customers and Order lookup population processes. Then we could expose these via wcSettings, or some other fashion, and eventually communicate progress to users.

**EDIT by Jeff:** The status should be based on the number of customers/orders to be processed and the number that have been added to the corresponding lookup tables.

**Comment by justinshreve** [comment]
Just a note that the `wcSettings` value is only set on initial PHP page-load, so if you are moving between `wc-admin` pages, this value will not update. We can use it to prime a cache, but we'd still need an API endpoint to query every so often. Maybe a new `/data` endpoint?

**Comment by timmyc** [comment]
Correct, I had thought of that issue too - I suppose I was looking at this issue as a first step to potentially having an endpoint that could get polled from via fresh-data... also since we don't have designs yet around how we are going to display the status I wasn't really sure if we need an endpoint or not. Like perhaps we have an inbox notif that says "10% of lookup table population complete as of time" and a button to refresh.

**Comment by justinshreve** [comment]
Makes sense. I'll add the `wcSettings` value for now. If we end up needing an endpoint, this can prime the response.

One thing to note about the percentage text is that the number of jobs can change overt ime (since some jobs spawn child jobs) so it might be hard to calculate a constant percentage.

**Comment by timmyc** [comment]
> One thing to note about the percentage text is that the number of jobs can change overt time (since some jobs spawn child jobs) so it might be hard to calculate a constant/accurate percentage.

Absolutely, I was going to comment on your PR about that too. So I like what you have done there already, but also wonder if we can expose the number of batch jobs too, like total customer batch jobs and number completed, along with the order batch jobs.

Since those remain static during the install - they just spawn more child jobs - it seems like that might be a way we can calculate some rough percentages of progress. I'm very likely totally simplifying this though, but that was one of my grand ideas I had at like 5am one morning 😆

**Comment by justinshreve** [comment]
I pushed some changes here to expose number of batch jobs (total done and pending) however I still don't know if we can get a good percentage from this https://github.com/woocommerce/wc-admin/pull/1716/commits/daa3fbd9c74921995aa7810136fd9b7ac13be490.

Mainly, the issue is the batch actions complete once they've spawned child jobs -- so you might end up in a scenario where you have pending jobs to run, but all batch ones have completed. Example from where my store is at now. 

```
"reportActionCounts": {
    "all-pending":"259",
    "orders-batch-pending":"0",
    "customers-batch-pending":"0",
    "all":6883,
    "orders-batch":210,
    "customers-batch":323
}
```

Do we try to calculate percentage when there are still pending batches, and then switch over to the 'all' count?

Another issue is that the "completed" totals also stay in the database. We could save a "last run" timestamp and then use that to even further limit these queries -- but this also feels like a lot of data querying for what could be an inaccurate progress bar. I.e. multiple queries are running for these totals. Any other ideas I might be missing here?

**Comment by timmyc** [comment]
> Do we try to calculate percentage when there are still pending batches, and then switch over to the 'all' count?

This seems like it would work okay.

> Another issue is that the "completed" totals also stay in the database.

Yikes that is problematic for sure. I guess first import, not a problem, but subsequent re-processing that is indeed a problem. I concur we could try and store a timestamp for the start of the run to get proper scoping/limit the queries.

Lets bring this up during the wc-admin hangout tomorrow when we discuss David's designs.

**Comment by timmyc** [comment]
I'm going to close this in favor of #1851 - as I think that PR covers most of the use cases for this data.
