### ISSUE TITLE
Create utility to clear all pending Analytics Background Jobs

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#1699]
In the event of a site experiencing resource issues due to a large number of analytics jobs processing, it seems we should have a way to delete all pending Action Scheduler jobs for analytics. 

**Describe the solution you'd like**
I'm thinking a method which is very much the inverse of the initial install job that enqueues all the batch jobs - this util would delete all pending analytics jobs. It seems like we should have this method called when WooCommerce Admin is deactivated, but also possibly add a button to _Analytics | Settings_ where users could opt to remove all pending jobs without deactivating the plugin.

**Comment by justinshreve** [comment]
I'm reopening this one because I've been running into some issues when testing the past couple days. I've gotten a view timeouts trying to deactivate the plugin if there are a lot of jobs queued.

It seems like `cancel_all` ends up being slow because it cancels them one at a time... https://github.com/woocommerce/woocommerce/blob/6e8f9954267cfe1297bdca9a57ab711957c2918c/includes/libraries/action-scheduler/functions.php#L101-L105

For our purposes, maybe we could just do a DELETE query on the rows based on group?

I'm unassigning myself for now incase someone wants to pick this up, otherwise I'll revisit soon.

**Comment by jeffstieler** [comment]
Ping @rrennick for any insights - we could probably issue a `DELETE` query as @justinshreve has proposed, but that would only work for the WP Post data store..

**Comment by rrennick** [comment]
The actions can be unscheduled with `as_unschedule_all_actions( null, array(), WC_Admin_Reports_Sync:: QUEUE_GROUP );` .

**Comment by jeffstieler** [comment]
@rrennick we're not having trouble figuring out how to unschedule actions, we're hoping to bulk/batch unschedule the actions rather than have them happen one-by-one: https://github.com/woocommerce/woocommerce/blob/6a89a76c114c9d83097777df6ffa8bfa04fe8a6f/includes/libraries/action-scheduler/functions.php#L101-L105

**Comment by rrennick** [comment]
AS doesn't provide a way to do a bulk delete using single DB queries. WP generally tends to avoid queries affecting a large number of records to minimize deadlocks.

**Comment by rrennick** [comment]
This issue is one of the ones I was thinking of in https://github.com/woocommerce/wc-admin/pull/1759#issuecomment-470625714.
