### ISSUE TITLE
Fatal Error on activation

### ISSUE THREAD

**Issue by mujuonly** [woocommerce/woocommerce-admin#1752]
Fatal error: Uncaught Error: Class 'WC_Admin_Reports_Sync' not found.

Error while activating the plugin

WC 3.5.5
WP 5.0
![screenshot 2019-03-06 at 3 15 46 pm](https://user-images.githubusercontent.com/459367/53871864-1319c600-4023-11e9-8a08-d40deeea376d.png)

**Comment by joshuatf** [comment]
@mujuonly Thanks for reporting this issue!

>WC 3.5.5
WP 5.0

It looks like WooCommerce Admin dependencies aren't being met.  Can you double check those versions on your install and let me know if WooCommerce is activated prior to activating WooCommerce Admin?

The plugin is deactivating itself since the dependencies aren't being met and then it's trying to clear out any scheduling sync tasks which it's unable to do since the plugin classes were never initiated.  That's definitely a bug that we can tackle, but if you have any more issues getting it activated, feel free to post back here.

**Comment by mujuonly** [comment]
Is this case cannot be handled instead of throwing error?

**Comment by jeffstieler** [comment]
Thanks for the bug report @mujuonly! This has been fixed in #1797.
