### ISSUE TITLE
Parent Categories: Stat totals include child categories

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#1908]
**Describe the bug**
Discovered in https://github.com/woocommerce/woocommerce-admin/pull/1873#pullrequestreview-217812675, when comparing categories which are parent categories, Summary numbers are off. They most likely include child category numbers as well.

**To Reproduce**

1. In the Categories Report, compare parent categories such as "Music" and "Clothing" if you have woo dummy products.
2. See the totals in the table and chart be less than Summary number totals.

**Expected behavior**

I'd expect them to be the same. See "Items sold" below.

**Screenshots**

![Screen Shot 2019-03-25 at 2 01 14 PM](https://user-images.githubusercontent.com/1922453/54889025-18be4980-4f07-11e9-96d2-00724bdd12fb.png)

**Comment by psealock** [comment]
Additional comment: In the example above, only clothing seems to be undercounted as evidence by clicking through on the category name to the single category view and comparing resulting numbers.

**Comment by joshuatf** [comment]
I managed to reproduce this issue, however, the cause was a bit different than described.

In my testing, the incorrect summary numbers were due to unfiltered summary numbers that were showing all stats, regardless of category, for that time period.

When making a query to the products stats data store (which is used for stats in the Categories report), if a `categories` param is passed, the data store filters down results using a call to `get_included_products()`.  The problem is that if this is done for a category that has no products, `get_included_products()` will be empty and the condition is never applied.

I'll open a PR to handle this, but can you confirm that this happens with with your data sets @psealock and @Aljullu?
