### ISSUE TITLE
wmpl translated products are treated as individual product instances instead of being aggregated

### ISSUE THREAD

**Issue by x-moe-x** [woocommerce/woocommerce-admin#1939]
**Describe the bug**
wc-admin ignores product translations via wpml. wpml translates products via copying the original product and provide localized texts. plugins ignoring this are seeing in fact one product for every languiage available for the specific product. wc-admin should reflect this in it's products tab.

**To Reproduce**

* install wpml
* configure a default and a second language
* add a product and add a translation to the second language
* go to wc-admin's products-tab

**Expected behavior**
see products and corresponding values being aggregated (all numerical values summed up for all localizations of the product) as one product

**Current behaviour**
wc-admin lists all localization of the product as an individual product

* OS: [e.g. iOS] debian
* Browser [e.g. chrome, safari] chromium
* Version [e.g. 22] latest stable

**Comment by joshuatf** [comment]
Thanks for opening this issue @x-moe-x!  I've got a branch ready to go that will combine stats into a single product, but wanted to get a bit of discussion going first as this might open a can of worms.

>see products and corresponding values being aggregated (all numerical values summed up for all localizations of the product) as one product

I'm pretty on board with this, but wondering if some store owners would prefer to see them as separate products.  Since WPML effectively treats them as two separate entities, each translated product can have its own sku, price, and even be a different type of product (simple, variable, bookable, etc).

That's most likely not the majority, but wondering if we should bake in a setting (or at least filter) to allow this to be more configurable.

Penny for your thoughts. /cc @timmyc @Aljullu 

### Translation in reports

Should the translation names match the selected language in the backend or remain as the original product?  For example, here were my products prior to combining stats:

<img width="923" alt="Screen Shot 2019-03-29 at 3 23 59 PM" src="https://user-images.githubusercontent.com/10561050/55217714-25aaa800-523b-11e9-877e-1858e86fa2df.png">

Switching to es/en, the product remains the original translatable item:

<img width="726" alt="Screen Shot 2019-03-29 at 3 56 11 PM" src="https://user-images.githubusercontent.com/10561050/55217857-820dc780-523b-11e9-881e-99986a39ba81.png">

### Other translatable items

I also imagine we'll want to address categories and variations if we do this as they may have the same issues.

**Comment by x-moe-x** [comment]
Thanks for your comments on this topic @joshuatf! You brought up an interesting thought about how store owners could use wpml translation.

However reading about [product translation](https://wpml.org/documentation/related-projects/woocommerce-multilingual/#translating-products) I come to the conclusion that the default behavior of wpml for translating products is in fact have localized texts for otherwise identical products, so I'd vote for aggregating products by default with the option of using filters and actions. Owners that want to deviate from the default path can implement custom behavior while the preset is a reasonable default.

**Comment by Aljullu** [comment]
Thanks for reporting this @x-moe-x!

> I'm pretty on board with this, but wondering if some store owners would prefer to see them as separate products. Since WPML effectively treats them as two separate entities, each translated product can have its own sku, price, and even be a different type of product (simple, variable, bookable, etc).

@joshuatf I agree it would make sense to aggregate all different translations instead of displaying them separately. Ideally we would let WPML to change that if they want to add a setting or modify the default behavior. I didn't take a deep look at this, so I'm not sure if that needs to be fixed in WooCommerce Admin or it's something that must be added to WPML.

**Comment by timmyc** [comment]
@x-moe-x thanks for opening this issue. By chance do you know how this is handled in the current Woo reports? I agree @joshuatf this could be venturing into a 🐰 🕳 - I feel the best approach to fixing this should also exist in the plugin/extension that offers the multi-lingual support too.

**Comment by x-moe-x** [comment]
@timmyc I'm sorry, I don't know...

**Comment by timmyc** [comment]
After re-reading this, I think the best solution here is for WPML to add support for the new reports within their extension. I'm happy to talk with the developers if they need some help in exploring this.
