### ISSUE TITLE
P&L reports

### ISSUE THREAD

**Issue by kwok0781** [woocommerce/woocommerce-admin#1966]
For this new release, may I request P&L reports whereby we input the underlying cost of every item in our store and WC can calculate P&L based on the final charge price. The only complication would be free shipping.  If a zone has a free shipping calculation, can we automatically deduct the original shipping amount from the P&L?

**Comment by timmyc** [comment]
@kwok0781 thanks for opening up this issue. The first round of reports we are seeking to ship are the ones that are present in the plugin right now. I'm curious though - do you track cost of goods currently in your Woo install? Wondering if there is an extension you might be using - which could then build out a report you are looking for.

**Comment by kwok0781** [comment]
Currently I am building the P&L reports in excel after exporting WC data. It would be great to run everything directly inside WC since they have all the transaction data anyways




On Tuesday, April 2, 2019, 8:28 AM, Timmy Crawford <notifications@github.com> wrote:


@kwok0781 thanks for opening up this issue. The first round of reports we are seeking to ship are the ones that are present in the plugin right now. I'm curious though - do you track cost of goods currently in your Woo install? Wondering if there is an extension you might be using - which could then build out a report you are looking for.

**Comment by RiaanKnoetze** [comment]
2103109-zen

Customer of our [Cost of Goods](https://woocommerce.com/products/woocommerce-cost-of-goods/?aff=10486&cid=1131038) extension asked about compatibility. The marketplace devs behind [Cost of Goods](https://woocommerce.com/products/woocommerce-cost-of-goods/?aff=10486&cid=1131038) forwarded the following:

> Woo team, Bob wrote in to us asking about the new WooCommerce Admin plugin and asked if it would work with WooCommerce Cost of Goods. I can see after testing that it does not take Cost of Goods costs into account in its reports. Bob would like to know if there are any plans to include Cost of Goods in the new Admin reports going forward.

**Comment by joshuatf** [comment]
Hey @kwok0781 👋 I know its been a while since you opened this issue, but wanted to follow up.  I think the best venue for adding cost of goods would be to use a plugin that has this functionality.  The current scope of WooCommerce Admin is purely for reporting on existing data, but we encourage plugin authors to extend these reports with any data they may have.

@RiaanKnoetze I think the responsibility of adding cost of goods data would need to fall on the Cost of Goods plugin.  

There are a number of example extensions and docs that may be useful for plugin authors wanting to extend reports.  Below are a couple of links, but I'd be happy to answer any questions and help out the Cost of Goods devs if they're up for it. If you can, please reach out to them and see if they need any help with this and we can follow up here or in Slack.

[Example extensions](https://github.com/woocommerce/woocommerce-admin/tree/main/docs/examples/extensions)
[Guide on extending](https://developer.woocommerce.com/2020/02/20/extending-wc-admin-reports/)

Going to close this issue for now, but feel free to reopen or ping me for any additional questions.
