### ISSUE TITLE
Dashboard: Add Ability to Move Section Up/Down

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2121]
Child Issue of #2009 / Dependent upon #2120 

See #2120 for a bit more background - but again for this enhancement I'm thinking we leverage the existing pattern of the Ellipsis menu to expose the ability to move a Dashboard section up/down in display. And again for this feature, I'm thinking we lean a bit on established patterns in the block editor:

![block-order](https://user-images.githubusercontent.com/22080/56834859-7657f580-6827-11e9-82f4-11baec29ddb8.gif)

My reasoning for using the Ellipsis menu again is we don't have an "edit state" for the dashboard. In some early designs, @jameskoster had a notion of a Dashboard Settings button - but I think exposing the option to change the order of the sections works well in the ellipsis menu too.

- Under the new "Customize" Menu Title section in the ellipsis menu, add options to move the section up or down in the display of the dashboard.
- Following the gif above - if a section is at the top already, "Move Up" should not be an option, and likewise if the section is already at the bottom "Move Down" should not be shown.
- Until we have a persistence layer that we are writing/reading from for dashboard preferences, lets just have the sections change order in the dashboard state

**Comment by josemarques** [comment]
@timmyc here's the design for moving section up and down:

![Dashboard - Move block](https://user-images.githubusercontent.com/57050/56974129-29955700-6b66-11e9-9bd0-822be7c1b4eb.jpg)

This adds "Move up" and "Move down" controls to the section settings menu. If the section is at the top position the "Move up" option is not shown, and the same if the section is at the bottom position for the "Move down" option.

We opted for this approach instead of using the ellipsis Gutenberg pattern since that would require having a "edit mode" for this screen that would allow revealing the controls when the user hovered the block.
