### ISSUE TITLE
Packages: Audit / Move to New Repo / Contribute Upstream

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2123]
This task was born out of our Q1 retro. As more teams internally at Automattic, and third-party developers everywhere, want to begin building and contributing to with the various npm modules that are exported from this repository, it is becoming evident that some components might be best housed in a stand-alone repo.

@ryelle also added this great bit of feedback on the topic:

> If we’re looking to move @woocommerce/components (good idea), it could be nice to take the time to audit the components and split out some of the more data/nav intensive components (like filters, charts, maybe search?). It’s pretty complicated to use one or two components when it also brings along the entire navigation library, for example.

Another item while doing this task is we should determine which components we should contribute upstream to `@wordpress` / gutenberg.

So this issue is looking for someone who would be keen to:

- Audit our [components](https://github.com/woocommerce/woocommerce-admin/tree/master/packages/components/src) and determine which ones are very specific to wc-admin ( data / navigation items ), and how we should best handle those. Maybe create a new `@woocommerce/wcadmin-components` package?
- Determine which components might be good to contribute to `@wordpress`
- Create a new repo for the `@woocommerce/components` to live in and be published from

Any other thoughts on this one @woocommerce/isotope

**Comment by psealock** [comment]
Having not been at the Q1 retro, I'd like to get clarity on the motivation behind this idea.

I'm hesitant on this idea because it introduces friction by requiring development in two repos while using tricks like `npm link`. Is it worth the effort to get our components out to a wider array of users and use cases?

If the idea is to decouple components as much as possible from dependencies like `@woocommerce/navigation` and woo-specific styling for use outside of woocommerce or even wordpress itself, can I propose another idea?

Can we use Lerna to create a new package in this repo for those components that fit the bill for standalone usage? This would alleviate the development problem while making components available on npm under a new namespace. 

Are there benefits of a new repo that I'm not seeing?

**Comment by timmyc** [comment]
@psealock thanks for chiming in, and bringing up some very valid points - especially:

> I'm hesitant on this because it introduces friction by requiring development in two repos while using tricks like npm link

_shudders_

To revisit the retro, and for the sake of transparency - the main goals of the move are:

- Eliminate some of the pain points that we experienced in the blocks project with consuming the components. A specific example of this was some bugs introduced by the wc-admin nav components when used elsewhere.
- Separation of components that are likely to be used elsewhere, and ones that are more wc-admin centric
- Identify components up-stream to WordPress core which we feel will have more use outside of Woo
- Try to make contributing to these components easier for other teams at a8c, and in the broader Woo community

Using those as our guides, I would say your suggestion of:

> Can we use Lerna to create a new package in this repo for those components that fit the bill for standalone usage? 

... would definitely satisfy the first two goals above. So that seems like a reasonable approach to me.

I suppose since wc-admin is still the primary consumer of these components, your argument about developer friction is a very valid point. But I do think at some point in the future, other teams like Hydra might begin to contribute more to the `@woocommerce/components` so they might then feel the burden of that dev flow.

But that is all conjecture at this point, so it seems taking your new package approach in the repo here would be an excellent in-between step... and if/when the time comes we need to split out packages it will be easier to do so then.

/cc @ryelle for thoughts.

**Comment by psealock** [comment]
`/packages/components/.` can be divided into three categories:

### WordPress

Can we can contribute this component upstream to Gutenberg? These are ideal for general purpose use and are disconnected from all WooCommerce logic and styles.

### woocommerce/components

Components which make sense in the WooCommerce context, but could be used outside of it as well. In other words, their logic will be free from wc-admin specifics and they can serve as a useful building blocks for extension developers or teams like Hydra who are looking to leverage this work as they build out screens.

A goog example is the `EllipsisMenu`. It could be used outside of WooCommerce but its not likely because its simply a really convenient wrapper for `Dropdown` (and others) that applies WooCommerce styling and uses. 

![Screen Shot 2019-05-06 at 1 53 42 PM](https://user-images.githubusercontent.com/1922453/57203695-664dcc00-7006-11e9-9e02-705fa34165d0.png)

Hydra may find this component useful and can apply it in any manner they choose, but your average wordpress developer likely won't be able to take advantage. 

### woocommerce/wc-admin

These components are uniquely tied to wc-admin. Their use outside of this context doesn't make sense due to either tightly coupled logic or designs.

The `Filters` component is a good example. Its logic is really only useful in a report in wc-admin because its intensely tied to navigation.

| Component                 | Repository             | Comments                                                                                                                                    |
|---------------------------|------------------------|---------------------------------------------------------------------------------------------------------------------------------------------|
| animation-slider          | woocommerce/components |                                                                                                                                             |
| calendar                  | woocommerce/components | Date Range Picker could be pulled apart and contributed to @wordpress                                                                       |
| card                      | woocommerce/components |                                                                                                                                             |
| chart                     | woocommerce/components | A few uses of navigation function will need to be removed first                                                                             |
| count                     | woocommerce/components |                                                                                                                                             |
| date                      | WordPress              |                                                                                                                                             |
| dropdown-button           | woocommerce/components |                                                                                                                                             |
| ellipsis-menu             | woocommerce/components |                                                                                                                                             |
| empty-content             | woocommerce/components |                                                                                                                                             |
| filters                   | woocommerce/wc-admin   |                                                                                                                                             |
| flag                      | woocommerce/components |                                                                                                                                             |
| gravatar                  | WordPress              |                                                                                                                                             |
| higher-order              | woocommerce/components | These are not currently used, but use-filters is useful                                                                                     |
| image-asset               | woocommerce/wc-admin   |                                                                                                                                             |
| link                      | woocommerce/components | Although tied to wc-admin, this one can be really useful for extensions creating screens in wc-admin                                        |
| order-status              | woocommerce/wc-admin   | Has reliance on `wcSettings`                                                                                                                |
| pagination                | woocommerce/components |                                                                                                                                             |
| product-image             | woocommerce/components | References to `wcSettings will need to be removed first                                                                                     |
| rating                    | woocommerce/components |                                                                                                                                             |
| search                    | woocommerce/wc-admin   | This could be in woocommerce/components and would be useful, but a good amount of work will be required to pull apart preset autocompleters |
| search-list-control       | woocommerce/components | Only used by blocks at the moment                                                                                                           |
| section                   | woocommerce/components | Hierarchy starts at `h2` so its tied to wc-admin at the moment. It will need to be more agnostic.                                           |
| section-header            | woocommerce/components |                                                                                                                                             |
| segmented-selection       | woocommerce/components |                                                                                                                                             |
| split-button              | woocommerce/components |                                                                                                                                             |
| summary                   | woocommerce/wc-admin   |                                                                                                                                             |
| table                     | woocommerce/wc-admin   | Parts of this component would be great in woocommerce/components if some dependencies can be teased out.                                    |
| tag                       | woocommerce/components |                                                                                                                                             |
| text-control-with-affixes | woocommerce/components |                                                                                                                                             |
| view-more-list            | woocommerce/components |                                                                                                                                             |

**Comment by ryelle** [comment]
The idea of `@woocommerce/wc-admin` is to just be the app, not exporting another set of components, right?

> `section`: Hierarchy starts at h2 so its tied to wc-admin at the moment. It will need to be more agnostic.

We should leave it as the h2, since there should only be one h1 on a page, that should be handled separately outside of the reusable-section component.

> `chart`, `search`, `table`… other things with wcSettings dependencies

Sounds like these will be/could be in `@woocommerce/components` but also have counterparts in `@woocommerce/wc-admin`?

**Comment by psealock** [comment]
>The idea of @woocommerce/wc-admin is to just be the app, not exporting another set of components, right?

Yes, although extensions will still need access when building out reports and screens. Filters, for example can still be used by 3PD, which means it'll need to be on the window, which means it'll need to get exported 🤔. 

>We should leave it as the h2, since there should only be one h1 on a page, that should be handled separately outside of the reusable-section component.

Great point, I'll update the table.

>Sounds like these will be/could be in @woocommerce/components but also have counterparts in @woocommerce/wc-admin?

Could we pass in a settings prop? Thinking further about your first point, it looks like `@woocommerce/wc-admin` would need to get exported anyways, so perhaps we can leave them as is.

**Comment by psealock** [comment]
I'm going to close this for now. With a bi-weekly release cadence of wc-admin and an npm release process that can be made anytime, publishing updates is relatively painless. When Hydra ramps up usage of our components, we can revisit this issue.
