### ISSUE TITLE
Data not populating

### ISSUE THREAD

**Issue by glamble007** [woocommerce/woocommerce-admin#2130]
None of my data is getting populated. I am getting constant 500 error in G-chrome console.

On opening the status 500 url - {"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}} is the message.

**Comment by rrennick** [comment]
@glamble007 Are you still seeing this? If so, could you provide us with some detail about your install?

**Comment by rrennick** [comment]
Closing this for lack of feedback.

**Comment by onemanparsons** [comment]
@rrennick I was pointed to this issue by a WC support team member. We are experiencing this issue on our website: https://www.capecross.co.za. 

Some details (let me know if you need more info here): 
- Site is running on Apache shared server
- We use CloudFlare with default settings. There are no firewall rules set up. 
- I've tested for and ruled out plugin and theme conflicts
- The issue is occurring intermittently on different reports in WooCommerce Analytics. * Currently the issue just seems to occur on Month to Date and Last Year view. Reports seem to load correctly when I choose a different date range.
- When I view the error in console, I see the following error message: Failed to load resource: the server responded with a status of 500 () – {"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}

**Comment by rrennick** [comment]
> I was pointed to this issue by a WC support team member.

@onemanparsons Was this through a support ticket or WordPress.org forum thread? We don't offer support through this Github repo.

This issue was closed over two years ago and there have been over 20 releases of WC Admin since this issue was created. A 500 status is a fatal error. You may be able to find the error in your server's error logs.
