### ISSUE TITLE
Why does WCAdmin depend on calls from 77.104.133.171 ?

### ISSUE THREAD

**Issue by kwok0781** [woocommerce/woocommerce-admin#2380]
I am on a hosted server plan and have been hitting limits on usage.  When I check the logs, there are 11,946 hits coming from 77.104.133.171.  Once I block this IP address, the charts in WCAdmin no longer work.  Why is this plugin dependent on data coming from 77.104.133.171 and is my data being sent off to a third party?  

How do I minimize these calls to an external server?

**Comment by timmyc** [comment]
@kwok0781 the WooCommerce Admin plugin does not make calls to any external servers in order to process data or function properly. Doing a lookup on that IP address it resolves to:

```
inetnum:        77.104.133.0 - 77.104.133.255
netname:        UK-SITEGROUND
descr:          SiteGround Hosting Ltd.
```
WooCommerce does collect usage data, which you can read more about [here](https://woocommerce.com/usage-tracking), but you can disable that and wc-admin will still function.

Hope that helps!
