### ISSUE TITLE
Use on the production site

### ISSUE THREAD

**Issue by code-estari** [woocommerce/woocommerce-admin#2413]
Does using the "WooCommerce Admin" plugin on the production site carry any risk for the website itself, its operation and its data? 

Is the information on the page of the plugin:
_"This project is in an active development, and it is not ready for the use of."_ - applies only to the fact that some elements of the plugin may not yet work fully?

**Comment by rwkyyy** [comment]
Yes, the plugin is in an early beta state, you can use it on a production, but I do not recommend it because from my testing it does alot of load in migrating the data (if you want it done fast) and it tends to be a little slow on big data, plus the `woocommerce_admin_note_action `runs hourly and can give you some load as well.

If you really need it, I suggest rigourous testing on a local development then install it.

**Comment by code-estari** [comment]
Ok, thanks for information.
