### ISSUE TITLE
Datepicker gets covered by title bar on Edit Order screen

### ISSUE THREAD

**Issue by robertdevore** [woocommerce/woocommerce-admin#2435]
When you edit an order and click the date, the datepicker opens up and the top is partially covered by the new title bar.

It looks to just be because the title bar has a large z-index, so by adding a slightly larger z-index to the datepicker in the admin screen CSS, it would display the datepicker above the title bar.

Before:

![datepicker-css-update-before](https://user-images.githubusercontent.com/9917957/59568135-9c8a5c80-9044-11e9-9d51-1830159f7d91.jpg)

After:

![datepicker-css-update-after](https://user-images.githubusercontent.com/9917957/59568136-a14f1080-9044-11e9-9250-6525b8f29b70.jpg)

I'd be happy to submit the CSS update as a pull request, just figured I'd open a ticket first.

**Comment by timmyc** [comment]
Thanks for the bug report @robertdevore - z-index strikes again!

> I'd be happy to submit the CSS update as a pull request, just figured I'd open a ticket first.

That would be fantastic if you have time to do so.

**Comment by Aljullu** [comment]
Just to add some thoughts to the discussion. Are we sure we want to display the date picker on top of the header bar? When scrolling (see GIF below), I expect the date picker to stay below the header bar:

![Peek 2019-06-18 19-58](https://user-images.githubusercontent.com/3616980/59707779-9ee6e500-9203-11e9-80aa-9b7c53e1d4a9.gif)

I think the best solution for this specific issue would be to open the datepicker at the bottom of the input field instead of the top, so it's not overlapped by the header bar. But I'm not sure how easy that would be or if it's even possible.

**Comment by timmyc** [comment]
I concur @Aljullu it seems that anchoring at the bottom of the element would be a great solution here. Also something for us to consider as we look at updating the orders page design ( @dreiris  )

**Comment by rrennick** [comment]
It looks like this one has been fixed in WC core (3.7.0 RC). The calendar opens below the date field unless the page is scrolled to where there isn't room for it below. Closing, if this issue returns please re-open.
