### ISSUE TITLE
Note dismiss button

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#2505]
**Is your feature request related to a problem? Please describe.**
Support thread: https://wordpress.org/support/topic/filters-to-remove-inbox-ads/#post-11670256

Currently the only way to dismiss a Note from the Inbox is to click on the action button. Non-dismissible admin notices are a pain point in many installs. Some store owners will want to dismiss the notes without opening the related link.

**Describe the solution you'd like**
Add a dismiss button to notes to mark them as `dismissed` to remove them from the inbox. To go with this it would be great to add a way to review dismissed notes.

**Describe alternatives you've considered**
Add filter(s) to the REST API endpoint to allow removing them dynamically. This would probably be a more robust solution if the notes had data on the source of the note.

**Comment by timmyc** [comment]
Existing REST API endpoint exists for updating a note, which would allow for "dismissal" to happen from the UI. We would need some design direction on this /cc @jameskoster

**Comment by jameskoster** [comment]
One feature I'd like to introduce to the Inbox is Tabs for "Unread" and "Read" notifications. Once a notice has been viewed (read) it should be moved to the "Read" Tab. This effectively "dismisses" notices automatically while still keeping them accessible.

As for allowing folks to programatically remove Inbox notifications... I think we should hold off on that. If people want to remove notifications it's because the notifications aren't bringing any value. This would be a failure on our part in ensuring that our notices are contextually relevant to the store in question. Of course we can't guarantee they will all be super-high value, but people shouldn't be wanting to entirely disable them 🙈. AFAIK we aren't serving _any_ "ads" in the Inbox just yet. Is that correct?

**Comment by timmyc** [comment]
> If people want to remove notifications it's because the notifications aren't bringing any value.

This is a valid point. We could analyze the tracks data on Panel opens vs actions taken on the different note types, and determine which are yielding more value ( via actions ) vs others that aren't actioned upon as often.

Having a way to "dismiss" or hide a notification would be another indicator though to let users both remove un-wanted notices, and inform us of those they didn't find useful. One thing to consider here is we do have a limit right now of showing the last 10 notices ( #864 ). If the only way to clear a notice is to action upon it, then as notices stack up, only the 10 most recent will be shown.

> Tabs for "Unread" and "Read" notifications

This sounds interesting, but also if a note is read, and unactioned, what is the value in keeping it around in an "unread" column? I suppose due to the nature of notices being shared amongst all store managers it might be a way for everyone to see things that have been read by others.

> AFAIK we aren't serving any "ads" in the Inbox just yet. Is that correct?

Well I think what people consider ads can really be interpreted in many ways. I'm certain some would consider the nudge to connect to WooCommerce.com an ad - though we likely don't. In the current sprint we plan to add a notice to encourage installation of the Facebook extension #2538 

We might need to consider and possibly reach out to the plugin team to see if we **should** be providing a way to close out/dismiss the inbox notes per the repo guidelines.

**Comment by jameskoster** [comment]
> but also if a note is read, and unactioned, what is the value in keeping it around in an "unread" column?

Once a note has been viewed, it would be moved to the "Read" tab, regardless of whether action was taken or not. I think there's value in keeping read-but-unactioned notes around because not all notes need to be, or will be, actioned immediately - and that doesn't necessarily mean they lack value. If they're out of the way (visually speaking) in the "read" tab I think that counts as adequate "dismissal", for now. 

I'm not 100% against more destructive note dismissal, but it needs further investigation before implementation. It would be really annoying if you dismissed a note only to later want to action it. So we'd also need to consider some kind of trash search & retrieval system as well. At that point it really starts to feel like overkill for a feature of this nature, which is why I'm hesitant.

Re ads, one idea would be to add an Inbox filter feature for note types. That way folks could view certain note types on demand or just permanently hide (not disable) them if they need to. We could save the filter per user, so the right people are always looking at the right note types. This way a merchant can disable ads to begin with, then review them once their store starts making money. If they're disabled entirely merchants will forget about them which is a missed opportunity for us and for them.

I remain optimistic that if we can be really smart about how we serve ads to people, they won't _want_ to disable them. If people want to disable our ads entirely that means the protocol for serving them has failed. Obviously that protocol won't be perfect to begin with, so we should be extremely passive about our suggestions while we fine tune things. But I still think that if we offer a way to programatically disable them, we're kind of undermining the purpose of this feature. I'd prefer us to concentrate our efforts on making the feature valuable before we do that.

I appreciate this is a controversial subject though. A broader discussion should be had for sure.

**Comment by rrennick** [comment]
> This would be a failure on our part in ensuring that our notices are contextually relevant to the store in question.

The reason I created this issue is that it was noted in the support thread that there is already another plugin using our note functions to add notes to the Inbox. We have no control over the relevance of notes added by other plugins.

**Comment by jameskoster** [comment]
Hmm, ok, good point. 

Going back to the filter idea then, would it be possible for us to require classification for third party notes? So if an extension adds an advertisement, but the user has filtered those out, they wouldn't see it?

I know there would be ways around that (devs marking ads as something else), but at least then the responsibility (and blame) lies squarely on the extension author.

**Comment by timmyc** [comment]
> Going back to the filter idea then, would it be possible for us to require classification for third party notes? So if an extension adds an advertisement, but the user has filtered those out, they wouldn't see it?

We can try to add safeguards, but developers will probably be able to side-step them.

**Comment by jameskoster** [comment]
I think that's OK as long as we provide clear and public principles for developers to follow. The onus is then on them to behave appropriately. If we make it easy for folks to do the right thing I'm optimistic that the vast majority will do just that.

Naturally this would be a requirement in our marketplace UX guidelines as well.

In the case of support tickets like @rrennick surfaced, we'd inform the user that the extension in question isn't following our guidelines, and advise them to reach out for an update. If the author refuses to update, it's down to the customer whether they continue to use it or look for an alternative.

**Comment by psealock** [comment]
Closing as this functionality exists.
