### ISSUE TITLE
Customer Report: Negative Total Spend and AOV

### ISSUE THREAD

**Issue by derekakelly** [woocommerce/woocommerce-admin#2522]
**Describe the bug**
I've used several other email addresses in the past to create orders and test my website. So I fully expected to have my name come up multiple times. But not with a negative result.

**To Reproduce**
First I searched for myself in the Customer Report, then i compared it to a search for myself in my list of Orders.

It seems as if when an order is both refunded and marked as cancelled it's counted twice.

**Expected behavior**
I expected to see $0

**Screenshots**
![dk-cust-report](https://user-images.githubusercontent.com/5824837/60213063-ae33e700-9830-11e9-9c4d-106b2fda163c.png)
![dk-orders](https://user-images.githubusercontent.com/5824837/60213071-b2600480-9830-11e9-97a5-92d3b048e913.png)

**Comment by psealock** [comment]
Thanks for reporting this. It should be $0.

**Comment by jeffstieler** [comment]
@derekakelly can you elaborate on your process that includes marking refunded orders as cancelled? _(I'm just curious)_

@psealock this is being caused because [we exclude the `wc-cancelled` order status](https://github.com/woocommerce/woocommerce-admin/blob/master/src/API/Reports/DataStore.php#L465) from queries for report data. How do you feel about forcing a `wc-refunded` status in our lookup table for orders that have been refunded, rather than updating the status to something like `wc-cancelled`?

**Comment by jeffstieler** [comment]
@derekakelly - if you go to Analytics > Settings and remove `Cancelled` from the "Excluded Statuses" does that resolve the issue for you?

![Screen Shot 2019-08-16 at 9 17 29 AM](https://user-images.githubusercontent.com/63922/63182174-c7723c00-c006-11e9-9d03-bdc1790343ba.png)

**Comment by psealock** [comment]
>How do you feel about forcing a wc-refunded status in our lookup table for orders that have been refunded, rather than updating the status to something like wc-cancelled?

That certainly would satisfy the use case here, but the concern is opening another can of worms and potentially unexpected behavior. 

I'm also curious what the process is for labelling refunded orders with the `cancelled` status.  cc @derekakelly

**Comment by derekakelly** [comment]
Hi @psealock 

For us at least, an order is marked as being canceled automatically after it's been voided. Voided transactions only happen the day of the original sale.

Here's an example of a customer ordering an item. Our drop ship vendor was out of stock, so we voided the transaction and it automatically canceled the order.


`Order status changed from Processing to Cancelled.

July 20, 2019 at 9:48 am

Authorize.Net Credit Card Void in the amount of $7.63 approved. (Transaction ID XXXXXXXXXXX)

July 20, 2019 at 9:48 am

Order status changed from Pending payment to Processing.

July 20, 2019 at 7:58 am

Authorize.Net Credit Card Charge Approved: MasterCard ending in XXXX (expires XX/XX) (Transaction ID XXXXXXXX)

July 20, 2019 at 7:58 am`

**Comment by jeffstieler** [comment]
Hello @derekakelly,

Thanks for the extra context around cancelled orders.

In order to reproduce this I had to refund an order, and then cancel it - which resulted in a "Order status changed from Processing to Refunded" log item, which I'm not seeing in your example.

Perhaps the payment gateway extension is creating a refund order behind the scenes? Which Authorize.net extension are you using?

Thanks!

**Comment by derekakelly** [comment]
Hi  @jeffstieler ,

I am using the official WooCommerce Authorize.Net plugin from woocommerce.com. I just checked, there used to be several versions, but I guess they merged into one now.

**Comment by derekakelly** [comment]
@jeffstieler 

Yes, removing canceled orders from the exclusions does result in correct AOV values being produced.

**Comment by jeffstieler** [comment]
@derekakelly I'm inclined to say that's the solution then! Please let us know if the inclusion of Cancelled status orders causes any other issues your reports.

@psealock - the Authorize.net extension filters `woocommerce_order_fully_refunded_status` so the refunded order never gets the `refunded` status - only `cancelled`.
