### ISSUE TITLE
Order Panel: Completed Orders Linger in List

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2592]
**Describe the bug**
After marking an order as completed ( a non-actionable status ) the order is still shown in the activity panel with the old order status.

**To Reproduce**

1. Have an order that has an "actionable" status and shows up in the activity panel.
2. Edit the order to a non-actionable status, i.e. mark it as complete.
3. Note after the POST of the edit order form is completed, the order is still shown in the order activity panel
4. Navigate to the wc-admin dashboard, and the order will still be in the panel.

**Expected behavior**
Completed orders to no longer show in my activity panel

**Comment by jeffstieler** [comment]
So it seems this bug is really just the delay between the order being updated and Action Scheduler processing the job created to update it in our stats table.

A possible solution is to rework the Orders panel to query the core WC `/wc/v3/orders` endpoint instead of our `/wc/v4/reports/orders` endpoint. Does that seem reasonable? One downside to using the core endpoint is that we aren't getting the aggregate values we've decided to track in the stats table.

**Comment by psealock** [comment]
What do you think about adding a mechanism to bypass Action Scheduler for new/updated orders?

**Comment by jeffstieler** [comment]
> What do you think about adding a mechanism to bypass Action Scheduler for new/updated orders?

We introduced action scheduler for this so we don't interrupt more important order processing on save: https://github.com/woocommerce/woocommerce-admin/issues/429.

If switching to the core endpoint (which I'm trying now) solves the timing/refresh issue - I think that's a better way to go.
