### ISSUE TITLE
currency symbol not showing  properly

### ISSUE THREAD

**Issue by prashantcs8** [woocommerce/woocommerce-admin#2615]
**bug**
Indian rupee currency symbol not showing  properly
in my theme functions.php  
`if (isset($woocommerce) || !function_exists('WC')) {

    function amm_add_scripts() {
        wp_enqueue_style('font-awesome', get_stylesheet_directory_uri() . '/assets/css/font-awesome.min.css', false);
    }

    add_action('wp_head', 'amm_add_scripts');

    function amm_add_admin_scripts() {
       wp_enqueue_style('font-awesome', get_stylesheet_directory_uri() . '/assets/css/font-awesome.min.css', false);
    }
    add_action('admin_enqueue_scripts', 'amm_add_admin_scripts');  
    function amm_add_INR_currency($currencies) {
        $currencies['INR'] = '<i class="fa fa-rupee"></i> ';
        return $currencies;
    }

    add_filter('woocommerce_currency_symbols', 'amm_add_INR_currency');
}`

it works both frontend and dashboard 
but not worked in
domain/wp-admin/admin.php?page=wc-admin#/analytics/revenue

**Screenshot**
https://imgur.com/pRCxXHO

**Comment by psealock** [comment]
In order to render the markup, we’d need to use React’s [dangerouslySetInnerHTML](https://zhenyong.github.io/react/tips/dangerously-set-inner-html.html), which would open up the app to vulnerabilities. 

Do you need an svg icon? The Indian Rupee is available as a currency symbol http://hookr.io/filters/woocommerce_currency_symbols/.

Otherwise, you can do this:
```php
function amm_add_INR_currency($currencies) {
    $currencies['INR'] = ₹;
    return $currencies;
}
```

**Comment by psealock** [comment]
I’m going to close this because rendering outside code is not a good idea, but happy to help otherwise.
