### ISSUE TITLE
Business Details Revenue Options i18n

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#2768]
When reviewing https://github.com/woocommerce/woocommerce-admin/pull/2763, Josh raised a concern about our revenue question.

<img width="256" alt="Screen Shot 2019-08-08 at 9 48 12 AM" src="https://user-images.githubusercontent.com/689165/62708558-a8016080-b9c1-11e9-9b76-bce2eddcb5fa.png">

> One small issue here, but we might need to tackle in a follow-up- this actual value may vary greatly from currency to currency and in many currencies might be a very small amount.

> I wonder if there are any packages that can convert to rough approximations/ranges based on currency.

https://github.com/woocommerce/woocommerce-admin/pull/2763#discussion_r311856562.

I did a quick search for packages and nothing jumped out unless we want to start pulling in exchange rates.

Since this is an approximate range, maybe we could just hard code these strings with translator comments (instead of just adding the currency symbol)? The slug would still remain `10000-50000`, unless we just saved the translated string or something.

Any other ideas?

cc @joshuatf @jameskoster @pmcpinto

**Comment by pmcpinto** [comment]
I imagine that even with [money.js](http://openexchangerates.github.io/money.js/) or [currency.js](https://currency.js.org/) it would be tricky to accurately adjust the values to any currency.

> Since this is an approximate range, maybe we could just hard code these strings with translator comments (instead of just adding the currency symbol)?

@justinshreve so your suggestion is to keep the same ranges independently of the country and just localize the currency symbol?

**Comment by joshuatf** [comment]
>Since this is an approximate range, maybe we could just hard code these strings with translator comments (instead of just adding the currency symbol)? 

I think this might be a good simple solution to this problem.  I think since the currency symbol is included in the tracking data, that should be enough information.

Side note for development: I think if we do this we'd need to add the currency symbol directly to the string instead of using `sprintf` since store language and currency may differ.

**Comment by joshuatf** [comment]
https://github.com/woocommerce/woocommerce-admin/pull/3059 did not fix this issue since the variable needed for the currency would not be pulled into the POT file.

@justinshreve noted another possible solution we can consider going forward:

>I wonder if we should/could ask for their currency up front (on the store details screen), and then we hard code in the ranges for some top currencies (USD, EUR, etc) that we can return depending on that setting. Fallback could either be USD, or just not show the question in those cases.

@justinshreve Are there any other ways a store owner might set the currency before seeing this screen?  Or will it always be in USD by default?

**Comment by justinshreve** [comment]
> Are there any other ways a store owner might set the currency before seeing this screen? Or will it always be in USD by default?

If they navigate from the wizard and go to the settings screen manually, they could change it. We only force them into the wizard view on dashboard pages at the moment.

**Comment by pmcpinto** [comment]
Today when I was testing the new onboarding and selected Portugal as a country I got the GBP symbol (£), both on the Business Details and the Shipping step. I was expecting to get the euro or the dollar symbol.

<img width="1440" alt="Shipping task" src="https://user-images.githubusercontent.com/3380168/67228959-3d918580-f432-11e9-90ee-711d6ad2186c.png">
<img width="1440" alt="Business Details-3" src="https://user-images.githubusercontent.com/3380168/67228979-484c1a80-f432-11e9-8109-45a67c712a8e.png">

What if instead of asking for the currency upfront we just assume it based on the country and hard code it?
US - dollar
EU countries - euro
India - indian rupee
UK - pound sterling
Brazil - real 
More 2-3 of the top countries
Rest of the world - dollar

**Comment by justinshreve** [comment]
>  I got the GBP symbol (£)
> Or will it always be in USD by default?

That reminds me --  GBP is actually the WooCommerce default: https://github.com/woocommerce/woocommerce/blob/c802677875d3618182a88dbfb60aadb0d65d9912/includes/admin/settings/class-wc-settings-general.php#L234-L243

> What if instead of asking for the currency upfront we just assume it based on the country and hard code it?

I think this would be the best course of action, considering we also need to set currency position, thousands separator, etc. If I remember correctly, we do something similar for Store on WP.com and the eCommerce plan.

Tip for ourselves: https://github.com/Automattic/wp-calypso/blob/97569a3c821c111dba318498cdf79d45db32a217/packages/format-currency/src/currencies.js can be used to figure out currency position, etc.

**Comment by pmcpinto** [comment]
> I think this would be the best course of action, considering we also need to set currency position, thousands separator, etc. If I remember correctly, we do something similar for Store on WP.com and the eCommerce plan.

I this compile that info if it still doesn't exist anywhere.

**Comment by justinshreve** [comment]
Created a separate issue for setting the default currency settings: https://github.com/woocommerce/woocommerce-admin/issues/3101. This issue can stay focused on the i18n of the business details question.

**Comment by rrennick** [comment]
> Are there any other ways a store owner might set the currency before seeing this screen? Or will it always be in USD by default?

The wizard is now setting the currency based on the country selected in the store address #3110. Since we can pull the currency symbol from WC, translating the range seems the best approach

> Since this is an approximate range, maybe we could just hard code these strings with translator comments (instead of just adding the currency symbol)? The slug would still remain 10000-50000

**Comment by joshuatf** [comment]
Sorry to be late to replying on this one- I'm not sure that https://github.com/woocommerce/woocommerce-admin/pull/3251 solves the issue.  Let me re-outline the issue:

**The problem**

Currencies shown after the initial store details step are currently broken on master and can't work with hard-coded strings.  The issue of currency code used in subsequent steps is separate from this thread and covered here - https://github.com/woocommerce/woocommerce-admin/issues/3318

This issue (#2768) is meant to cover how ranges differ from currency to currency.  E.g., the range of 2500 - 10000 USD is vastly different in value than 2500 - 10000 MXN.

**What we know so far**

* Adding currencies directly inside strings to translate does not work since a store's language does not determine its currency. `__( 'Even though this is English, USD may not be the currency for this store.', 'woocommerce-admin' )`
* Passing currencies through `sprintf` or as variables does not work since they won't be seen by the translator. `sprintf( __( 'These vars are not visible to translators:  %s to %s', 'woocommerce-admin' ), currencyValue1, currencyValue2 )`
* Passing a range from a currency may or may not have issues with ranges since a language may format number ranges in different ways. `sprintf( __( 'This may be problematic for RTL languages: %s', 'woocommerce-admin' ), formattedRange )`

**Possible solution**

My current thought is that if we really want to solve this we can go back to getting a rough range based on the currency.  Since @justinshreve has added currency data for the most commonly selected countries, we could create an exchange rate value which we can then round to the nearest nth number.

```
MX: {
	code: 'MXN',
	symbol: '$',
	symbolPosition: 'left',
	thousandSeparator: ',',
	decimalSeparator: '.',
	precision: 2,
        exchangeRate: 0.051 // This is a rough exchange rate to USD.  Precision is not paramount.
}
```

Then we can use `currency.exchangeRate` against the range numbers and round to the nth number.

**Comment by justinshreve** [comment]
> My current thought is that if we really want to solve this we can go back to getting a rough range based on the currency

I like this solution, especially now that we have the other currency data it can sit along side.
