### ISSUE TITLE
Onboarding payments missing action button

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#2879]
**Describe the bug**
If a user leaves the onboarding flow after the payment gateways are installed but before they are configured then when they return they start at the beginning of the gateway step again. The gateway plugins are already installed and active. The `Proceed` button is hidden so the user cannot continue.

**To Reproduce**

1. Restart onboarding
2. Follow onboarding to payment gateways
3. Choose Stripe & PayPal
4. Install & activate
5. Click on WP Pages menu item
6. Go back to onboarding
7. Repeat starting at 2

**Expected behavior**
The `Proceed` button should be visible whether or not plugins needed to be installed.

**Screenshots**
<img width="887" alt="Screen Shot 2019-09-04 at 8 39 26 AM" src="https://user-images.githubusercontent.com/343847/64252423-45807f00-cef1-11e9-8cc0-294bba88e7dc.png">

**Desktop (please complete the following information):**

* OS: MacOS
* Browser Chrome 
* Version 76.0.3809.100

**Comment by justinshreve** [comment]
Thanks for the report Ron!

The payments task is still in heavy development (#2684) and installation is pretty much the only thing that works at the moment. This will be addressed in a follow-up PR coming up soon that allows for configuring the methods, and jumping back into the correct part of the task (which will be necessary for visiting Stripe's OAuth screens and returning to configure other methods).

I'm going to close this since it'll be handled as a part of that work.
