### ISSUE TITLE
Woo Analytics Report Export Only Showing Page 1/1

### ISSUE THREAD

**Issue by Cer983** [woocommerce/woocommerce-admin#2906]
**Describe the bug**
When I create a report using any portion of Woo Analytics I have to expand the viewable option to (100), because the export only shows what is in the viewable option.  
**To Reproduce**
Woo Analytics - orders - scroll to orders list.  click "download", notice that only the number of orders in "rows per page" is downloaded into a report.

**Expected behavior**
I expect ALL orders to be shown in the report export.

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by Cer983** [comment]
Please note, if the report output exceeds 100 orders then I have to export each individual page into CSV.  I currently have a reports with 7300 orders which means i would have to export 73 times to get the entire output into csv

**Comment by psealock** [comment]
Hi @Cer983, thanks for the report. 

https://github.com/woocommerce/woocommerce-admin/pull/2899 adds support for datasets larger than one page by adding an emailed link to download the entire set.

https://github.com/woocommerce/woocommerce-admin/issues/2936 tracks adding an option to accomplish this in wc-admin itself.

Thanks again, I'll close this since its being developed.
