### ISSUE TITLE
Plug-in does not access panel and exhausts server

### ISSUE THREAD

**Issue by vitorbtorres** [woocommerce/woocommerce-admin#2908]
I'm having trouble with the native WooCommerce Admin plugin (WooCommerce Store Management Dashboard).

While accessing the plug-in panel, I am getting error "508 Resource limit is reached" and the site goes down.

Input processes, physical memory, CPU usage, and IOPS are exhausted on the server when access is available.

Already tried to do everything ... increased the memory of php, among other things.

He is making thousands of requestments.

Version: 0.18 (Plugin) 

![requests-panel](https://user-images.githubusercontent.com/19597872/64554430-c7b5dc80-d311-11e9-9f49-3d76fdeb639e.PNG)

![resourcelimit](https://user-images.githubusercontent.com/19597872/64554550-064b9700-d312-11e9-8999-26a6a81868d8.PNG)

![estatisticas-server](https://user-images.githubusercontent.com/19597872/64554576-12375900-d312-11e9-8d3c-a95fbbd238fd.PNG)

**Comment by corsonr** [comment]
Reported in 2340122-zd

**Comment by corsonr** [comment]
Hey @vitorbtorres, yes, it's been reported by other users too, that's why we're gathering everything here. On a side note, it seems you're using the same server so that *might* be server related at some point but it's a bit early to tell.

**Comment by timmyc** [comment]
@vitorbtorres just checking in to see if newer versions of the plugin have resolved this issue for you?

**Comment by GWS13** [comment]
We have had a similar issue as described by @vitorbtorres, but we were getting 500 Internal Server errors (instead of 508) and then the website would go down. This problem has occurred since we upgraded our website to WordPress 5.3 and WooCommerce to 3.8.1.

We had Facebook for WooCommerce installed. A chat with hosting revealed the Apache logs showing a bombardment of IP addresses from Facebook. So we deactivated the Facebook plugin. That didn't solve the problem though.

We put the site in maintenance mode, disabled all plugins except for WooCommerce and then enabled the other plugins one at a time while watching the server stats. We found the CPU/memory spikes occurred when navigating to the WooCommerce Admin plugin dashboard itself. Anywhere else in WooCommerce (Orders, Settings, Status, etc) was fine. Once we deactivated the WooCommerce Admin plugin the server stats stay normal. 

Since we don't really need the WooCommerce Admin plugin, we decided to remove it. 

I want to note we have other websites showing issues with a different plugin -- WooCommerce Services plugin. We don't really need that either and have disabled it on two sites.

To sum, if you don't need the WooCommerce Admin plugin I recommend removing it. Same for Facebook for WooCommerce if the logs show high traffic from Facebook. 

I hope this information is helpful.

**Comment by timmyc** [comment]
@GWS13 thanks for taking the time to report the issue you had. Would it be possible for you to share some of the apache logs from when the problem happened when visiting the Dashboard page? Also by chance did you import historical data when you installed the wc-admin plugin? Trying to get a sense of what might have led to the issue you were having - so any further details about the hosting environment would be helpful too - an easy way to do this would be to generate a System Report from WooCommerce > Status in your site's wp-admin.

If you would prefer to send this info via email just let me know.

I've tested the WooCommerce Admin dashboard on a number of hosting configurations, with larger test data sets ( 5k, 10k orders ) and haven't encountered this exact issue myself.

Thanks again for the report, and looking forward to getting some more details if possible.

**Comment by GWS13** [comment]
Hi, Timmy—

 

Thank you for your email response and sorry for the delay. We rolled back the website to the earlier version of WooCommerce and don’t have a status file copy from before. We did however post the WooCommerce > Status to report our problems here <https://kriesi.at/support/topic/enfold-theme-options-dropdown-theme-options-not-working-with-wordpress-5-3/#post-1163527>  on WooCommerce support. Would you be able to see details of it there?

 

Regards,

 

Kathi Watts

 <https://urldefense.proofpoint.com/v2/url?u=http-3A__www.gallopwebservices.com_&d=DwMFAg&c=Zoipt4Nmcnjorr_6TBHi1A&r=PK2TuBAxHyHNmDVOjCdcmALa6mvBghjdXNKd5p127is&m=QxGM-zRGUuImEaqs5U5ddKDevBDDPS2DqbyXabyAKgU&s=YOMed1hoTN8Rokhm_LTKUFMmzXzufhjXrZGXjSIqC6Y&e=> 

p: 540.338.8511 |  c: 571.271.3724 | Skype: gallop.web

 

 <https://urldefense.proofpoint.com/v2/url?u=http-3A__www.gallopwebservices.com_best-2Dof-2Dloudoun-2D2015-2Dwebsite-2Ddesign-2Ddevelopment_&d=DwMFAg&c=Zoipt4Nmcnjorr_6TBHi1A&r=PK2TuBAxHyHNmDVOjCdcmALa6mvBghjdXNKd5p127is&m=QxGM-zRGUuImEaqs5U5ddKDevBDDPS2DqbyXabyAKgU&s=kbj_YaJq7l3sCF9vYKg9uoirVf_o8vrlYHOPxpkyEM8&e=> 2015 Best of Loudoun – Web Design & Development

 <https://urldefense.proofpoint.com/v2/url?u=http-3A__www.gallopwebservices.com_2012-2Dtechnology-2Dbusiness-2Dof-2Dthe-2Dyear&d=DwMFAg&c=Zoipt4Nmcnjorr_6TBHi1A&r=PK2TuBAxHyHNmDVOjCdcmALa6mvBghjdXNKd5p127is&m=QxGM-zRGUuImEaqs5U5ddKDevBDDPS2DqbyXabyAKgU&s=bYGH_9BMxo3zXogyrMozL7McvWkGYnm-2C-rgJAEnnI&e=> 2012 Technology Business of the Year

 <https://urldefense.proofpoint.com/v2/url?u=http-3A__business.loudounchamber.org_list_member_gallop-2Dweb-2Dservices-2Dphilomont.htm&d=DwMFAg&c=Zoipt4Nmcnjorr_6TBHi1A&r=PK2TuBAxHyHNmDVOjCdcmALa6mvBghjdXNKd5p127is&m=QxGM-zRGUuImEaqs5U5ddKDevBDDPS2DqbyXabyAKgU&s=DfH4axfmKeTpPUgZgNhFqjvckcTVSSVxu_OcCU58eXE&e=> Member Loudoun Chamber of Commerce |   <https://urldefense.proofpoint.com/v2/url?u=http-3A__www.facebook.com_GallopWebServices&d=DwMFAg&c=Zoipt4Nmcnjorr_6TBHi1A&r=PK2TuBAxHyHNmDVOjCdcmALa6mvBghjdXNKd5p127is&m=QxGM-zRGUuImEaqs5U5ddKDevBDDPS2DqbyXabyAKgU&s=WadSn3WkOPffPu-CWqCmOg2BscPDbkB8uGXpI4axjr8&e=> FB  |   <https://urldefense.proofpoint.com/v2/url?u=http-3A__www.linkedin.com_in_kathiwatts_&d=DwMFAg&c=Zoipt4Nmcnjorr_6TBHi1A&r=PK2TuBAxHyHNmDVOjCdcmALa6mvBghjdXNKd5p127is&m=QxGM-zRGUuImEaqs5U5ddKDevBDDPS2DqbyXabyAKgU&s=Aw7HGs_SYJnh2w4Xwdbke6dSQuFc368lukrGLlf-Wzg&e=> LI 

 

Like Us on Facebook:  <https://urldefense.proofpoint.com/v2/url?u=http-3A__www.facebook.com_gallopwebservices&d=DwMFAg&c=Zoipt4Nmcnjorr_6TBHi1A&r=PK2TuBAxHyHNmDVOjCdcmALa6mvBghjdXNKd5p127is&m=QxGM-zRGUuImEaqs5U5ddKDevBDDPS2DqbyXabyAKgU&s=BQGAuwqjN6BcVBP13VDEn3AIUs6wlYRZxmqfVRzYWGg&e=> http://www.facebook.com/gallopwebservices

**Comment by timmyc** [comment]
Since we haven't had any further feedback here, I'm going to close this out. If you are still experiencing performance issues please do respond.
