### ISSUE TITLE
Onboarding: Fix update + await pattern

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#2959]
via https://github.com/woocommerce/woocommerce-admin/pull/2897#discussion_r321569096

> I think this await pattern we've been using will not work with wc-api. I'm not sure it returns the promise and isSettingsError will not yet have updated.

**Comment by joshuatf** [comment]
It seems like we can use `@wordpress/data-controls` as one solution to this problem (big thanks to @nerrad for pointing out this option!).  https://developer.wordpress.org/block-editor/packages/packages-data-controls/

```js
import { dispatch } from '@wordpress/data-controls';
 
// Action generator using dispatch
export function* myAction() {
    yield dispatch( 'core/edit-post', 'togglePublishSidebar' );
    // do some other things.
}
```

While this solution can work, it seems like the recommended pattern here is to create a file of controls (essentially action creators) and process any other actions after the dispatch from these controls.  This does not seem to allow us to use any kinds of callbacks after the action directly within our components (please correct me if I'm wrong @nerrad).

The main limitation to this seems to be the use fresh data with the generic store.  We'll need to register our store via `registerStore` instead of the current `registerGenericStore` in order to add the controls.

More discussion on that in p1573241460032300-slack-isotope-meetings

I think using Redux thunks would be a more ideal solution, allowing us to directly get the promise inside our component without the need to create a new set of action creators/controls.

```js
updateOptions( ... ).then( () => {
    // do something
} );
```

However, this solution requires us to `applyMiddleware` to the store, which we don't appear to have access to via `wp.data`.

In the meantime, I'm going to un-assign myself from this issue.  We have workarounds that circumvent the current issues with updating data, but long-term it would be great to have a more direct way to know when a specific promise in the store has been resolved.

**Comment by timmyc** [comment]
@joshuatf is this good to close now?
