### ISSUE TITLE
Welcome Screen - evaluate removing print shipping labels benefit

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3147]
AFAIK the print shipping labels benefit of WCS is exclusive to US merchants, so we should evaluate if it makes sense to display it to any store: https://cld.wthms.co/tCckfg

**Comment by justinshreve** [comment]
@pmcpinto 

According to the docs, to print labels you need the following to be true:

> Your store is in the United States (including Puerto Rico, Virgin Islands, and other U.S. territories)
> Your store currency is US Dollars

Should we just go ahead and remove this benefit now? I think we're probably already showing enough benefits as is.

**Comment by pmcpinto** [comment]
Hey @justinshreve sorry for the late reply, but I was in a meetup during the last days. I thought a bit more about this issue and printing shipping labels it's an important value proposition of WCServices, so I think we should continue displaying it to the stores that match the criteria you mentioned above.

Can you do a rough estimation of how long it can take to hide this benefit from the stores/users that don't match the criteria? We only get their address later in the onboarding, so maybe it's not possible to easily implement this. Thanks

**Comment by justinshreve** [comment]
> We only get their address later in the onboarding, so maybe it's not possible to easily implement this.

Correct -- since we get their address after this step, there is no way for us to know if we should show the benefit or not. If users re enter the profile wizard for any reason, and had an address filled out, we could detect that, but that seems like an edge case and those users likely are more technical and have already decided about Jetpack.

We could do some sort of geolocation or guess based on IP, but that seems overkill for this in my opinion and not worth the effort.

**Comment by pmcpinto** [comment]
> but that seems overkill for this in my opinion and not worth the effort.

I agree, so let's keep it as it is right now. I'm closing the issue.
