### ISSUE TITLE
Analytics Terms: Rename Total Sales, Recalculate Gross Sales

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#3175]
Make changes outlined in p90Yrv-1ef-p2 to modify Analytics terms. Previously attempted in https://github.com/woocommerce/woocommerce-admin/pull/3104, the changes will require a database update.

* Rename `gross_total` to `total_sales`
* Create a new column `gross_sales` defined as

```
gross_sales = total_sales + refunds + coupons - tax - shipping
```

* Reintroduce the `coupon_total` column, or figure out how to use the JOIN to calculate the value.

**Comment by jeffstieler** [comment]
In #3104, we're calculating `gross_sales` using:

```php
$gross_sales =
"( SUM({$table_name}.total_sales)" .
" + SUM(discount_amount)" .
" - SUM({$table_name}.tax_total)" .
" - SUM({$table_name}.shipping_total)" .
" + {$refunds}" .
" ) as gross_sales";
```
where `$refunds` is another calculated value using `ABS`, `SUM`, and `CASE` statements:

```php
$refunds = 
"( ABS( SUM( CASE WHEN {$table_name}.gross_total < 0 THEN {$table_name}.gross_total ELSE 0 END ) )" .
" - ABS( SUM( CASE WHEN {$table_name}.tax_total < 0 THEN {$table_name}.tax_total ELSE 0 END ) )" .
" - ABS( SUM( CASE WHEN {$table_name}.shipping_total < 0 THEN {$table_name}.shipping_total ELSE 0 END ) ) )";
```

After moving the refunds query into a column value, I don't think its worth the trouble to do the same to for gross sales.

At best the query becomes:

```php
$gross_sales =
"( SUM({$table_name}.gross_sales_col)" .
" + SUM(discount_amount)" .
" + SUM({$table_name}.refund_amount)" .
" ) as gross_sales";
```

Discount values come from a table join, so we can't include that value without losing the single source of truth.

Refund values are an aggregate, since each refund is stored as a separate row in the order stats table.

I'm not sure if there's a performance benefit to the "best" query above. Without creating a new `gross_sales` column, we can use:

```php
$gross_sales =
"( SUM({$table_name}.total_sales)" .
" + SUM({$table_name}.refund_amount)" .
" + SUM(discount_amount)" .
" - SUM({$table_name}.tax_total)" .
" - SUM({$table_name}.shipping_total)" .
" ) as gross_sales";
```
