### ISSUE TITLE
Extension: How to use hooks create from @wordpress/hooks between multiple react application

### ISSUE THREAD

**Issue by varun-webkul** [woocommerce/woocommerce-admin#3216]
Hi,

I would like to know about @wordpress/hooks use. As using this package we can add hooks for filters and actions. Theses are used in this woocommerce-admin plugin. These added hooks can be used within same react application. But, how to use these hooks from different react applications. The point is to make extension for this plugin to apply needed changed and additions.

Any kind of information regarding above will be appreciated.

Thanks & Regards

**Comment by Aljullu** [comment]
Hi @varun-webkul, regarding `@wordpress/hooks`, you can get more details about how to use it in the following link:
* https://developer.wordpress.org/block-editor/packages/packages-hooks/

In order to create an extension on top of WooCommerce Admin, I would recommend taking a look at our extension docs:
* https://github.com/woocommerce/woocommerce-admin/tree/master/docs/examples/extensions

We try to keep GitHub issues to track development tasks or bugs, for support you should better go to WordPress.org support forums, StackOverflow or similar websites where the community will be able to answer your specific questions, so I will proceed closing this issue for now. If you encounter a specific bug feel free to open a new issue and we will take a look to see what might be wrong. :+1:

**Comment by varun-webkul** [comment]
Hi @Aljullu , thanks for reply. And I know this is not the right place for this type of query. Actually this thing have very less discussion topics over web.

As per your recommendation I have looked at your extension docs. So, we can add more extensions using this way from woocommerce-admin. I have one last query here if you could address that'll be great.

The query is how to add extensions using the flow described from different plugin other than woocommerce-admin.

Thanks & Regards

**Comment by Aljullu** [comment]
Hi @varun-webkul, the examples I posted above should work as standalone plugins, they don't need to be inside `woocommerce-admin`. We added them in this same repo so they are easy to find.

You can find an example of standalone plugin that hooks into WooCommerce Admin here:

https://github.com/psealock/woocommerce-admin-extension-examples

It's a bit outdated and I'm not sure it works anymore, but you can look at how it interacts with WooCommerce Admin filters as an example:

https://github.com/psealock/woocommerce-admin-extension-examples/blob/master/extensions/add-report/js/index.js#L18

Hope that helps!

**Comment by varun-webkul** [comment]
@Aljullu Thank you so much. I'll check the same.

**Comment by varun-webkul** [comment]
Hi, @Aljullu Sorry for disturbing you again. Actually, I need some help here. First of all I have raised the query over stackoverflow as well. Meanwhile If you could address that'll be appreciated.

I have tried as per your guidance and it works for the WooCommerce Admin default hooks available. 

But when I created add-on for my plugin in which hooks are added in same way as woocommerce admin, its not working.

So is there any restriction like it works in admin end only or there is anything I'm missing while creating custom hooks that's why those aren't available globally.

Thanks & Regards
