### ISSUE TITLE
Translations: wp i18n make-json produces no files

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#3298]
**Describe the bug**

The command `npm run i18n` creates a `.pot` file for translations. First, the js and then the php. The js gets overwritten by the php.

First reported in https://wordpress.org/support/topic/wordpress-i18n-how-to-translate-js-strings/

**To Reproduce**

1. `npm run i18n`
2. Check the resulting `languages/woocommerce-admin.pot` file for strings derived from js files, and see none exist.
3. Run just the js this time, `npm run -s i18n:js` and see the js strings available in the same file.

**Expected behavior**

I'm not an expert here, but it seems the js and php should be concatenated.

**Comment by rrennick** [comment]
@psealock It merges them vs concatenate. If you `npm run i18n` in current master the second string in the file is

```
#: includes/connect-existing-pages.php:17 languages/woocommerce-admin.php:1863
#: src/Features/Analytics.php:142
msgid "Settings"
msgstr ""
```

The first 2 lines indicate locations where the string is found. `languages/woocommerce-admin.php:1863` is the js strings

```
	// Reference: client/header/activity-panel/panels/orders.js:198
	// Reference: client/layout/controller.js:64
	__( 'Settings', 'woocommerce-admin' ),
```

**Comment by psealock** [comment]
I see! Thank you. I will close this one then.

**Comment by yash-webkul** [comment]
Hello there,

Yes the mappings for JavaScript files are present in woocommerce-admin.php and in woocommerce-admin.pot, there are mappings for woocommerce-admin.php. But still, I am not able to translate any JavaScript strings.

Kindly mention the steps to translate them if you're able to translate.

--

Thanks

**Comment by rrennick** [comment]
@yash-webkul See https://github.com/woocommerce/woocommerce-admin/blob/master/CONTRIBUTING.md

**Comment by yash-webkul** [comment]
@rrennick yes, I have already checked that. In this doc, it is mentioned that to translate the WooCommerce Admin plugin, we need to download .pot file from [https://translate.wordpress.org/projects/wp-plugins/woocommerce-admin/](url) and yes this .pot file is correct but my question is that how to create this .pot file.

Kindly compare this .pot file from [https://translate.wordpress.org/projects/wp-plugins/woocommerce-admin/](url) and the one which is generated by the command `npm run i18n` and see the difference by yourself.

**Comment by rrennick** [comment]
> but my question is that how to create this .pot file.

.po/.pot files have the generator in the header of the file. You can find that by opening the file in a text editor. The WordPress.Org generator is

```
"X-Generator: GlotPress/2.4.0-alpha\n"
```

Different tools may generate the file with strings in a different order. Eg.

GlotPress first string is on line # 17
```
msgid "The WooCommerce Admin feature plugin requires <a href=\"%1$s\">WooCommerce</a> %2$s or greater to be installed and active."
```

the result of `npm run i18n` has this string on line # 4576.

**Comment by yash-webkul** [comment]
Hello @rrennick 

Kindly provide me the steps to create a `.pot` file.
I have done some modifications in the WooCommerce Admin plugin. In doing so, have added new strings in JavaScript files and want to generate a `.pot` file so that all those strings can be included with proper JavaScript mapping.

But if I run `npm run i18n` command, it doesn't even provide me the default WooCommerce Admin strings here with JavaScript mappings. It only provides me the mapping of PHP files so I can only translate the strings which are coming from PHP files in WooCommerce Admin plugin.

According to [https://github.com/woocommerce/woocommerce-admin/blob/master/CONTRIBUTING.md#localizing-woocommerce-admin](url), i have to download the `.po/.mo` files from [https://translate.wordpress.org/projects/wp-plugins/woocommerce-admin/](url).

Yes, if i download `.po` file from [https://translate.wordpress.org/projects/wp-plugins/woocommerce-admin/](url), it has all the proper JavaScript mappings so I am able to translate all the JavaScript strings.

But my question is that how this `.po` file is created? As per my knowledge, `.po` file can only by generated by `.pot` file. So please let me know how i can generate the proper `.pot` file which has all the proper mappings so that i can generate it too for my modified WooCommerce Admin plugin.

--

Thanks

**Comment by rrennick** [comment]
> But if I run npm run i18n command, it doesn't even provide me the default WooCommerce Admin strings here with JavaScript mappings.

Yes, it does. See my explanation https://github.com/woocommerce/woocommerce-admin/issues/3298#issuecomment-559853785 .

**Comment by yash-webkul** [comment]
I have seen your explanation and yes I know that there are JS mappings present in woocommerce-admin.php file and in woocommerce-admin.pot file, there are mappings of woocommerce-admin.php file but when you try to translate any JS string with this `.pot`, translation not done successfully. However, if you translate any PHP string like menus then it will get translated successfully.

Let me give an example for the translation. Kindly try translating word **Analytics**, it will get translated successfully and changes will get reflected in the site. Then try to translate the word **Gross Revenue**, it will get translated successfully because it is present in the `.pot` file but changes will not get reflected in the site.

I have tested this with the `.pot` file generated by `npm run i18n`.

@rrennick kindly test by yourself and let me know your views in this.

--

Thanks

**Comment by rrennick** [comment]
@yash-webkul Could you try out #3433 to see if that works for you?

**Comment by yash-webkul** [comment]
@rrennick thanks, yes it works for me now.

A little suggestion from side if you wish to apply, with command `npm run i18n:json`, you are replacing some mappings of development folder with the build one for `.po` file and then creating `.json` files. So instead of changing mappings in `.po` file, you can change the mappings directly in `.pot` file while generating it and just create `.json` file here.

Kindly let me know your views about this.

**Comment by rrennick** [comment]
@yash-webkul Thanks for the followup. I explained the reason for delaying the mapping change with

>The js pot file contains source references (which are useful for translators) while the json files are compiled based on the registered script handles of the dist/* files. Those references needed to be updated after translation but before making the json files.

Do translators use those source references?
