### ISSUE TITLE
Shipping task - user not being redirected to the Task List after completing the Shipping task

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3326]
I'm not being redirected to the Task List page after installing Jetpack and WooCommerce Services during the Shipping task (with a US address) and completing the task:

https://www.loom.com/share/3671061e217646c891a3b643a9d028a9

Also, after installed WCServices I think I was supposed to see a WCServices tab in the Shipping settings, correct?

**Comment by joshuatf** [comment]
>I'm not being redirected to the Task List page after installing Jetpack and WooCommerce Services during the Shipping task (with a US address) and completing the task:

Can confirm that this ends up in an endless loop.  Will update the redirect to go back to the task list instead of current page.

>Also, after installed WCServices I think I was supposed to see a WCServices tab in the Shipping settings, correct?

This sounds like it might be related to the same issue you experienced with https://github.com/woocommerce/woocommerce-admin/issues/3151 - this might not show if:

* You have Javascript errors (any showing in the console?)
* Jetpack is not connected
* TOS have not been accepted

If your Jetpack is connected and you have access to your database, could you post the values of `woocommerce_setup_jetpack_opted_in` and `wc_connect_options` from your `wp_options` table?  If you need help with this, feel free to ping me on Slack.

**Comment by pmcpinto** [comment]
Hey @joshuatf sorry for the late reply on this. Do you still want me to check this, considering your [comment](https://github.com/woocommerce/woocommerce-admin/pull/3245#issuecomment-561007043) on #3245?

> This sounds like it might be related to the same issue you experienced with #3151 - this might not show if:
> You have Javascript errors (any showing in the console?)
> Jetpack is not connected
> TOS have not been accepted
> If your Jetpack is connected and you have access to your database, could you post the values of woocommerce_setup_jetpack_opted_in and wc_connect_options from your wp_options table? If you need help with this, feel free to ping me on Slack.
