### ISSUE TITLE
Packages: Create new woocommerce\data package

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#3373]
A primary goal of changing our data stores to wp.data is to also build them in a way where they can be easily consumed by other developers. This task involves creating a new `@woocommerce\data` package using our lerna setup in this project.

We have [some instructions](https://github.com/woocommerce/woocommerce-admin/tree/master/packages#creating-a-new-package) on how to do this. @nerrad suggests we set this new package to not publish by setting `private: true` in the associated package.json ( [some convo about this approach in the lerna repo](https://github.com/lerna/lerna/issues/536) )

**Comment by nerrad** [comment]
To clarify around some of the suggestions I had:

- prioritize store migrations that you think might be utilized by extensions into `@wocommerce/data`
- the bundle could be enqueued in the WordPress environment on a `wc-store-data` handle so that extensions can ensure any stores they want to utilize are registered.
- You should export store names as constants (expose them publicly) so that consumers can do things like:

```
import { SETTINGS_STORE_KEY } from `@woocommerce/data`;
```

And if the build tool is using `wp-scripts` dependencies will automatically be picked up for the registered `@woocommerce/data` external and output to the `*asset.php` file (making it super easy to ensure the right dependencies are enqueued.
- I suggested don't publish `@woocommerce/data` initially until you're relatively certain api is stable for the stores.  But publishing it mostly just means that consumers can use these stores outside of a WordPress environment.  Which would still involve some initialization step for `wp.apiFetch` at some point (but non-relevant for your usage in the Woo Admin).

**Comment by psealock** [comment]
I pushed changes to the Settings example/try branch to set up `packages/data` https://github.com/woocommerce/woocommerce-admin/pull/3313.

There are a few rough edges in the PR, something is off with `isDirty` for instance, as well as several things already noted. But we can create issues around them and iterate upon whats the work already started.

**Comment by psealock** [comment]
This is done
