### ISSUE TITLE
Onboarding: Country/State dropdown does not drop down after initial selection

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-admin#3519]
**Describe the bug**
After selecting the Country/State in the new OBW, the drop down does not drop down anymore, only if you erase the text. That is counterintuitive to how most of dropdowns drop down.

Illustration:
https://d.pr/i/dYnUi4

**To Reproduce**

1. Go through the new OBW, select a country/state from the list
2. Try to click on the arrow down to select a different country/state
3. You shall not drop down.

**Expected behavior**
Usual dropdown behaviour.

**Desktop (please complete the following information):**

* OS: macOS
* Browser Chrome 78

**Additional context**

ref: pb22l9-5T-p2, #comment-316

**Comment by pmcpinto** [comment]
I agree with Peter that this is counterintuitive. I'm not sure if this is a bug or the component's default behavior. @joshuatf can you confirm?

**Comment by joshuatf** [comment]
I believe this is the expected behavior of the dropdown since there is already a query (selected text) inside the dropdown limiting the results.  See https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html for an accessible example.

The dropdown has an option to exclude already selected items, which the country/state dropdown utilizes.  So in the screen capture above, clicking the dropdown is opening the list and filtering by the existing query `United States (US) -- California`, excluding the currently selected result (`United States (US) -- California`).

I'm not sure we should show the full list of options if a query or selected item already exists that should filter results.  But maybe not excluding the selected item from the list of options would make this feel more intuitive since it would show a list of that single item. /cc @peterfabian @pmcpinto

**Comment by peterfabian** [comment]
I think behaviour similar to Example 3 would be preferable. It makes it apparent that it's still a functioning dropdown and pre-selects (part of) the text to make further interaction more understandable (i.e. I understand that when I start typing, it will change the content of the box, while our dropdown just looks like a choice has been made and it's stuck). But it's quite a low prio cosmetic issue.

![Screenshot 2020-01-07 at 10 48 43](https://user-images.githubusercontent.com/2207451/71885764-4f361f80-313b-11ea-98b0-d56482636122.png)

**Comment by pmcpinto** [comment]
@joshuatf thanks for your feedback. I think that displaying the selected item in the dropdown would make it more intuitive, as it shows in the 3rd example

**Comment by peterfabian** [comment]
LOL, 20 seconds apart, that is a record :D

**Comment by pmcpinto** [comment]
Lol :) 

I also agree that's a low priority issue.

**Comment by joshuatf** [comment]
>LOL, 20 seconds apart, that is a record :D

Lol nice.

>I think behaviour similar to Example 3 would be preferable. 

Sounds good to me.  I think we can just not exclude the selected item to get this working.

>pre-selects (part of) the text to make further interaction more understandable

I only see this on initial typing.  Does your browser pre-select that piece of the text after re-selecting the select box? /cc @peterfabian
