### ISSUE TITLE
Focus on the benefits for the merchant 

### ISSUE THREAD

**Issue by warrendholmes** [woocommerce/woocommerce-admin#3544]
In the new onboarding flow it would make more sense that we focus on the benefits a merchant will get when they install Jetpack instead of focusing on Security first https://cloudup.com/cGzh9cC7yMH 

My suggested order : 

- Mobile app
- Simple payment set up
- Shipping labels
- Tax
- Speed 
- Security

Also, for the Speed benefit we should focus the message on how our CDN makes the shopping experience better and helps convert visitors. @Timstreep Would be great to get a marketer's input here.

**Comment by joshuatf** [comment]
@warrendholmes Since the new design removes a bunch of these items, do you have any input on the new design? /cc @Timstreep as well in case you have any feedback.

<img width="646" alt="Screen Shot 2020-02-21 at 4 23 22 PM" src="https://user-images.githubusercontent.com/10561050/76079272-978b8580-5fa4-11ea-95c1-f5c1dfb141b3.png">

<img width="1064" alt="Screen Shot 2020-02-24 at 1 50 20 PM" src="https://user-images.githubusercontent.com/10561050/76079265-93f7fe80-5fa4-11ea-93a2-16041947a9b2.png">

**Comment by timmyc** [comment]
I think the benefits page and this issue have diverged a bit so I'm going to close this out.
