### ISSUE TITLE
[WC 3.9 rc4] Onboarding: `Plugins` section UI being displayed during onboarding on the Calypsoify site

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3600]
**Describe the bug**

`Plugins` section UI being displayed during onboarding on the Calypsoify site. 

**To Reproduce**

1. Use the existing Calypsoify site for testing. I used Pressable site with added `calypsoify=1` parameter;
2. Make sure new onboarding is activated (use this [snippet](https://gist.github.com/justinshreve/6e945dcb4714134156aba1b3c7f086cf) if needed);  
2. Navigate to `https://yoursite.com/wp-admin/edit.php?post_type=shop_order` and change the URL to `https://yoursite.com/wp-admin/admin.php?page=wc-setup`;
3. Select to proceed with the new onboarding by clicking `Yes`;
4. Note that the `Plugins` section UI being displayed during onboarding:

![plugins](https://user-images.githubusercontent.com/19143190/72812328-33fa0280-3c59-11ea-853d-3fc6559ffa7b.jpg)

**Expected behavior**

I expected not to see the `Plugins` section UI being displayed during onboarding. 

**Screenshots**

See the screenshots above. 

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 3.9 rc4
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com, WooCommerce Beta Tester, WooCommerce Stripe Gateway

**Desktop (please complete the following information):**

* OS: macOS Catalina v 10.15.1
* Browser: Chrome
* Version:  79.0.3945.117 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by timmyc** [comment]
Thanks for the report Julia - I'm going to mark this one as blocked for now since we are going to discuss calypsoify usage soon. Based off the outcome there I will possibly move this to the `wc-calypso-bridge` repo for a fix.

**Comment by joshuatf** [comment]
I actually opened an issue on `wc-calypso-bridge` recently for a fix on this, but this issue does not stem from the bridge (and it actually resolves it if enabled, but its calypsoify feature cannot be simultaneously enabled with the new onboarding experience by design).

This issue is actually directly from Jetpack's calypsoify module.

While ideally we could deal with this upstream, I may see if there's a workaround in wc-admin since it would be beneficial to prevent any plugins from accidentally leaking into this view.
