### ISSUE TITLE
[WC 3.9 rc4] Onboarding: Not able to select the state of the shop location during onboarding on the Calypsoify site

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#3602]
**Describe the bug**

Not able to select the state of the shop location during onboarding on the existing Calypsoify site. 

**To Reproduce**

1. Use the existing Calypsoify site for testing. I used Pressable site with added `calypsoify=1` parameter;
2. Make sure new onboarding is activated (use this [snippet](https://gist.github.com/justinshreve/6e945dcb4714134156aba1b3c7f086cf) if needed);  
3. Navigate to `https://yoursite.com/wp-admin/edit.php?post_type=shop_order` and change the URL to `https://yoursite.com/wp-admin/admin.php?page=wc-setup`;
4. Select to proceed with the new onboarding by clicking `Yes`;
5. When you get to the store address section, in my case I had Florida state preselected. I wanted to change it and first was not able to click on the arrow to open the drawdown. You can only select the state and delete it. I wanted to select Florida again but it was not available. See screencast I made:

http://g.recordit.co/wg15vp5yn9.gif

**Expected behavior**

I expected to be able to click on the arrow to open the dropdown and to select the state of Florida again. 

**Screenshots**

See the screenshots above. 

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 3.9 rc4
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com, WooCommerce Beta Tester, WooCommerce Stripe Gateway

**Desktop (please complete the following information):**

* OS: macOS Catalina v 10.15.1
* Browser: Chrome
* Version:  79.0.3945.117 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by timmyc** [comment]
Thanks for the report Julia - I'm going to mark this one as blocked for now since we are going to discuss calypsoify usage soon. Based off the outcome there I will possibly move this to the `wc-calypso-bridge` repo for a fix.

**Comment by joshuatf** [comment]
This issue should be resolved in the current master branch.

We had 2 PRs that affect this:
* One of them change the behavior to not exclude already selected options for the list (so Florida would still be shown in the list even though this is already the state you've selected) https://github.com/woocommerce/woocommerce-admin/pull/3540
* The second added an option to show all items on click instead of filtering by the existing query. https://github.com/woocommerce/woocommerce-admin/pull/3551

Going to close this one for now but feel free to reopen if this doesn’t meet expectations on the latest WC admin build.
