### ISSUE TITLE
Will an admin nag show if WooCommerce Admin plugin is active in order to WooCommerce to upgrade

### ISSUE THREAD

**Issue by lukecav** [woocommerce/woocommerce-admin#3652]
Will the WooCommerce Admin featured plugin need to be deactivated or deleted in order for the WooCommerce Admin features in WooCommerce 4.0 to work correctly?

Will an admin nag show to remind users to deactivate and delete the plugin for WooCommerce Admin since it no longer needed?

**Comment by rrennick** [comment]
> Will the WooCommerce Admin featured plugin need to be deactivated

@lukecav We will implement arbitration similar to Action Scheduler, Woo Product Blocks, and Woo REST API to determine which version should be active.

> Will an admin nag show to remind users to deactivate

There will be something for that. Because there is a wide range of earlier versions still active, how this is handled is likely to vary by version range. As with the above mentioned plugins, sites will be able to install/use the latest version of the standalone plugin and the packaged version in WC will be dormant.

I'll close this issue but if you have other questions, feel free to ask.

**Comment by lukecav** [comment]
@rrennick 

Thank you.
