### ISSUE TITLE
Onboarding - payments step: improve flow and include offline payments

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3710]
The Payments step is performing poorly and this is probably due to some reasons:
- We don't guide users to set up offline payments, while we still have a significant % of stores that activate and use COD and BACS.
- Showing different payment methods together with the subsequent steps can increase cognitive load and cause some confusion.
- We redirect the user to external websites to set up their accounts on Stripe Paypal.

We can't do much about the last point, but we're confident that if we add offline payments set up and tweak the design it will be possible to improve the experience and help users set up their payment methods.

Changes to the current flow:
- Regarding online payments, we're changing the first screen and if the user clicks to set up one of the payments the flow should be identical to the one we have now.
- For COD, the user needs to turn on the option and by doing this it turns the COD Payments setting on core.
- For BACS, if the user clicks to set up we should turn on the respective setting on core, but in this case, we also allow him to fill the bank account details without going to Settings. If he fills the bank details, they should also be recorded in the respective payment settings.
- We're also going to add an option to skip this task. When the user clicks to skip the task we display a modal to get info about the main reason behind skipping the task.
- We also need to make some changes in terms of tracking:

     - Add a new event for when the user clicks "Skip this step": `wcadmin_tasklist_payment_skip_task` (event prop: skip_option: the 3 options that we display in the modal)
     - Add a new event for when the user turns off the radio button:  `wcadmin_tasklist_payment_turnoff_payment` (event prop: payment_method: payment method name)
     - Add a new event for when the user clicks "Done" to complete the task: `wcadmin_tasklist_payment_done` (event prop: payment_methods_installed: list of the payments methods installed)
     - Add a new event for when the user clicks "Set up" in one of the payments or turns on COD: `wcadmin_tasklist_payment_setup` (event props: payment_method_selected: payment method selected, payment_methods_displayed: payment methods displayed). This event ends up replacing `wcadmin_tasklist_payment_choose_method`

[Mockup
](https://www.figma.com/file/nzAjPR4nqdJTDxH32PT4Qg/On-boarding?node-id=29%3A20)

**Comment by pmcpinto** [comment]
Hey @joshuatf among all the improvements that we planned for the cycle this is probably the most complex one and one of the most important. And this is also going to impact all the other changes planned for the payments step (add PayFast, fine-tune for CBD), I created an epic with all the issues associated with Payments.

So it would be important to have an estimation of how long this issue can take, so we can tweak it or backlog other onboarding issues. Let me know if you have questions or suggestions

**Comment by joshuatf** [comment]
@pmcpinto Gotcha.  In addition to the estimation, do you want to prioritize this issue over the others since it sounds like a high priority item?

**Comment by pmcpinto** [comment]
Hey @joshuatf, yes that would be great. I think the issues associated with the payments step and moving the Jetpack/WCS step to a different place are the most important ones, as they seem to be the most complex among all the improvements that we would like to make during this cycle.

But pls take a look at all the onboarding issues identified for this cycle, try to give just a rough estimation on each one and let me know what you think about it. I think that probably they're too much just for one person, so maybe we need to backlog some of them or have another member of the squad working on some of them too. I think Fernando already started looking at some of the quick fixes. Thanks!

**Comment by grigorijurasov** [comment]
I did some tests with WooCommerce 4.0.0 beta-1 today.

Let me know if this warrants a separate bug report, but here's somewhat an edge case scenario:

* The last step of the onboarding in WooCommerce >> Dashboard is Stripe:

<img width="1488" alt="Screenshot 2020-02-20 at 17 50 16" src="https://user-images.githubusercontent.com/13084901/74959049-355e4c80-540a-11ea-9a2e-7845292e6505.png">

* Since my Stripe account with a8c email address is connected to Bubblestorm Stripe account, I bailed on the store setup process and entered the test API keys manually.

* Stripe for WooCommerce is already enabled but the WooCommerce >> Dashboard still implies it isn't:

<img width="1494" alt="Screenshot 2020-02-20 at 17 53 17" src="https://user-images.githubusercontent.com/13084901/74959360-b0276780-540a-11ea-8050-9550dd9b19e7.png">

* After de-activating Stripe for WooCommerce plugin I was offered a choice between entering live keys manually or skipping. I skipped.

**Comment by joshuatf** [comment]
Thanks for noting the issue @grigorijurasov.  Since https://github.com/woocommerce/woocommerce-admin/pull/3782 and https://github.com/woocommerce/woocommerce-admin/pull/3801 refactor how the payments tasks are set up and include configuration checks, I don't believe that will be an issue anymore once they've been merged.
