### ISSUE TITLE
[4.0 beta] Review the image assets bundled with WC Admin

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-admin#3716]
Currently, WC Admin includes 5MBs of images in the images/onboarding directory, which contributes to the total package size of WC core considerably (total ±12MBs). We need to optimize and remove the unneeded ones.

**Comment by timmyc** [comment]
Thanks @peterfabian this was on my list of to-dos this morning. Here are some thoughts I have on solutions. Since these images are only used in the setup checklist to create starter home page templates perhaps we can:

- Remove them entirely from the repo, and either host them on WPCOM ( not sure of any implications on the .org plugin guidelines here ) or download them to the site only when they are needed.
- Lower effort, run them all through image optimization. But still feel odd having us ship images to all woo core users that aren't needed.

**Comment by psealock** [comment]
With #3731 merged, this one can be closed.

**Comment by peterfabian** [comment]
Thanks folks!
