### ISSUE TITLE
OBW, step business details styling broken on iPad

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-admin#3718]
**Describe the bug**
Styling seems broken on iPad during the OBW, please see the screenshot
![image_from_ios](https://user-images.githubusercontent.com/2207451/74466999-95984000-4e98-11ea-894c-3a5379cfe824.png)

WC 3.9.2
WCA 0.25.1
WooCommerce Services 1.22.3

**Additional context**
p1581618045076800-slack-proton

**Comment by joshuatf** [comment]
Thanks for noting this issue, @peterfabian!

I tried to reproduce this on an iPad 4 and iPad Pro via BrowserStack as well as Safari's iPad user agent without any luck.

Could you let me know which version this was found on?

Were the new Jetpack `is_staging_site()` errors visible on this page?

**Comment by peterfabian** [comment]
cc @beaulebens as he was the one who experienced the problem.

**Comment by beaulebens** [comment]
I've just tried again, and was able to get it. I'm using Chrome (latest) on an older iPad (2017 model I think), 9.7".

- created a JN site, checked the box to include Woo, left the boxes for debugging messages/logging to be included
- went straight for the "set up Woo" admin notice (not the WCAdmin one)
- got the new flow, worked through everything and said i was going to have physical products only
- said 101-1000 products (random selection) and that I wasn't selling elsewhere
- immediately got the broken layout in the screenshot after selecting "No" for selling elsewhere

The `WP_DEBUG` messages about `is_staging_site`  _were_ displaying at the top of the page, so I was scrolled down to interact with the wizard/see this UI breakage.

**Comment by beaulebens** [comment]
And I don't know what was different this time, but I actually got stuck at this step completely. When I tried to tap "Continue", I got a snackbar error saying "There was a problem updating your business details." Pretty hard dead end, although I was able to figure out that I could tap the "Theme" option in the progress bar across the top.

**Comment by joshuatf** [comment]
@beaulebens I was able to reproduce this issue in Safari when the Jetpack errors are present.
<img width="1649" alt="Screen Shot 2020-02-18 at 10 48 49 PM" src="https://user-images.githubusercontent.com/10561050/74781092-29a34680-52a1-11ea-83f5-35f30490bf45.png">

After deactivating Jetpack, the issue is resolved:
<img width="1655" alt="Screen Shot 2020-02-18 at 10 49 27 PM" src="https://user-images.githubusercontent.com/10561050/74781085-27d98300-52a1-11ea-9d0c-202a3769b92e.png">

I'm thinking the error `There was a problem updating your business details.` is most likely also a symptom of the Jetpack errors, but let me know if you are able to reproduce either of these issues when Jetpack is disabled (or with a version where the bugs are resolved).

**Comment by peterfabian** [comment]
The error in the screenshot is caused by an updated approach in JP autoloader and should be fixed by https://github.com/woocommerce/woocommerce/pull/25697.

**Comment by jeffstieler** [comment]
Testing `woocommerce-admin` on the `version/1.0` branch @ fa3d21534ae6fc64ca6e42b5002b735c88f333f7 with `woocommerce` on the `4.0.0-rc.1` tag @ 7c7a74bfa3c27d3c7c7cd2b4e4c22a87639cab8d shows that this has been resolved.

OK to close @peterfabian ?

**Comment by peterfabian** [comment]
Sure, thanks for checking.
