### ISSUE TITLE
Traffic reports - wc-admin dashboard

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#3882]
In the upcoming cycle, we plan to start implementing some changes in the wc-admin dashboard, including the inclusion of 1/2 traffic reports based on pageviews/visitors. More info here: pbIJXs-1w-p2 (design tbd)

It seems that this can only be achieved for stores using Jetpack, so at the end of the cooldown it would be great to understand the following:
- If we can introduce these reports for new and existing stores
- If it's possible to show historical traffic data for existing WooPack stores
- A rough estimation of how long it can take this implementation
- If we can reduce technical complexity to improve development time
- A list with the largest modules of work

**Comment by psealock** [comment]
>If we can introduce these reports for new and existing stores

WooPack stores can take advantage of these REST API endpoints to populate traffic report or dashboard widget

```
https://public-api.wordpress.com/rest/v1.1/sites/<site-id>/stats
https://public-api.wordpress.com/rest/v1.1/sites/<site-id>/stats/visits
```
You can view how wordpress.com displays this data at `https://wordpress.com/stats/day/<my_site>`.

>If it's possible to show historical traffic data for existing WooPack stores

Yes, so long as the Jetpack connection was valid, traffic data was being collected.

>A rough estimation of how long it can take this implementation

Would this be a full report page or widgets? Its hard to know without seeing the concept as a whole. To replicate wp.com's basic traffic stats like page views and most viewed pages using existing wp public api to create a widget could take one dev a month.

>If we can reduce technical complexity to improve development time

If we can transform the data so that we re-use our chart used for reports (very doable), then the task is greatly simplified.

**Comment by pmcpinto** [comment]
@psealock thanks for checking this.

> Would this be a full report page or widgets? Its hard to know without seeing the concept as a whole. To replicate wp.com's basic traffic stats like page views and most viewed pages using existing wp public api to create a widget could take one dev a month.

> If we can transform the data so that we re-use our chart used for reports (very doable), then the task is greatly simplified.

The idea for v1 is to provide a quick overview of today's visitors and page views, allowing the user to also check the "week to date" and "month to date" variation. If the user wants to check more details about visitors/views we'll redirect him to:

On wpcom: The “Stats” screen
On self-hosted sites: The “Site stats” screen in Jetpack

See the design proposal here: pbIJXs-4Z-p2
