### ISSUE TITLE
The source link dashboard in the bar of product page hides my tool (add image)

### ISSUE THREAD

**Issue by r365online** [woocommerce/woocommerce-admin#3954]
**Describe the bug**
The source link dashboard in the bar of product page hides my tool (add image)

**To Reproduce**
1. Go to 'edit product page'
2. Click on 'nothing'
3. Scroll down to 'add image'
4. I can't, I have to scroll up to add image because the tab hides my add image tool.

**Screenshots**
<img width="1440" alt="Screen Shot 2020-03-20 at 11 00 01" src="https://user-images.githubusercontent.com/62413698/77134605-5615d280-6a9a-11ea-8f38-466dcc869e0a.png">

**Expected behavior**
Hide or fix the problem of hiding the tool.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by timmyc** [comment]
@jameskoster Thoughts on this?

**Comment by jameskoster** [comment]
WordPress applies `position: fixed` to the toolbars when you scroll past them. If it's possible, we just need to offset the values applied there by the height of the top bar.

**Comment by joshuatf** [comment]
Is the toolbar the only area affected that we're aware of?

I think we can override the `top` position of the toolbar, but we'll have to recalculate the wpadminbar height for the calculation depending on screen size.  This will result in some code duplication between this repo and core but may be unavoidable.

I looked at adding in a transparent border or pseudo elements to the admin bar to fake a larger height since this calculation is done in core with jQuery's `outerHeight()` method.  While this solves the toolbar issue, it spawns new issues with overlapping other menus/bars.

**Comment by moon0326** [comment]
Closing this as it's been stale for 6 months+
