### ISSUE TITLE
Track WooCommerce Payment task clicks

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-admin#4016]
From clicks on the various links in the WooCommerce Payments flow (card) to establish some funnels

Ref: https://github.com/woocommerce/woocommerce-admin/pull/3978#pullrequestreview-382403799

Props @timmyc

**Comment by timmyc** [comment]
cc @thenbrent and @pmcpinto for any special tracks considerations on this feature. Specifically thinking it might be interesting to drop a track when the card/option is even displayed to get a true sense of the funnel start size.

**Comment by thenbrent** [comment]
> it might be interesting to drop a track when the card/option is even displayed to get a true sense of the funnel start size.

Good idea.

**Comment by thenbrent** [comment]
@pmcpinto do you have any special considerations given to other Task List items that we could learn from? (Like tracking the card's display.)

I'm primarily interested in the number of clicks on the Set up button, naturally. But also keen to track the other links in the card.

**Comment by pmcpinto** [comment]
> Specifically thinking it might be interesting to drop a track when the card/option is even displayed to get a true sense of the funnel start size.

That's a great suggestion. By the way, in 4.1 we're going to have `wcadmin_tasklist_payment_setup` with an event prop that shows the gateways displayed in the task and the ones that were clicked, @timmyc can you confirm? So that would give the number of views and the number of clicks. We'll also have three additional events: 

- When the user clicks "Skip this step": `wcadmin_tasklist_payment_skip_task` (event prop: skip_option: the 3 options that we display in the modal)
- When the user turns off the radio button: `wcadmin_tasklist_payment_turnoff_payment` (event prop: payment_method: payment method name)
- When the user clicks "Done" to complete the task: `wcadmin_tasklist_payment_done` (event prop: payment_methods_installed: list of the payments methods installed)

cc @thenbrent

**Comment by thenbrent** [comment]
Those are great. We don't need any additional events tracked beyond those.

**Comment by pmcpinto** [comment]
Just a heads up that those are new events, so I'm going to test them, but it would be good to have 1 or 2 people also checking if they work fine :)

**Comment by pmcpinto** [comment]
I'm going to close this one as it seems that all the events are working fine.
