### ISSUE TITLE
Clicking continue on set store location task list step triggers console error

### ISSUE THREAD

**Issue by jconroy** [woocommerce/woocommerce-admin#4031]
**Describe the bug**

Working through the onboarding task list when I click the "Continue" button on the "Set Store Location Step" I get the following console errors on master.

Production Build:

> TypeError: i is not a function

Development Build:

> TypeError: updateSettings is not a function

**Expected behavior**
I continue to the next step.

**Screenshots**

<img width="1528" alt="Screen Shot 2020-03-31 at 8 18 02 pm" src="https://user-images.githubusercontent.com/355014/78012652-d5ee4780-738c-11ea-8a3a-ade15a6590fc.png">

**Desktop (please complete the following information):**

* OS: macOS
* Browser firefox dev edition
* Version 5.0b10
* WooCommerce 4.0.1

I had a look to see if this was a dupe but couldn't see anything - apologies if it is known.

**Comment by becdetat** [comment]
Hi @jconroy 

I'm having trouble reproducing this - it works fine in Firefox for me. Can you navigate to index.js:22244 and post a screenshot of the script? I might be able to find the right place to look from there.

Thanks

**Comment by jconroy** [comment]
Hi @becdetat sorry for the delay. I updated to latest master to double check - still seeing it (line number is slightly different below but I get the same error).

Here is a screenshot

![Screen Shot 2020-04-07 at 10 47 50 am](https://user-images.githubusercontent.com/355014/78619789-7ed10100-78bd-11ea-95a8-85fa7b412fa0.png)

**Comment by mattsherman** [comment]
I can reproduce this... investigating a fix!

**Comment by timmyc** [comment]
Just noting here that I wasn't able to reproduce this bug using Beta 2. My approach was to visit the Tax step in the Setup Checklist first, and all worked fine for me.

**Comment by jconroy** [comment]
> My approach was to visit the Tax step in the Setup Checklist first, and all worked fine for me.

Interesting, I was just working through the list from top from bottom.

At the moment I've got the tax step ticked off and am still seeing it.

**Comment by timmyc** [comment]
I know @mattsherman was able to reproduce it too. Just finding it odd that it isn't consistent. Seems like the folks helping with some QA on 4.1 haven't hit it either...

**Comment by mattsherman** [comment]
I hit it in "Set up shipping" and "Set up tax" if the conditions to get the store location task to appear are met (no store location set for "Set up tax", also need a physical product in the store to get the store location task to show up in "Set up shipping). 

It's just plain broken when you enter an address and click continue -- I don't see, looking at the code, how it would ever succeed if you tried to set the store address from the task list, since it is calling a function prop that doesn't exist!

Also, once I fixed the initial problem of calling the non-existent function, it exposed an issue where the subsequent step was mistakenly skipped over. My WIP PR (#4091) has this *mostly* working for the "Set up tax" flow. I need to tidy up some loose ends in that and do a similar fix in "Set up shipping".
