### ISSUE TITLE
Advanced custom filters

### ISSUE THREAD

**Issue by Phuzer** [woocommerce/woocommerce-admin#4043]
Hello, 

I'm currently using wordpress 5.3.2 and woocommerce 4.0.1 that already have Woocommerce Admin included. My idea is to add custom advanced filters with custom queries only using php hooks. Is there a list of hooks I can use in order to do this? I saw this tutorial https://woocommerce.wordpress.com/2020/02/20/extending-wc-admin-reports/ , and I tried to use some hooks used in this tutorial (for example woocommerce_admin_orders_report_filters, to add a select box) but wasn't really successful with it, as the function never gets called. Is this possible to achieve using just php?

**Comment by psealock** [comment]
Hi @Phuzer, 

Thanks for your question. 

>Is there a list of hooks I can use in order to do this?

There isn't at the moment, but getting documentation together is a priority, even if its just a list of hooks.

>Is this possible to achieve using just php?

Much of the logic in the Reports and wc-admin resides in JavaScript, so these will need to be called from the JS portion of your extension. The `npm run create-wc-extension` command should help you set all that up painlessly. Are there specifics problems you're running into with the set up?

**Comment by Phuzer** [comment]
Hi, thanks for the response.

I ended up following the tutorial, and was able to successfully set a dropdown with my options and manipulate the query. But sometimes, they give weird results and i'm not sure why. I will try my best to explain. I want my dropdown to basically filter orders made by users that represent the selected company. I have a user custom field called "company" (i'm using ACF) and I am able to populate the dropdown with all the companies that exist. The problem is, sometimes when I change the dropdown value, the functions 'add_join_subquery', 'add_where_subquery' and 'add_select_subquery' don't get called. I know that because i'm writing to debug.log when the function runs. Even if the function don't execute, sometimes the order results change anyway. Is there some type of cache that stores previous results?

**Comment by psealock** [comment]
>Is there some type of cache that stores previous results?

Yes, there is! You need to let the caching system know about your query argument so that when it changes, fresh data will be gathered instead of data in cache. I'm not sure what report you are developing for, but here is some example code for several reports. By adding `currency` to a report's query arguments, caches will respect changes made to the `currency` query argument.

https://github.com/woocommerce/woocommerce-admin/blob/b008f6b22d699581596e470816d9add1463ac389/docs/examples/extensions/sql-modification/woocommerce-admin-sql-modification.php#L97-L130

Is it just the Orders Report you are modifying? Are you using filters `woocommerce_analytics_orders_query_args` and `woocommerce_analytics_orders_stats_query_args`?

**Comment by Phuzer** [comment]
The problem is fixed. Documentation is really needed here :|
