### ISSUE TITLE
Task List - Shipping task: missing store location (WC-Admin 1.1 test)

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4054]
**Describe the bug**
If the user fills the store details at the beginning of the onboarding, we shouldn't ask him to fill the store location again in the Shipping step. See this video: https://www.loom.com/share/5978d8187113464bb9740bdc9a7b17fb

PS: it worked fine when I went through the store profiler the second time.

**To Reproduce**
1. Add store details in the first step of the onboarding
2. Visit Shipping task
4. See store location empty

**Comment by joshuatf** [comment]
@pmcpinto I wasn't able to recreate the issue, but I suspect this could be another case related to caching.

Was this issue found locally, JN or somewhere else?

Normally, the store location step will be skipped entirely if an address if filled in.  But even if it was not skipped, the fields should be prefilled with existing store data.  This makes me think that the option retrieval may be cached initially with an empty value and subsequently purged which is why you were able to see it when revisiting.

![Screen Shot 2020-04-06 at 12.31.28 PM.png](https://images.zenhubusercontent.com/5d7fd4b446611c000130d6f9/2e0ad37e-39c7-45bd-8c07-36f5e592ddae)

Possibly related: https://github.com/woocommerce/woocommerce-admin/issues/3467

**Comment by pmcpinto** [comment]
Hey @joshuatf, thanks for checking this. It happened on a Pressable site. Should we leave the issue open or close it? As this seems to be related to caching

**Comment by joshuatf** [comment]
Ah, that makes sense.  I'm going to close this as it sounds likely it's related to the caching issue we've only encountered on Pressable sites in https://github.com/woocommerce/woocommerce-admin/issues/3467.

If you see it occur on any non-Pressable sites, feel free to open this back up and ping me and I'll take another look.
