### ISSUE TITLE
Setup Checklist: Remove "Setup" Menu Feature

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#4067]
Per feedback from @pmcpinto - we are going to disable the "Setup" menu feature that was added in #3796 before the final release of 1.1. Some of the concerns around the feature are users might be following a tutorial to setup their Woo site, and by hiding the menu items, this could result in some confusion by end users.

We want to keep the other logic in that original PR that includes the new links to Skip / Do It Later, so thinking we could just remove the changes in the above PR to ` src/Features/OnboardingTasks.php` to "turn off" the menu changes. but /cc @becdetat for confirmation.

**Comment by pmcpinto** [comment]
I think that we'll also need to remove the `Do It Later` link as the goal of this link was to unlock the menu instead of just showing the Setup link. An alternative could be keeping the `Do It Later` link and display the existing wcadmin dashboard below the task list (similar to what happens when the user completes the list). @jameskoster what do you think?

We should keep the `Skip` link independently of what we decide to do with the `Do It Later` link

**Comment by jameskoster** [comment]
I think we should just get rid of the `Do it later` link 👍
