### ISSUE TITLE
[GlobalStep - 4.1 beta 1]Tax option in “Add Your first product” gets updated on updating “Setup Shipping”.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4089]
**Step to Reproduce:**
1. Create a test site using JN. 
2. Complete initial screens and go to dashboard.
3. Click on "Add your first product".
4. Note that Tax options are not available on add product page.
5. Now go to "Setup Shipping" page and update shipping details.
6. Now go back to "Add Product".
7. Observe that  tax options are displayed.

**Actual Result:**
Tax option in “Add Your first product” gets updated on updating “Setup Shipping”.

**Expected Result:**
Tax options should be available on the "Add product" screen.
![9_Actual](https://user-images.githubusercontent.com/41110392/78812668-6827c880-79e9-11ea-81ee-193083ddda6d.png)
![9_Expected](https://user-images.githubusercontent.com/41110392/78812674-69f18c00-79e9-11ea-8747-ef31160b439e.png)

**Comment by timmyc** [comment]
I think this is working as intended, as tax inputs are dependent upon taxes being configured for use on the site. The only solution I see here is moving the tax setup above the product setup in the setup check list. Thoughts @pmcpinto @jameskoster

**Comment by pmcpinto** [comment]
I would keep the order that we have in the task list and then provide an inbox message about this. @jameskoster what do you think?

**Comment by jameskoster** [comment]
Yeah I think this is something we should address on the product screen. Hiding the inputs based on other settings perhaps isn't the most elegant solution.

It is strange that completing the shipping task reveals these options though. Is the store address the pre-requisite?

Either way, we should probably check that a `tax status` value is set in this scenario, regardless of whether it's visible or not. Just because it would be frustrating for users if products are set as non-taxable by default, and then have to update them all once tax settings have been configured.
