### ISSUE TITLE
[GlobalStep - 4.1 beta 1] On Safari(v13.0.5), "Setup Payment" page only "Done" button is displayed.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#4106]
**Step to Reproduce:**
1. Create a test site using "https://jurassic.ninja/".
2. Complete initial screens and go to dashboard.
3. Go to "Setup" screen.
4. Click on "Setup Payments".
5. Note that blank screen is displayed. 
6. Observe that only "Done" button is displayed.

**Actual Result:**
On Safari(v13.0.5), "Setup Payment" page only "Done" button is displayed.

**Expected Result:**
All payment options should be displayed upon clicking "Setup Payment".

![19](https://user-images.githubusercontent.com/41110392/78920779-8c4edc80-7ab1-11ea-9550-5d1661a032b3.jpg)

**Comment by timmyc** [comment]
@gglobalstep do you have any details around the store address, specifically the country, used in this test? Also which "Industries" did you select. I'm guessing this might be the same bug that @juliaamosova and @vedanshujain hit when testing Beta 2 today which would be the following:

- A non US address was entered in the OBW Store Details ( Step 1 )
- On the Industry page ( step 2 ), "CBD and other hemp-derived products" was selected

The bug is happening because the only payment option that supports CBD sales is Square, and that method [is only visible for US stores](https://github.com/woocommerce/woocommerce-admin/blob/master/client/dashboard/task-list/tasks/payments/methods.js#L263).

The solution I think we should do at this time is to remove "CBD and other hemp-derived products" from the Industries page, unless the store address is in the USA. Does that sound good to you @pmcpinto ?

**Comment by psealock** [comment]
The solution I think we should do at this time is to remove "CBD and other hemp-derived products" from the Industries page, unless the store address is in the USA. 

Agreed, this solves the problem by eliminating this situation.

https://github.com/woocommerce/woocommerce-admin/pull/4117

**Comment by pmcpinto** [comment]
> The solution I think we should do at this time is to remove "CBD and other hemp-derived products" from the Industries page, unless the store address is in the USA. Does that sound good to you @pmcpinto ?

Yep, let's go with this solution. Thanks
