### ISSUE TITLE
New inbox notification: Track your store performance on mobile

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4227]
**Title:** Track your store performance on mobile
**Content:**  Monitor your sales and high performing products with the Woo app
**Segmentation:** Existing users
**Timing:** 9 months after they created store (if they haven't downloaded the app)
**Cadence:** Once
**CTA leads to:** https://woocommerce.com/mobile/?utm_source=inbox
**CTA label:** Learn more

**Note:** this one can be implemented by the mobile team

**Comment by timmyc** [comment]
Chatting a bit with @astralbodies [on slack about this](https://a8c.slack.com/archives/C6H8C3G23/p1594660561458100) and it seems like there isn't a really quick/easy way to determine if a site is already using one of the mobile apps.

As such I don't think we can ship an informed inbox notification per this spec right now.

**Comment by pmcpinto** [comment]
Perhaps we can apply a similar logic that was used in #4225 - if they actioned the "Install Woo mobile app" note, we don't display this note

**Comment by becdetat** [comment]
> if they actioned the "Install Woo mobile app" note, we don't display this note

That would require setting an option when they action the install app note, and adding a new rule to the remote inbox notifications system, which would require a new version of WCA to be installed prior to rolling out the new notification.

Which is fine, because recording the fact that the actioned the install app note needs a new version of wca to be installed anyway.

My estimate is 3.
