### ISSUE TITLE
Webpack builds files in project root

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4261]
**Describe the bug**
Occassionally, the new optimized files introduced in https://github.com/woocommerce/woocommerce-admin/pull/4094 get built directly in the wc-admin root instead of the `dist` folder.

This seems to happen on branch change.  This may just be a point of frustration temporarily and not long-term since it's unlikely we'll be switching back and forth between branches with this change for too long.  We may decide that this is an edge case and does not need a fix.

If we do decide to fix this, my best guess is that this is stemming from the introduction of the `path` property in webpack `output`.

**To Reproduce**

1. Go to an older branch or commit.
1. Run `npm start`.
1. Switch to the current master.
1. Note the files are built in the root directory.

**Expected behavior**
Expected to only have those files built into `dist` folder.

**Screenshots**
<img width="518" alt="Screen Shot 2020-04-30 at 3 01 56 PM" src="https://user-images.githubusercontent.com/10561050/80713600-6ccd3180-8afc-11ea-9b79-f78b11521090.png">

**Comment by jeffstieler** [comment]
Hmm that seems really tricky (if possible) to solve. AFAIK this is a problem any time we make a change to the Webpack config - you have to restart the `--watch` process.

It looks like some folks have had success with using `nodemon` to do this: https://github.com/webpack/webpack-dev-server/issues/440#issuecomment-409231332

However, the problem is if you introduce a change to the config that breaks the JS it appears that the process might not be able to recover.

Unfortunately I don't think there is any way to retroactively fix these older branches since any potential fixes will require changes to the way we invoke the build+watch process.

Is it still worth trying to handle? Breaking Webpack config changes are pretty infrequent.

**Comment by joshuatf** [comment]
>Unfortunately I don't think there is any way to retroactively fix these older branches since any potential fixes will require changes to the way we invoke the build+watch process.

I attempted a quick fix at this yesterday and you're right, we would need the newly added watch arguments to be already in the old branches for this to work with our current configuration.

>Is it still worth trying to handle? Breaking Webpack config changes are pretty infrequent.

Agreed.  I don't think this is worth going down a Webpack rabbit hole for something that rarely comes up.

Closing this issue for now.
