### ISSUE TITLE
Dashboard page is empty

### ISSUE THREAD

**Issue by froston** [woocommerce/woocommerce-admin#4344]
**Describe the bug**
When I go to `Woocommerce->Dashboard` or any page in `Woocommerce Admin` the page is blank, not showing any content. There is a JS error in console: `Uncaught SyntaxError: Unexpected token ','` The error appeared afeter I migrated my page to the hosting thru [Akkeba Backup plugin.](https://www.akeebabackup.com/products/akeeba-backup-wordpress.html) but possibly that is not related to it.

**To Reproduce**

1. Go to Woocommerce->Dashboard or any page in Woocommerce Admin
2. See the blank page

**Expected behavior**
It should show the content and no errors.
**Screenshots**

![image](https://user-images.githubusercontent.com/24678624/81614126-f65ee800-93b5-11ea-9293-cf217d76f26a.png)

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser Chrome 81.0

**Comment by psealock** [comment]
Thanks for the report. Could you click on `VM589_index.js` to see the minified code? You can click on this icon in Chrome to make it a bit more readable.

![Screen Shot 2020-05-12 at 11 06 01 AM](https://user-images.githubusercontent.com/1922453/81620761-c14ba780-9440-11ea-86ec-60b820b82650.png)

Hopefully this can reveal good info on where the bug is coming from. Thanks!

**Comment by froston** [comment]
That's weird, but the issue seems to disappear for some reason!
Thank you anyway for the help.
