### ISSUE TITLE
WP Data should handle resolution status

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4384]
Now that things are moving towards wp data, we can remove specific selectors that check for `isSomethingRequesting` and use the built-in selectors in wp data.

For example, this call is no longer needed:
https://github.com/woocommerce/woocommerce-admin/blob/e0bab726b658bdc0edd3bb5c693cb5d63342da5e/packages/data/src/plugins/resolvers.js#L71

And call to check for requesting can be replaced with:
`isResolving()`

https://github.com/WordPress/gutenberg/blob/1e8d78189a9b05628b171016e102e2c50e267c39/packages/data/src/namespace-store/metadata/selectors.js#L55

This [blog post](https://unfoldingneurons.com/2020/wordpress-data-store-properties-resolvers) is also a very good overview of some of the available built-in selectors.  Big thanks to @nerrad for these suggestions and taking a look at our current implementation.

**Comment by nerrad** [comment]
Also should be noted that the current implementation of `isRequesting` in the plugins resolver is prone to bugs because `getJetpackConnectionUrl` can be called with a `query` argument. 

Resolver state is cached by selector name and arguments. So _every time_ the query argument changes, the resolver will be called. When this happens you could potentially have multiple in flight requests but as soon as one of them is finished `setIsRequesting( 'getJetpackConnectUrl', false )` is called and thus `isRequesting` will be false _even if other in flight requests are not complete yet_.

It's possible this didn't surface as a bug anywhere because of the way things are currently implemented, but the pattern certainly could produce bugs if used elsewhere.

All that to say, it's good you're doing a review of this pattern 👍
