### ISSUE TITLE
Hydration fails when data store registered multiple times

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#4443]
**Describe the bug**
The plugin, settings, and soon-to-come hydration HOCs set the initial state for a component so the state is readily available without needing to send a network request to resolve information.

Lazily loaded Webpack chunks appear to be chunking the stores in multiple files instead of sharing them, causing them to be re-registered when imported.  This then reset the state to the default state set in the store.

Not that there is a temporary fix for this in https://github.com/woocommerce/woocommerce-admin/pull/4433 but this should be handled by building the stores in their own module and that fix eventually removed.

Thanks to @psealock for discovering the cause and for @nerrad helping us debug the issue.

See p1590435699034400-slack-woo-start-manage for full discussion.

**To Reproduce**

1. Log the state of the plugins.
1. Visit a page, such as the Profiler, that is lazily loaded.
1. Note that plugins are initially hydrated and subsequently reset, then filled again after resolution.

**Expected behavior**
Expected the `registerStore` function to only be called once per store.

**Comment by joshuatf** [comment]
I don't know the solution off the top of my head to this one.  I think it's to include the data stores as part of the main chunk file, but I don't know exactly how easy this is to do and for that reason I'd estimate a 3.

@jeffstieler will probably have a more accurate estimate on this one.

**Comment by jeffstieler** [comment]
I'm more optimistic for a quick fix, but out of caution will estimate 2.

**Comment by samueljseay** [comment]
Unassigning myself from this because I can't reproduce the behaviour stated. Here's what I tried:

1. On a fresh install and build of main I did the reproduction steps. I couldn't see the behaviour (expected)
2. I removed the conditional checks and did the reproduction steps that stop `registerStore` being called, I saw the behaviour the same as without them. (not expected).
3. I also tried various code splitting strategies of webpack and they didn't change the behaviour at all either.

Possible explanations:

1. Maybe since this problem arose a side effect or another change has stopped this being a problem.
2. Maybe I'm misunderstanding the issue. I'd love if someone more familiar like @joshuatf could take a look at this and confirm. If you can reproduce it, I'd love to see some more detailed reproduction steps, because I think as they are, they do leave it up to interpretation a bit.

**Comment by joshuatf** [comment]
I can no longer reproduce this issue.  I would venture a guess that some recent webpack changes may have also resolved this issue.  @jeffstieler may have more info on those how those changes affected this.

I think this issue can instead remove those checks (or at least `@todo` comments) around `registerStore` since the primary issue appears to be resolved.
