### ISSUE TITLE
Analytics Reports can not be sent via email on WPcom eCommerce plans

### ISSUE THREAD

**Issue by senff** [woocommerce/woocommerce-admin#4483]
**Describe the bug**
When you try to email a revenue report, it says an email will be sent. However, the email is never sent.

**To Reproduce**

1. Access WP-admin of a WordPress.com site with an eCommerce plan
2. Go to Analytics
3. Select a range that is relatively long, such as "Year to date" or "Last Year"
4. Select the "Download" button

**Expected behavior**
Message "_Your Revenue Report will be emailed to you_" appears at the bottom of the page, and the email arrives a few minutes after that.

**Actual behavior**
The message appears, but the email is not sent.  

**Additional context**
WP Mail Logging shows that the email is not sent to begin with with the error message "_Message body empty_"

Error logs show the following:
`[02-Jun-2020 19:45:47 UTC] wc_get_template was called incorrectly. <code>/wordpress/plugins/woocommerce/4.1.1/packages/woocommerce-admin/includes/emails/html-admin-report-export-download.php</code> does not exist.`

**Comment by kriskarkoski** [comment]
Another case in 21651023-hc. In this case and others on eCommerce the plugin cannot be force installed due to being symlinked. Maybe this is specifically an issue with the symlinked version?

**Comment by mdmoore** [comment]
One more report in 3309106-zen.

**Comment by madeincosmos** [comment]
Also reported in 3396985-zen

**Comment by xpurichan** [comment]
Another report in 3436794-zd. I did install `woocommerce-admin` version `1.6.2` and generated a new report. The AT Logstash logs don't show that a new email was sent, unfortunately. This could be a two-fold issue in my case of the customer experiencing this scenario AND using an @gmail.com email address instead of a custom domain email address.

**Comment by RiaanKnoetze** [comment]
There seem to be some reports that this isn't isolated to WPCOM e-commerce plans only, see https://wordpress.org/support/topic/revenue-report-email-not-being-sent/

**Comment by johndcoy** [comment]
Another report of this on a site using Google Cloud hosting 3650119-zen

**Comment by cgsmith** [comment]
@johndcoy this does not appear to be related to #5774 as there is no error in the log.

**Comment by timmyc** [comment]
Wanting to add a note here to capture what I know about this bug, and also to make sure that it doesn't get confused with other reports of CSV exports failing like we are seeing on issue #5774 

The eCommerce plan installs WooCommerce, and a number of other plugins, using symlinks to a shared install point across sites. Because of this, the email logic in WooCommerce appears to try and use a path to load the CSV report template, and fails to locate the file due to the path being incorrect. This results in the email failing to send every time.

When I have looked at possible fixes, it seems like a fix for the mailer class within WooCommerce might be needed, or perhaps a simpler fix would be to move the email templates for these reports to Woo Core itself ( or leverage a generic template if one exists ) since all other transactional emails seem to work fine. It seems to only impact WooCommerce Admin since it is installed as a composer package.

Another possible fix, that I have to explore - Installing the plugin version of woocommerce-admin.

I did share some other work-arounds to not having reports emailed at all [here](https://github.com/woocommerce/woocommerce-admin/issues/5774#issuecomment-765650472)

**Comment by timmyc** [comment]
I'm adding this issue to the the "Needs Scoping" to get some more dev eyes on it this week. @octaedro I see you assigned yourself here. Can you share anything you have discovered with this issue to help the others doing scoping for the next cycle?

**Comment by octaedro** [comment]
> Can you share anything you have discovered with this issue to help the others doing scoping for the next cycle?

@timmyc I can't recall too much. But I think this issue will also affect the new `merchant email notes` (p90Yrv-25h-p2) since they use the email [templates too](https://github.com/woocommerce/woocommerce-admin/blob/main/includes/emails/html-merchant-notification.php). So fixing this bug will be a double win 🙂

**Comment by timmyc** [comment]
Thanks @octaedro - I had the same concern about the note generated emails.

**Comment by psealock** [comment]
Estimate: 3

It seems like the source of the issue has been identified and a few solutions under proposal. 

>It seems to only impact WooCommerce Admin since it is installed as a composer package.

Maybe this can be leveraged to determine a path that is correct

**Comment by jeffstieler** [comment]
@timmyc are you able to reproduce this? I just tried with a Stock report (easiest to set up with no data) and while the email hasn't hit my actual inbox, I was able to see it using the WP Mail Logging plugin:
![Screen Shot 2021-04-16 at 12 57 23 PM](https://user-images.githubusercontent.com/63922/115065234-e2701000-9ebb-11eb-9984-9d3cfaeaf2f2.png)

**Comment by timmyc** [comment]
I just tested on a new ecom plan, using the revenue report and confirmed that the mail was sent correctly too. Guess this is no longer an issue so closing it out

**Comment by arvydasg** [comment]
Email does not get sent.

**Comment by eifjell** [comment]
I'm having the same issue here. The notification of e-mail being sendt pops up, but no e-mail is received.

**Comment by AtlantisNet-com** [comment]
We're having the same issue as well. Check out https://github.com/woocommerce/woocommerce-admin/issues/7920
