### ISSUE TITLE
Task List - creating WooCommerce pages without completing the store profiler

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4575]
**User story:**
As a new merchant
I want to be able to create the WooCommerce pages without completing the onboarding
So I can still have the basic pages created as quickly as possible

**Description:** we're going to streamline the [WooCommerce pages](https://docs.woocommerce.com/document/woocommerce-pages/) creation by automatically creating them, independently if the user completes the onboarding 

**Acceptance Criteria:**
- [ ] Automatically create the [WC pages](https://docs.woocommerce.com/document/woocommerce-pages/) independently if the user completes the onboarding 

**Event tracking:**
NA

**Comment by timmyc** [comment]
This one feels pretty straightforward to me - calling `create_pages()` [#](https://github.com/woocommerce/woocommerce/blob/c35c4f1f084bb397a023682229477286b418ad54/includes/class-wc-install.php#L545) does most of the heavy lifting for us.

Implementation-wise it also looks like we have some prior [REST API endpoints](https://github.com/woocommerce/woocommerce-rest-api/search?q=create_pages&unscoped_q=create_pages) to work with as well - I'm not totally certain on the level of effort to integrate those in with wp.data therefore I'm going to put this a little bit higher on the effort estimate:

Estimate: 3

**Comment by joshuatf** [comment]
Good news is that we actually have this endpoint already in place in onboarding:

https://github.com/woocommerce/woocommerce-admin/blob/0b68c1d7c0c5025789071022efa129126da1ded5/src/API/OnboardingTasks.php#L56

Estimate: 2

**Comment by mattsherman** [comment]
If there is no input required from the user to create the WooCommerce pages, and they are required to be in place in order to have a functional store, why not just automatically create them when the user skips the store profiler, instead of introducing this new task that doesn't really require anything from the user?

**Comment by pmcpinto** [comment]
> If there is no input required from the user to create the WooCommerce pages, and they are required to be in place in order to have a functional store, why not just automatically create them when the user skips the store profiler, instead of introducing this new task that doesn't really require anything from the user?

That's a good point, it simplifies the implementation and the experience. cc @jameskoster

**Comment by jameskoster** [comment]
Yep that makes a lot of sense :D

**Comment by pmcpinto** [comment]
I'm going to update the issue description to only cover the auto-creation of the Woo pages independently if the user finishes the obw.

**Comment by jeffstieler** [comment]
Sorry I didn't follow back up on this during the cooldown period.

Going further - why not just have WooCommerce core create the pages as part of it's install routine? Why have this in WC-Admin at all?

**Comment by jameskoster** [comment]
The reason we didn't auto-generate the pages in the past was due to concerns that people who had established sites, and were just trying out wc, probably wouldn't want a bunch of pages being published to their site without their say so. This was at a time where pages were generally added to frontend menus automatically upon publish :D

I suppose that is less of a concern now that most people manage their menus manually. But that is a very good point @jeffstieler. It's probably worth discussing this with Proton.

**Comment by pmcpinto** [comment]
That's a good point.

@peterfabian what do you think about auto-installing the WooCommerce pages after the user activates the plugin? I can open a new issue in the Core repo about this.

**Comment by peterfabian** [comment]
Sorry for my late response. I've heard some people also mentioned that creating those pages later in the process (not during install) was better when people install plugins and later switch their site to another language, as they would have 'Cart' and 'Shop' instead of 'Cesta' or 'Tienda' pages, but I think that's an edge case. 

I agree the pages should be created in core and probably in a better way than tied to onboarding. Created https://github.com/woocommerce/woocommerce/issues/27286 to get it done on our side (and I think this one can be closed)

**Comment by joshuatf** [comment]
Awesome, thanks @peterfabian.

On the WCA side, we'll need to:
* Remove the API call that creates store pages in store details unmount.
* Potentially remove the `/create_store_page` route from the onboarding API in favor of the methods added in core.
* Coordinate when this fix gets released with the update in core.

**Comment by rrennick** [comment]
Removing the old onboarding removes the Setup help tab so it will need to be added for onboarding https://github.com/woocommerce/woocommerce/pull/26853

**Comment by rrennick** [comment]
https://github.com/woocommerce/woocommerce/pull/26853 is ready for review. It breaks the core E2E tests due to not redirecting to the setup screen. It will need a PR for this to restore passing E2E tests.
