### ISSUE TITLE
Task List - Tax task: redirect to settings after enable automated taxes

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4631]
**Describe the bug**
On the Tax step, I'm being redirected to the settings after enabling automated taxes: https://d.pr/i/b2sGmf

**To Reproduce**

1. Create a new store and install/connect JP and WCS at the end of the store profiler
2. Go to the Tax task in the Home screen
3. See the message about automated taxes and click to enable them
4. See that you're redirected to Settings
5. If you go back to the task and do the same it not redirects to the home screen

**Expected behavior**
I was expecting to be redirected to the home screen

**Comment by pmcpinto** [comment]
I think that this was already happening before 1.3.0, but I'm adding it to the milestone in case it's possible to quickly fix it.

**Comment by timmyc** [comment]
@c-shultz I was looking around the WCS code to see if there might be a redirect that is being triggered somewhere there after taxes are "setup". I'm not seeing anything jump out at me, but by chance do you know if there might be some code in the WCS plugin that is causing this?

Pedro since this is happening already outside of the 1.3 release, I'm going to remove it from the milestone. Plus kind of feeling like it might be WCS triggering this redirect, but maybe Chris will confirm ;)

**Comment by pmcpinto** [comment]
> Pedro since this is happening already outside of the 1.3 release, I'm going to remove it from the milestone

Ok, I'll include it as part of Cycle 4, just in case it's not something on the WCS side

**Comment by c-shultz** [comment]
@timmyc ,

I don't see anything that would be triggering this on the WCS end, and I don't see any changes that we've made related to this.

I tested this and saw the same thing. It redirected to `admin.php?page=wc-settings&tab=tax&section=standard` I see several places in this file where it makes that redirection:
https://github.com/woocommerce/woocommerce-admin/blob/main/client/task-list/tasks/tax.js 

Could the root cause be there?
