### ISSUE TITLE
Accept WCS Terms of Service on install

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#4696]
_Edited from earlier today to only include the copy change._

**Is your feature request related to a problem? Please describe.**
Not a huge problem since we already have the TOS being accepted from this step, but if Jetpack is already installed and connected (Woo-pack users), we can include copy for those merchants that explains the WooCommerce Services [Terms of Service](https://wordpress.com/tos/) will be accepted upon installing the extension.

**Additional context**
![Install WCS](https://user-images.githubusercontent.com/5121465/85756331-51ce0680-b6d4-11ea-9881-e700b35006ad.png)

The detail text includes the copy "...and you agree to our Terms of Service" and provides a link out. cc @jameskoster @pmcpinto @c-shultz

**Comment by c-shultz** [comment]
@elizaan36 ,

I just did some testing with this flow. I was surprised to see that it appears that the ToS is being accepted when they go through this flow. WCS is not asking me to take that extra step after the fact. Can you confirm if that's what you see on a fresh site?

If that's true, then the copy should probably be updated here as you suggest, but we won't need any code changes otherwise.

**Comment by c-shultz** [comment]
It appears that wc-admin is setting the option `woocommerce_setup_jetpack_opted_in`, which flags WCS to accept the ToS. I was not aware of this as path to accept the ToS until now.

**Comment by elizaan36** [comment]
@c-shultz that's great. If it's just a copy change then even better.

As discussed on Slack, I'll edit the issue to only refer to the copy changes.☺️

**Comment by pmcpinto** [comment]
@c-shultz can you submit a PR with that change? Thanks!

**Comment by c-shultz** [comment]
Sounds good. I have it added to our sprint board!
