### ISSUE TITLE
Removing the Marketing tab in WC 4.3 rc1 

### ISSUE THREAD

**Issue by gbruzzo** [woocommerce/woocommerce-admin#4716]
Hello there

up to Woocommerce 4.2 it was possible to remove the marketing tab by using  
`add_filter( 'woocommerce_marketing_menu_items', '__return_empty_array' );`
in a plugin. 

see woocommerce/woocommerce#26499

This does not work anymore since Woocommerce 4.3 rc1 (maybe already from beta)

The line

`$marketing_pages = apply_filters( ‘woocommerce_marketing_menu_items’);`

usually on line 77 of woocommerce/packages/woocommerce-admin/src/Features/Marketing.php in function add_parent_menu_item()

was moved to function register_pages() (about 30 lines down) as

`$marketing_pages = apply_filters( ‘woocommerce_marketing_menu_items’, []);`

At the moment using 

`add_filter( 'woocommerce_admin_disabled', '__return_true' );`

causes both Admin to be Removed. **It would be proper practice to allow users to enable Admin but Disable Marketing.** 

The Marketing Tab is, at the moment at least, a **wholly useless advertising platform**. 

It would be nice to be able to disable it, if not used. 

Thank you in advance 

Giacomo Bruzzo

**Comment by gbruzzo** [comment]
@peterfabian all understood, thank you

**Comment by jconroy** [comment]
Hi @gbruzzo 

>  It would be proper practice to allow users to enable Admin but Disable Marketing.

As you've noted we've rearranged things a little. Because the marketing tab is set up setup as a feature in wc-admin you can actually use the [woocommerce_admin_features](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Loader.php#L129) filter to get selective about what features you wish to enable/disable if you wish.

I've updated my [original gist](https://gist.github.com/jconroy/e21c146aefa4301397b65d430f80dc05) with a basic example.

**Comment by gbruzzo** [comment]
@jconroy 

Thank you, will check out woocommerce_admin_features pronto. 

Appreciated

**Comment by isaumya** [comment]
Thank you @gbruzzo for raising the issue. I was also felt wired after upgrading to v4.3 due to this exact same reason. Also super thanks to @jconroy for sharing the awesome gist.

Anyways, I've also made a much more explainer gist, just in case if anyone is looking for it: https://gist.github.com/isaumya/89f48dcd84cb58af1e668bb76ba2c029

Thank you all for your amazing contribution. 🙂

**Comment by gbruzzo** [comment]
Cheers @isaumya 
There is also a plugin now available (see [this link](https://wordpress.org/plugins/disable-dashboard-for-woocommerce/) which operates along the lines indicated above.

**Comment by timmyc** [comment]
@gbruzzo I'm going to close this out since there have been a few gists offered up as ways to remove the Marketing menu item. Thanks @jconroy and @isaumya for taking time to contribute another gist here as well.

**Comment by peterfabian** [comment]
Please note that with WC 4.4, coupons are getting moved under the Marketing menu, so just hiding the tab might cause problems.

**Comment by isaumya** [comment]
@peterfabian What other solution do you recommend if we don't wanna see the marketing things but want to use the coupons? I mean honestly, the marketing tab is simply useless for most people, I have no idea why it exists.

**Comment by jconroy** [comment]
Hi @isaumya 

> I have no idea why it exists.

There are a few reasons:

* It's possible you’ve seen the [proposal for the new menu system](https://woocommerce.wordpress.com/2020/07/01/scaling-the-woocommerce-navigation-call-for-testers/) being worked on for WooCommerce - the changes we are making are small steps to begin to align the existing navigation with the larger overall vision for the future of WooCommerce.
* The Marketing tab itself is **small first step** towards a more integrated, cohesive marketing experience in WooCommerce core (similar to what many other ecommerce platforms/provide provide. We working towards giving merchants the ability to launch, manage, and measure their marketing activities. Think things like automations, campaigns, customer segmentation, coupon management, marketing focused analytics, and reporting…
* We are in the process of working with extensions to integrate more closely with the tab - looking to move their own menu items etc. under marketing - we're just taking it slowly and hope to ramp this up in the coming months.

> What other solution do you recommend if we don't wanna see the marketing things

The Recommend Extensions component/s (like other marketing suggestions areas in WC) [can be disabled](https://docs.woocommerce.com/document/marketing-hub/#section-4).

> I mean honestly, the marketing tab is simply useless for most people,

Appreciate the feedback/thinking - we _are_ actively working to make this a more valuable area for merchants.

**Comment by jconroy** [comment]
> so just hiding the tab might cause problems

Just a note on this, we took the precaution that if the marketing _feature_ in wc-admin is/has been disabled, we also revert the coupon menu back to the original location / disable the coupon _feature_

**Comment by isaumya** [comment]
@jconroy Thank you so much for your reply. Now I completely get why it exists. But the point I was trying to make is that WooCommerce is being used in millions of website in various different ways.

For example on our website some of our services can be directly purchased over WooCommerce and for other services you need to fill up a form and we will get back to the customer.

Now for the services that can be purchased over WooCommerce, we just use WooCommerce checkout. We don't use shop, cart, my account or anything. Just the checkout page.

The reason I'm telling you this is because not everyone will be using all the features and there should be a way to disable the things the user don't wanna use.

Also I've tried the disable suggestion option, it just shows kinda blank marketing page. I mean why would I like to keep that around? Increasing another menu item on my left side.

**Comment by peterfabian** [comment]
> Just a note on this, we took the precaution that if the marketing feature in wc-admin is/has been disabled, we also revert the coupon menu back to the original location / disable the coupon feature

That's awesome, thanks for being thoughtful about the change! Let's pretend I just wanted more people to test our RC, then :)
