### ISSUE TITLE
Why all the analytics page displays path as path=%2?

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce-admin#4915]
I think other queries are in better order but why all the analytics page displays path as path=%2?...

**Comment by timmyc** [comment]
@shivapoudel that is part of the routing aspect of the single page application that powers this part of WooCommerce. Do you have a specific concern about this URL param?

**Comment by shivapoudel** [comment]
@timmyc While seeing JetPack, it is routing with HashRouter and URL seems bit tide like `admin.php?page=jetpack#/dashboard` but here at WooCommerce admin, it is with `path=/analytics/revenue` and Router is BrowserRouter so the path has slash and browser encodes them.

I am kickstarting some sort of SPA and got a bit curious to know which Routing methodology as an Automattician you suggest for simple WordPress Plugin with SPA which has its route-specific page only. Any sort-of idea to get rid of that encoded slash in SPA is appreciated?

For example  **WP admin menu pages**
- Dashboard (Sub-menu) = Route
---- General tab (Nav item) = Another sub route
- Settings (Sub-menu) = Route
---- General tab (Nav item) = Another sub route

**Comment by timmyc** [comment]
Looks like WooCommerce Admin, Jetpack and the Calypso project are all using the react router "under the hood" so that seems to be the standard.

> Any sort-of idea to get rid of that encoded slash in SPA is appreciated?

I'm personally not super savvy on ways around this, but would imagine there has to be content available online on different approaches here.

I am going to close out this issue since it isn't really a bug, but more of a question. I am happy to respond further but just triaging issues and getting this closed if there is no direct action we can take in the code base.
