### ISSUE TITLE
TableCard Component: Hide few columns by default

### ISSUE THREAD

**Issue by surajv** [woocommerce/woocommerce-admin#4967]
I am using `TableCard` component to create a custom table with custom data.

Is there any way to hide few columns by default and user can enable them later?  https://i.rankmath.com/ChAhkv

**Comment by shakeeb-mts** [comment]
Hello @timmyc and @loranallensmith can you please have a look at the issue.

**Comment by timmyc** [comment]
@surajv @shakeeb-mts the `TableCard` component does not support this functionality by default, but you can implement it in your own wrapping component as desired. You can see an example of this in our `ReportTable` component [here](https://github.com/woocommerce/woocommerce-admin/blob/main/client/analytics/components/report-table/index.js#L161-L175). For our use case, we persist the column visibility values in user meta and adjust the visibility of columns based upon that.

This logic was left out of the base `TableComponent` because it introduces too much application specific logic to the base component. There have been some requests for us to publish something more along the lines of the `ReportTable` component in the past though. But for now, you could probably copy/paste a bit of that logic to make things work in your application.

I'm going to close this issue out, but feel free to reply back with any further questions.
