### ISSUE TITLE
Notice is not hidden in WC pages

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce-admin#4976]
**Describe the bug**
Notice is not hidden in WC pages.

**To Reproduce**

1. Display some admin notices.
2. Click on 'Marketing > Coupons'
4. See that errors in not wrap in a hidden wrap.

**Expected behavior**
Notice is displayed in WooCommerce Admin Marketing > Coupons page.

**Screenshots**
![image](https://user-images.githubusercontent.com/3774827/90021928-97b94b00-dcd1-11ea-9996-91d6fc8d3813.png)

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by timmyc** [comment]
Hello there @shivapoudel - it looks like that particular message is generated by the MonsterInsights plugin - not WooCommerce. Here is the code that generates that message in the plugin: https://plugins.trac.wordpress.org/browser/google-analytics-for-wordpress/trunk/includes/admin/admin.php#L281

Since this is created by a plugin other than WooCommerce, I'm going to close this out.

**Comment by shivapoudel** [comment]
@timmyc I ofcourse agree it is not created by WooCommerce. In other marketting/analytics page it is hidden but not on that coupon page. I know woocommerce admin wrap those admin messages in certain div and hides them but it is not working on coupons page.
