### ISSUE TITLE
Home Screen: Enable store setup task list if user skips the wizard

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4989]
Currently, the store setup task list is only enabled if the user doesn't skip the wizard. However, it can be valuable to automatically enable the task list when WC is activated:

- A new user can find the task list useful even if he doesn't want to share the store profile info
- He also may have bypassed the wizard without noticing it.

**Comment by joshuatf** [comment]
Estimate: 1

Though there could be some follow-up issues if there is any task list logic dependent on profiler (though at a glance it doesn't appear there will be any issues here).

**Comment by samueljseay** [comment]
This one is actually a bug, because most of the time the task list does display.

I'll paraphrase these findings reported by @becdetat (thank you!)

The only place the store setup task list does not show is if the onboarding wizard is cancelled via "use the new setup experience" step which is *not* shown if you're using the woocommerce-admin plugin.

If you skip the onboarding wizard from the store details step it still shows the task list.
verified that `woocommerce_task_list_complete` and `woocommerce_task_list_hidden`  are both left unset after 
skipping the onboarding wizard, which should have triggered the task list being visible, but somehow the task list wasn’t visible and the quicklinks are visible  [see the code](https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/layout.js#L64).

**Comment by joshuatf** [comment]
Seems like the `enable_onboarding` which acted as a param to modify the feature flag is no longer necessary and the root of this issue.  On the WCA side, we just need to clean up references to this.

A follow-up is needed in core to make sure the "Not right now" action is actually able to skip the profiler.

**Comment by joshuatf** [comment]
On the WC core side, I think this issue will be resolved by bumping the WCA version number, though it does look like some clean-up may be needed around setup wizard files no longer used there.
