### ISSUE TITLE
Payments task - update countries list where Stripe is displayed as an option

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5209]
The [list of countries](https://github.com/woocommerce/woocommerce-admin/blob/d5c7d26caa33fc079a87016f29338ce378532c71/src/Features/Onboarding.php#L674) where we display Stripe needs to be updated:

**Include:**
BR (it no longer requires an invite)

**Exclude:**
EE
IN
LT
LV
MY
PR
RO
SK

**Comment by dechov** [comment]
What I believe was the previous change to the list (https://github.com/woocommerce/woocommerce-admin/pull/4545) brought it largely up to date with https://stripe.com/global. Regarding the removals, is there a better source for this list?

**Comment by timmyc** [comment]
@dechov I'm not sure of the best source of truth here - it would be pretty great if we could ask partnerships to follow up with Stripe to see if the page we have been using is the best spot, or if there was some way for us to be notified when changes to supported countries happen.

Is there a similar list being kept in the stripe extension itself? If so, while I know we can't access that from within the wc-admin code, perhaps whenever that list gets updated, there should be a note to update the config here in wc-admin too. Otherwise this really isn't something on team isotope's radar to check in on.

**Comment by dechov** [comment]
Ah, thanks, and good points. I'm collecting some context and will follow up early next week 👍

**Comment by thenbrent** [comment]
Just noting that there's more discussion about this in pbIJXs-jy-p2.

**Comment by dechov** [comment]
Opened https://github.com/woocommerce/woocommerce-admin/pull/5377 just to include Brazil without excluding any countries, with the understanding of that being the priority.

**Comment by dechov** [comment]
Closing based on Brazil having been added – and on further discussion in linked thread culminating in not necessarily needing to remove the other set of countries.
