### ISSUE TITLE
Home Screen - layout changes

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5223]
**User story:**
As a new merchant
I want to easily access the setup task list
So I can focus on completing the setup as soon as possible

**Description:** moving the setup tasks to the home screen increased retention among new users. However, we ended up seeing more users drifting away and not using the setup tasks. We bet that by some changes in the layout we'll be able to increase the focus in the setup tasks.

**Acceptance criteria:**
- [ ] For brand new stores we'll display a single column layout with the following order (setup tasks, stats overview, inbox)
![home-collapsed-task-list.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/d867c83e-3fda-40e6-b4ca-02e9d22abd36)

- [ ] Upon dismissing or completing the task list, the layout should default to two columns

![dismiss-task-list-1](https://user-images.githubusercontent.com/3380168/94914270-9d960600-04a2-11eb-848f-b850a972d846.gif)

- [ ] For existing stores we'll keep the two-column layout (this also includes stores that already have the setup task list enabled before the Woo version where we include the layout changes). However, we'll change the sections displayed on each column: the left column should include the tasks and store management section, on the right column we should have the stats overview and inbox
![Home.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/5e2ecc4b-486d-4d53-bc01-91db3b35d9ab)![Home (1).png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/fa27ac0c-2df4-44e3-b163-17137c1b3b06)

**Event tracking:**
It won't be necessary to include additional event tracking for this work

**Additional links:**
[P2 with link to Figma ](pbIJXs-ma-p2)

**Comment by jeffstieler** [comment]
How should these changes affect the "sticky" positioning of the right column? Do we simply flip the stickiness to the left column (when in 2 column mode)? cc: @elizaan36

**Comment by elizaan36** [comment]
hey @jeffstieler, since the Inbox messages will create a pretty lengthy page we should only introduce stickiness in either column when it's at the end of the scroll. Let me put together a [quick prototype](https://share.getcloudapp.com/p9uwOyO0) to illustrate...

![home screen sticky column scroll.gif](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/0a8e6293-51d9-4419-8b2f-cd85d0726ef2)

So in this case, when the scroll reaches the end of the left column, the right column is still free to scroll. This would happen in the opposite case as well, in case the user has dismissed all inbox notifications, the [stats overview would remain sticky ](https://share.getcloudapp.com/9ZuBoOk1)while the left column scrolls. 

![right column sticky.gif](https://images.zenhubusercontent.com/5f7c9605b2fe9f5aa9b5799b/44197874-0fc5-4944-a8ae-238b915e7200)
