### ISSUE TITLE
Remove "Historical Analytics Data" notice

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce-admin#5286]
**Describe the bug**

We've been experiencing this issue consistently on a number of sites, usually with the new-style "Database Update Done" notices. 

After a successful database upgrade, clicking "Thanks" seems to have no effect. Usually insisting a few times has the desired effect, but there is at least one local site/db I'm working with where the notice doesn't seem to go away.

I have found the "Historical Analytics Data" notice to behave similarly, probably by design? If the user doesn't want to import Analytics Data, the notice can't be hidden -- clicking "Get Started" has no effect and there is no "Dismiss" action.

**To Reproduce**

1. Update from WooCommerce 3.9
2. Trigger the DB upgrade process from the PHP notice that appears in the Dashboard upon logging in.
3. Wait for the DB upgrade to complete and reload the page.
4. Dismiss the PHP "thanks" notice that appears when the DB upgrades are complete.
5. Go to **WooCommerce > Home**.
6. You'll probably see another JS notice that the DB upgrade process is complete that can't be dismissed, along with the "Historical Analytics Data" notice, which can't be dismissed either.

**Expected behavior**

The new WooCommerce notices implemented in wc-admin should be dismissible, ideally without reloading the page.

On an unrelated note, it would be great if these notices followed all WordPress notice design conventions. Currently, WooCommerce is introducing its own notifications system, which sometimes results in the kind of WP experience it is trying to avoid (consistency suffers when the user sees 2 different notices about the same thing -- updating the DB -- that look different when moving from one admin screen to another).

**Comment by timmyc** [comment]
@franticpsyx thanks for bringing up both of these notifications. Looks like there is a similar issue in Woo Core for the database notice issues https://github.com/woocommerce/woocommerce/issues/27620 - and the database update notice is actually housed in the Woo core repo so I think that will get handled there. I'll drop a manual note on the issue there too for added visibility.

As for the historical data import notice - now that analytics has been in core since 4.0 - I think it is probably a good time to remove that notification entirely, or at the very least, just turn it into a standard inbox notification. I've updated the title of the issue to reflect that.
