### ISSUE TITLE
Navigation: Create slotFill guardrails to minimize misuse

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5327]
Fills to be consumed by plugins currently allow rendering of any children, which opens an avenue for misuse or a poor developer experience.

* Can we limit the types of children?
* Can we strategically place `console.warn` to help developers avoid pitfalls?
* Can we create a uniform experience with our Fills such that plugin only need to use `Woo*` components without needing to import `NavigationItem` from `@wordpress/components`?

**Comment by joshuatf** [comment]
I'm not quite sure what guardrails should be implemented here.  At first, I imagined we could limit that we could make sure child elements were of type `button` or anchor tags, but this doesn't work for custom components like a `Link` component that a consumer may want to use (even WooCommerce Admin will want to use its own `Link` component instead of links).

Any thoughts on other guardrails here?  /cc @psealock @joelclimbsthings

**Comment by psealock** [comment]
Given the nature of SlotFill, I'm not sure either. It seems to be an open invitation to place whatever you'd like. At least the result will always be wrapped in a `NavigationItem`.

https://github.com/woocommerce/woocommerce-admin/blob/dbeb7f9f44551b48d12a89381176e20b543086d8/client/navigation/components/Item/index.js#L14-L16

Unless there's any objection, I think we should close this for now.
