### ISSUE TITLE
[GlobalStep - WooCommerce 4.7 Beta 1][Android] "Mobile app banner" overlaps with "w" button on "Orders" page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#5459]
## Bug Description:
"Mobile app banner" overlaps with "w" button on "Orders" page.

## Environment:
Samsung Galaxy A50 (v10)
Browser: Chrome Version 86.0.4240.75

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Go to WooCommerce beta Tester.
1. Switch the WooCommerce version to 4.7 beta 1.
1. Now open the site on any Android device browser.
1. Tap on Hamberger menu.
1. Go to WooCommerce->Orders.
1. Observe that "Mobile app banner" overlaps with "w" button.
 
## Actual Result:
"Mobile app banner" overlaps with "w" button on "Orders" page.

## Expected Result:
"Mobile app banner" should be displayed properly aligned on "Orders" page.

## Artifacts:
[28044.zip](https://github.com/woocommerce/woocommerce/files/5417653/28044.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by joshuatf** [comment]
I can also replicate the issue.  It appears to be caused by setting an explicit height on `.woocommerce-embed-page .woocommerce-layout__header`.

This was probably done to match the `60px` standard being set, but would be great to avoid setting an explicit height if possible.

I'm also noting some funkiness with the new navigation enabled that can be addressed as part of this issue as well:

<img width="444" alt="Screen Shot 2021-01-26 at 6 34 25 PM" src="https://user-images.githubusercontent.com/10561050/105920982-49410400-6006-11eb-80fe-c0f1f83753e5.png">
<img width="443" alt="Screen Shot 2021-01-26 at 6 34 11 PM" src="https://user-images.githubusercontent.com/10561050/105920983-49410400-6006-11eb-8f9d-c522b0ade562.png">

**Comment by hsingyuc** [comment]
I'll give it a shot.

**Comment by hsingyuc** [comment]
@joshuatf  Perhaps should render the banner on top of the header so can solve the new navigation issue?

**Comment by joshuatf** [comment]
Thanks for taking a stab at this @hsingyuc.  I think your current open PR addresses the "W" however there may be some other opportunities to fix up the height here since we have other issues around header height.

Will provide more feedback on your PR early next week.

**Comment by joshuatf** [comment]
Estimate: 1

**Comment by timmyc** [comment]
@joshuatf would this also be in the header height bug list? ( #6235 )
