### ISSUE TITLE
New sale attributes in performance analytics 

### ISSUE THREAD

**Issue by mariakhala** [woocommerce/woocommerce-admin#5498]
Hi i want my custom sale attributes with net sales and gross sale in performance analytics. This attribute will show some of order with status expense(its my own status) and shipping cost of all in it. Any hook for it.
Thanks

**Comment by becdetat** [comment]
HI @mariakhala, thanks for your question. I'm not sure if this will fit your requirements, however I have a blog post (which will soon be added to the developers blog) detailing the hooks required to add columns to reports - https://becdetathome.wpcomstaging.com/2020/12/02/adding-columns-to-analytics-reports-and-csv-downloads/. Note that the current version of WooCommerce will not apply any modified columns to the instant, generated in-browser (if there are less than one screen of results) CSV; this should be fixed in WooCommerce 5.0.

Let me know if we can help further.

**Comment by mariakhala** [comment]
Thanks Woocommerce/Woocommerce-Admin i will check it out.
Best regards

**Comment by ilyasfoo** [comment]
I'm closing this issue as I think it had been resolved. Please reopen if you feel otherwise, thanks!
