### ISSUE TITLE
Navigation: Reorder Secondary Menu

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5531]
https://github.com/woocommerce/woocommerce-admin/issues/5530 creates a new section called "Extensions". The current secondary menu will need to change to reflect this.

![Screen Shot 2020-11-04 at 3 17 04 PM](https://user-images.githubusercontent.com/1922453/98061478-d154b900-1eb0-11eb-97e9-89b0147f70f1.png)

### Deliverables

* Secondary menu will be "Settings", "Maketplace", "Tools"
* Remove current "Extensions" category. "My Extensions" menu item that links to the plugins page is no longer in the designs. @elizaan36 to confirm please. "Marketplace" goes up a level.

**Comment by elizaan36** [comment]
> Remove current "Extensions" category. "My Extensions" menu item that links to the plugins page is no longer in the designs. @elizaan36 to confirm please. "Marketplace" goes up a level.

That's what the thinking is, yep. It's a bit jarring currently how the `All extensions` link takes you to WP plugins, so it would make sense to me if it were only the single Marketplace screen with no subnav. I don't see a major drawback to this, but it's worth noting that in order to see all of your WP plugins, users will have to navigate back to the WP dashboard and WP plugins folder.

**Comment by elizaan36** [comment]
To be sure I just chatted with @danhauk who's working on the marketplace screens and Marketplace may actually have a subnavigation. For example, he's suggesting two subnav items for `Extensions` and `Subscriptions` there.

Wanted to share the convo but I think the important thing is that `Marketplace` is pulled up one level and we can add the subnav items later.
