### ISSUE TITLE
Home Screen: Welcome Modal Flashes Briefly After Dismissed

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5555]
**Describe the bug**
While testing out pre-beta of 1.7.0 with Woo 4.6.2 and Gutenberg on a new JN site ( Safari used ) - I was noticing that when doing a hard refresh on the Home Screen, the welcome dialog is briefly shown/flashed during the page load:

https://cloudup.com/c-QiawR21Fg

**To Reproduce**

1. Do OBW, and dismiss the Welcome Modal on the home screen
2. Hard refresh the page and note the welcome modal is briefly shown.

**Expected behavior**
To not see the welcome modal after it has been dismissed.

**Comment by timmyc** [comment]
Tested this same item against 4.6.2 and I am not seeing this behavior in the current release. So this definitely seems like a regression with the new home screen work in 1.7.0

**Comment by samueljseay** [comment]
@timmyc could I get some more detail on this, because I can't reproduce locally, so just to confirm:

1. Does it happen with JN sites only?
2. Does it have to be Safari or did you reproduce with other browsers?
3. Could you confirm whether subsequent refreshes show the flicker or is it just the first refresh after dismissing it?

**Comment by samueljseay** [comment]
Scratch my comment above, I can now reproduce this locally.
