### ISSUE TITLE
Allow extensions to filter the order statuses used by WooCommerce Admin

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#5600]
**Describe the bug**
Currently, if an extension creates a new order status and filters it out so it's not included in Analytics (for example, with filter `woocommerce_analytics_excluded_order_statuses`), the status will still appear in several places of the UI like Analytics > Settings or Analytics > Orders > Advanced Filters > Order Status.

That might be confusing for users: why is the status appearing in the UI but the orders with that status are not included in the analytics?

**Use-case**
WC Blocks creates a Checkout draft order status that we want to exclude completely from WooCommerce Admin.

**Proposed solution**
Would it be possible to add a PHP filter that runs when order statuses are retrieved from the database ([maybe inside `get_order_status()`](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Loader.php#L1151-L1158))? That would allow extensions to completely exclude statuses from being used anywhere inside WC Admin.

**Comment by haszari** [comment]
A couple of comments about this (the new checkout block "draft" status is tricky IMO):

- Really, we want to exclude this status everywhere, not just in wc-admin. In other words, it's not a "real" status, it's hidden, or for internal use only. Would it be better to mark it as such somehow in core, rather than extend wc-admin + hook `woocommerce_order_query_args` (and whatever other patching we end up doing!). I realise this is not easy/practical in the short term, but if it's possible to work towards that, let's do it!
- Specific to wc-admin, there's a [concept of excluded-by-default](https://github.com/woocommerce/woocommerce-admin/blob/main/client/analytics/settings/config.js#L90), which is currently not extendable/filterable. Would this be a useful extension API? Is it worth considering for solving this issue – i.e. we extend wc-admin to add our checkout draft status to the "excluded by default" list.

**Comment by Aljullu** [comment]
Independently of the resolution we end up taking for the draft status in WC Blocks, I think there is still an extensibility need of what's described in the issue description. Currently, WC Admin allows setting `woocommerce_analytics_excluded_order_statuses` but those statuses still appear in the UI and there is no way to filter them out.

> - Specific to wc-admin, there's a [concept of excluded-by-default](https://github.com/woocommerce/woocommerce-admin/blob/main/client/analytics/settings/config.js#L90), which is currently not extendable/filterable. Would this be a useful extension API? Is it worth considering for solving this issue – i.e. we extend wc-admin to add our checkout draft status to the "excluded by default" list. 

+1. That might deserve its own issue, do you want to create it? (Otherwise, let me know and I will create it :+1: )

**Comment by haszari** [comment]
>  > Specific to wc-admin, there's a concept of excluded-by-default, which is currently not extendable/filterable. 
> +1. That might deserve its own issue, do you want to create it? (Otherwise, let me know and I will create it 👍 )

Let's see what feedback we get from wc-admin team on this issue first. I agree, but would like to hear @woocommerce/isotope point of view before adding more specific issues 😄

**Comment by psealock** [comment]
`woocommerce_excluded_report_order_statuses` [is filterable](https://github.com/woocommerce/woocommerce-admin/blob/main/client/analytics/settings/config.js#L75) and I think that satisfies the need @haszari brings up.

The original issue seems like a legitimate issue. It feels like a simple filter of the statuses should respect the excluded ones.
