### ISSUE TITLE
Home Screen: Orders Panel flashes empty state during load ( Gutenberg only )

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#5609]
**Describe the bug**
On 1.7.0 I noticed that when the orders data is loading to the activity panel, the empty/no order state is shown briefly a few times:

https://cloudup.com/cDOMVhYp3mg

**To Reproduce**

1. Install 1.7
2. Have some orders with actionable status
3. Hard refresh the home screen and note the behavior seen in the video above

* WooCommerce 4.6.1
* Atomic Site
* Gutenberg 9.1.1 installed and active.

**Comment by octaedro** [comment]
Thank you for the bug report @timmyc. It looks like this is an issue that only happens when `Gutenberg` is installed.
In the gif you shared, I could see another odd thing: the panel is loading an order with `Pending payment` status on a hard refresh. Since the [default actionable statuses](https://github.com/woocommerce/woocommerce-admin/blob/main/client/analytics/settings/config.js#L15) are `pending` and `on hold`, the orders with status `Pending payment` shouldn't be visible.

**Comment by timmyc** [comment]
@octaedro oh good catch that this is only happening with Gutenberg.

My site has Pending Payment as actionable, so that is working as expected. After recording the above, I adjusted the actionable statuses and confirmed it is working too.
