### ISSUE TITLE
Some navigation items missing due to duplicate IDs

### ISSUE THREAD

**Issue by joelclimbsthings** [woocommerce/woocommerce-admin#5626]
**Describe the bug**

@elizaan36 pointed out that the "Products" item is missing from the "Settings" category in [another PR](https://github.com/woocommerce/woocommerce-admin/issues/5572#issuecomment-726889677). It looks like this is actually due to conflicting IDs, an issue that could also easily cause issues elsewhere. 

We need to rethink a bit how these IDs are generated to prevent these kinds of conflicts. 

**To Reproduce**

1. Ensure the new navigation is enabled
2. Navigate to WooCommerce -> Settings
3. Observe that the "Products" item is no longer present

**Expected behavior**
All expected items should be present.

**Comment by elizaan36** [comment]
hey @joelclimbsthings , I noticed that another page is missing: *WooCommerce > Analytics > Settings*

Existing page in *WooCommerce > Analytics > Settings*
<img width="1375" alt="Screen Shot 2020-11-19 at 10 18 15 AM" src="https://user-images.githubusercontent.com/5121465/99693142-a93c8c80-2a50-11eb-9567-a014547f4d84.png">

Not showing in the new nav:
<img width="1509" alt="Screen Shot 2020-11-19 at 10 18 34 AM" src="https://user-images.githubusercontent.com/5121465/99693182-b35e8b00-2a50-11eb-8b07-7caf6e617408.png">

Could this be because of the same Duplicate ID reason? (Not to mention that this page should probably be located in *WooCommerce > Settings*, but that's for another day.)

**Comment by joelclimbsthings** [comment]
Morning @elizaan36 , on the latest I'm actually seeing that that page _is_ located under **WooCommerce > Settings > Analytics**; is that not what you're seeing? 

![image](https://user-images.githubusercontent.com/444632/99694504-5d361b80-2a41-11eb-87d7-b99b62b43115.png)

**Comment by elizaan36** [comment]
Oh yeah, I see it there! Sorry for the noise, I missed that somehow.
