### ISSUE TITLE
Unread indication for Inbox messages

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#5627]
In the latest release (since we removed the last Read/Unread functionality), there's no indication of which Inbox notifications have been viewed. This is an update so that merchants will understand what's new in their Inbox. The indication could also be encouragement to open the message and see what it's all about.

**Describe the solution you'd like**
A simple blue dot (directly to the left of the time stamp) upon first page load to indicate messages that have arrived since the user was last on the Home screen.

![Home - Unread indication](https://user-images.githubusercontent.com/5121465/99109264-28901300-25ae-11eb-8731-d6511693b6ba.png)

Once the message has been actioned on or the user navigates away, the dot disappears.

All designs are in the Home screen Figma, let me know if this needs any clarification.

**Comment by louwie17** [comment]
> The visual cue could be displayed only when a message is loaded for the first time in the home screen (tbd)

@samueljseay the above is from here: https://github.com/woocommerce/woocommerce-admin/issues/5247#issuecomment-713219245, how do you foresee we do this? I didn't see someplace where we might be doing something similar (might of missed it).

Otherwise I assume we could go about it two ways:
- Do we have a 'last visit date per page'? if so we can do: unread = note created > last visit date (just in our JS code) this won't work very well for the `inbox` panel on the other screens.
- Add a `read` property to the Notes class, that defaults to `false`. When the home screen gets loaded we trigger an update for any Notes that have unread as `false`.

The latter might be better for more control, and if we wanted to toggle the read state.
cc @jeffstieler @octaedro for any more insights?

**Comment by pmcpinto** [comment]
@samueljseay @louwie17 have you already established the best way to proceed in this? Lmk if you have questions.

**Comment by louwie17** [comment]
No, we hadn't talked about it further I had left it after the above comment.
Although since then I did notice we have a `activity_panel_inbox_last_read` user meta field that gets updated every-time the Inbox panel is rendered (which gets rendered on the home screen).
So we could continue using that approach, as most of the logic is already present (unread = date created > activity_panel_inbox_last_read).

**Comment by pmcpinto** [comment]
> So we could continue using that approach, as most of the logic is already present (unread = date created > activity_panel_inbox_last_read).

@louwie17 👍  sounds good to me
