### ISSUE TITLE
JS console warning when Gutenberg is activated

### ISSUE THREAD

**Issue by octaedro** [woocommerce/woocommerce-admin#5652]
**Describe the bug**
There is a console warning when `Gutenberg` is activated.
```
Warning: Cannot update a component (`DisplayOptions`) while rendering a different component (`Unknown`). To locate the bad setState() call inside `Unknown`, follow the stack trace as described in https://fb.me/setstate-in-render
    in Unknown (created by Controller)
    in Suspense (created by Controller)
    in Controller (created by _Layout)
    in div (created by _Layout)
    in div (created by PrimaryLayout)
    in PrimaryLayout (created by _Layout)
    in div (created by _Layout)
    in _Layout
    in Unknown (created by WithSelect(_Layout))
    in WithSelect(_Layout)
    in Unknown (created by Context.Consumer)
    in Route (created by _PageLayout)
    in Switch (created by _PageLayout)
    in Router (created by _PageLayout)
    in _PageLayout
    in Unknown
    in Unknown
    in Unknown
    in Unknown
```

**To Reproduce**

1. Go to `Home` screen.
2. The console warning will be visible. 

**Expected behavior**
No console warning.

**Screenshots**
<img width="1330" alt="Captura de Pantalla 2020-11-17 a la(s) 10 19 35" src="https://user-images.githubusercontent.com/1314156/99394911-73679e80-28be-11eb-9f3f-f1c837c699f2.png">

**Desktop (please complete the following information):**

* OS: MacOs
* Browser chrome

**Comment by samueljseay** [comment]
Digging in to this I found the source of this is 

the `withOnboardingHydration` component. It does some setState calls in it's `useSelect` that interfere with rendering the component. 

relevant lines:

https://github.com/woocommerce/woocommerce-admin/blob/main/packages/data/src/onboarding/with-onboarding-hydration.js#L44

https://github.com/woocommerce/woocommerce-admin/blob/main/packages/data/src/onboarding/with-onboarding-hydration.js#L57

This component is iffy at best, and I think we should probably be using React's `<Context>` rather than using this approach, either way I think this might require significant refactoring or at least significant care taken to test and understand any changes made.
