### ISSUE TITLE
Typo in Variations Stats report

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce-admin#5674]
https://github.com/woocommerce/woocommerce-admin/blob/0af934cfe57923da0ce7f6d95714c138c1b253ec/src/API/Reports/Variations/Stats/DataStore.php#L37

The ID should be `variations_stats`, not `variatons_stats` (missing "i"). I don't know if you would need a PR for this minor glitch, so I just thought of reporting it for now.

**Comment by adrianduffell** [comment]
Hi @daigo75,
​
Thank you for taking the time to report the typo, we really appreciate it.

The`$context` value is used in filters. I think the fix will need to consider maintaining backwards compatibility and support possible usage of the typo in existing filters.

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

A PR isn't necessary but feel free to provide one if you are interested.

**Comment by daigo75** [comment]
@adrianduffell In my opinion, it would be worth fixing the typo sooner, rather than later.  The longer the typo lies around, the higher the number of customisations that use the wrong IDs will be.

I spent a significant amount of time trying to understand why several filters would not trigger, and the root cause was the wrong ID. I had written the filters by typing the ID manually, following the usual pattern of `products`, `products_stats`, `variations`, `variations_stats`, without going into the `DataStore` to see the actual value, so the mismatch  was not immediately obvious.

I already fixed my code to use the correct ID (it won't work with the typo), so I won't have to worry about it changing later. It could be worth pointing out that fix during the next press release. 🙂

**Comment by adrianduffell** [comment]
Thanks @daigo75 . I am glad you found a workaround to this. 

I think the fix will be to support both spellings, to ensure any previous usage of the typo in customizations will continue to work. With that in mind, a fix is not currently a priority for the next release. I agree though, it is worth fixing sooner rather than later 🙂

**Comment by jeffstieler** [comment]
@adrianduffell I started down the path of implement backwards compatible filters... and I'm not sure we're going to be able to ensure backwards compatibility that doesn't introduce it's own potential problems.

To "support both spellings" I'm not sure what option we have other than firing all the hooks twice, with each spelling of the `$context` variable. Userland filters that don't rely on the `$context` will likely perform their modifications twice, which may lead to broken queries or other unintended side effects.

I'm starting to think it's probably easier to just fix the typo here and deal with the potential fallout in new issues/bugs.

**Comment by adrianduffell** [comment]
@jeffstieler Thanks, I don't think I considered a filter not relying on `$context`. I agree, this would create other issues with firing the hooks twice.

I'm thinking that fixing the typo is the best way forward now too.

**Comment by daigo75** [comment]
Thanks @jeffstieler and @adrianduffell 👍
