### ISSUE TITLE
Add working example of adding columns to report, and including them in the export csv

### ISSUE THREAD

**Issue by bowenac** [woocommerce/woocommerce-admin#5677]
I have followed the sql-modification example and was able to add new columns to the orders report table. However now I'm trying to figure out how to get these new columns included in the downloaded report. Seems like this would be a pretty common/popular way of extending the reports. Some of the columns I have added are all from reportTableData... Customer Number, City, State, Zip etc.

I have followed this example but it does not appear to be working anymore, seems like an issue for others as well but there has not been a lot of communication on that.
https://github.com/woocommerce/woocommerce-admin/pull/5134

**Comment by joshuatf** [comment]
Hi @bowenac 👋 

#5134 was merged and should already be in the current version of WooCommerce Admin.  You can see a working example of adding columns to the exported CSV in this plugin - https://gist.github.com/becdetat/0de2f79672e768f4e72b43d7ab07e2e3

Feel free to ping me if you have any questions about that implementation or if it doesn't meet your needs.

**Comment by bowenac** [comment]
@joshuatf that is the example I followed and it's not working.

**Comment by joshuatf** [comment]
@bowenac Could you provide an example to the repo with those changes so I can take a look?

**Comment by bowenac** [comment]
@joshuatf it is currently on a private branch, but in the main plugin file even as a test manually specifying values to add to the orders report isn't working. Example code I am in the main plugin file. Let me know if you do really need to see it in a repo, and I can package it up into a public repo.

`/**
 * Add columns to export
 */
function ideal_living_export_colunns( $export_columns ) {
    $export_columns['city'] = 'City';

    return $export_columns;
}
function ideal_living_export_item( $export_item, $item ) {
    $export_item['city'] = 'Test';

    return $export_item;
}
add_filter( 'woocommerce_report_orders_export_columns', 'ideal_living_export_colunns');
add_filter( 'woocommerce_report_orders_prepare_export_item', 'ideal_living_export_item', 10, 2);`

**Comment by becdetat** [comment]
Hi @bowenac I've replied to you and the others having this issue here - https://github.com/woocommerce/woocommerce-admin/pull/5134#issuecomment-730147307.

It looks like although the original change making it possible to add columns to the CSV only applied to the CSV downloaded from the server, you've been thinking that it should also apply to the client-side generated CSV (which just uses the displayed data to generate a CSV). That's not the case. I've created a new feature request here #5688 to add the new columns to the client-side generated CSV.

Thanks for raising this issue.
