### ISSUE TITLE
Combined loading state on tax success task

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#5711]
**Describe the bug**
All three buttons in the tax success task show they're loading at the same time. (I tried to figure this out myself today but couldn't quite get there.)

**To Reproduce**
Open a new site with Jetpack connected and the task list on the home screen.

1. Click on 'Set up tax'
2. Click on 'Yes please'

**Expected behavior**
The loading state should only appear on the primary button, not on the two links. Any ideas for how to fix this?

**Screenshots**
![combined loading states](https://user-images.githubusercontent.com/5121465/99850158-7a9ede80-2b42-11eb-9403-65918b34eb63.gif)

**Comment by moon0326** [comment]
It looks like `isBusy` flag is also used for the links as well.

See: https://github.com/woocommerce/woocommerce-admin/blob/main/client/task-list/tasks/tax.js#L428

What's the expected behavior when a user clicks the link (not the primary button)? Should it have the loading state?

I will start working on it.

**Comment by elizaan36** [comment]
I think we can remove the `isBusy` flag for the tertiary links. Pretty sure the text links aren't meant to have any loading state.

**Comment by moon0326** [comment]
@elizaan36 Thank you! I will make a PR 👍
