### ISSUE TITLE
[GlobalStep - WooCommerce 4.8 RC 1]  "Two column layout" option fails to be highlighted (Border) upon selection.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#5741]
## Bug Description:
 "Two column layout" option fails to be highlighted (Border) upon selection.

## Environment:
Windows 10, macOS Catalina: v10.15.7 (19H15)
Browser: Chrome(Version 86.0.4240.75 (64-bit))
                 Firefox(Version 82.0)(64-bit)
                 Safari(Version 14.0)(15610.1.28.1.9, 15610)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Go to WooCommerce beta tester.
1. Switch version to 4.8 RC 1.
1. Go to WooCommerce->Home.
1. Now click on “Display “option.
1. Select Two column layout.
1. Observe that  "Two column layout" option fails to be highlighted (Border) upon selection.

## Actual Result:
 "Two column layout" option fails to be highlighted (Border) upon selection.

## Expected Result:
 "Two column layout" option should be highlighted (Border) upon selection.

## Artifacts:
![#5741](https://user-images.githubusercontent.com/41110392/100254182-fd230600-2f67-11eb-8d8f-826cde944526.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by moon0326** [comment]
Additional note: This bug also exists in the lower versions of WooCommerce.

The border is actually `box-shadow` and it's not specifically applied for the column selection. It's a global style as far as I can tell. I'm not sure if the design is intended or not.

Do we want to keep the visual effect (border) and fix the bug or remove it?

/cc @elizaan36

**Comment by elizaan36** [comment]
This is a known issue in Gutenberg and there's already [an issue created](https://github.com/WordPress/gutenberg/issues/26896) to move towards a fix. From what I understand, given the way that focus handling was implemented for this component it's not a trivial fix. 

We've decided to wait until the global component style is updated, but I agree it's quite awkward and will keep an eye on progress there.

**Comment by moon0326** [comment]
Thank you @elizaan36 for the clarification 👍

**Comment by joshuatf** [comment]
I think that https://github.com/WordPress/gutenberg/issues/26896 may be a slightly different issue, but Gutenberg uses the [focusOnMount prop](https://developer.wordpress.org/block-editor/components/popover/#focusonmount) for determining whether the focus should go to the first item (used in this case), the popover itself, or nothing.

I think the outline shows focus and doesn't necessarily need to start on the selected item.  Someone can correct me if I'm wrong on that, but this is also the behavior used for all blocks using similar components.

I think the current behavior is okay, but open to hearing any contradicting evidence.  Closing this issue since either way we would need to handle this upstream to allow focus outside the first element.
