### ISSUE TITLE
Setup Wizard - Close dialog hover text not showing in Chrome 86 or Safari 14.0.1

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce-admin#5749]
**Describe the bug**
The 'Close dialog` hover text is not showing in Chrome 86 or Safari 14.0.1.

**To Reproduce**

1. Go to the 'Store Details' step in the Setup Wizard.
2. Fill out the address form and click "Continue" (alternatively you can click the Skip setup store details link at the bottom) to trigger the "Build a better WooCommerce" modal.
3. Hover over the ✖️  icon and note that the "Close dialog" text doesn't show in Chrome or Safari.

**Expected behavior**
The hover text for the close button should show.

**Screenshots**
![image](https://user-images.githubusercontent.com/71906536/100390231-e246a500-2fec-11eb-921e-0874a0736cb9.png)
☝️  This screenshot is from FireFox 83 to help show the text. This isn't showing in Chrome 86 or Safari 14.0.1.

**Desktop (please complete the following information):**

* OS: macOS Big Sur
* Browser: Chrome; Safari
* Version: 86; 14.0.1

**Comment by adrianduffell** [comment]
Hi @zhongruige,
​
Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end using Chrome and Safari.

Like with #5751 ,This seems to affect all modals from the @wordpress/components package. This can be tested in isolation on the WordPress Components Storybook.
​
We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by zhongruige** [comment]
> Hi @zhongruige,
> ​
> Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end using Chrome and Safari.
> 
> Like with #5751 ,This seems to affect all modals from the @wordpress/components package. This can be tested in isolation on the WordPress Components Storybook.
> ​
> We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

Sounds good--thanks for the follow up!
