### ISSUE TITLE
Close dialog text bleeds off to the right edge in modals

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce-admin#5751]
**Describe the bug**
Close dialog hover text bleeds off to the right edge in modals, such as the "Build a better WooCommerce" modal and the paginated modal once you complete the Setup Wizard. This also adds scrollbars around the modal as it tries to resize to fix the hover text.

**To Reproduce**

1. Go to the 'Store Details' step in the Setup Wizard using Firefox.
2. Fill out the address form and click "Continue" (alternatively you can click the Skip setup store details link at the bottom) to trigger the "Build a better WooCommerce" modal.
3. Hover over the ✖️  icon and note that the "Close dialog" text bleeds off to the right side.

**Expected behavior**
The close dialog hover text should be visible within the bounds of the modal.

**Screenshots**
![image](https://user-images.githubusercontent.com/71906536/100390914-276bd680-2fef-11eb-9a38-7d0a69b0e365.png)

**Desktop (please complete the following information):**

* OS: macOS Big Sur
* Browser FireFox
* Version 83.0

Only tested in FireFox as this does not show on Chrome or Safari, see: https://github.com/woocommerce/woocommerce-admin/issues/5749

**Comment by adrianduffell** [comment]
Hi @joshguss,
​
Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end using Firefox.

This seems to affect all modals from the @wordpress/components package. This can be tested in isolation on the [WordPress Components Storybook](https://wordpress.github.io/gutenberg/?path=/story/components-modal--default).
​
We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by zhongruige** [comment]
> Hi @zhongruige,
> ​
> Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end using Firefox.
> 
> This seems to affect all modals from the @wordpress/components package. This can be tested in isolation on the [WordPress Components Storybook](https://wordpress.github.io/gutenberg/?path=/story/components-modal--default).
> ​
> We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

Thanks for following up!
