### ISSUE TITLE
CSV report does not get emailed

### ISSUE THREAD

**Issue by luboslives** [woocommerce/woocommerce-admin#5774]
**Describe the bug**
Hi, I've been generating monthly revenue reports for a client under **Analytics > Revenue**. Just one week ago I generated reports from January to October, and I would click the **Download** button and the CSV would be generated and I would download it. Today I tried to generate the report for November and it gave me the `'Your %s Report will be emailed to you.'` message.

From what I gathered from another Issue, it should not be emailing the report if the number of total rows is less than the number of rows displayed. Is that correct? ([Source](https://github.com/woocommerce/woocommerce-admin/blob/bc2e36539a6edc8c04df1a491ee6cc1fc80c4a10/client/analytics/components/report-table/index.js#L155)) In my case I've been displaying 50 results per page.

I've tried multiple times and in different browsers, but it's always choosing the email route instead of the instant download.

- I checked **Tools > Scheduled Actions** and it reports both `woocommerce_admin_report_export` and `woocommerce_admin_email_report_download_link` as being Completed.
- I checked my server logs for errors. Nothing related, nothing from ModSecurity.
- I checked my WAF log (Ninja Firewall) and nothing pertinent there either.
- I checked my email server's Quarantine section, where they hold potential spam, and no Report emails are to be found there.
- There are several people in the support forum with a similar problem in [this thread](https://wordpress.org/support/topic/revenue-report-download-email-fails/) that popped up in a Google search.
- All other outgoing emails are working fine.

I should note that I use SMTP for outgoing emails, and it uses vars I've defined in wp-config.php. From my functions.php file:

```
function my_mailer_use_SMTPS( $phpmailer ) {
	$phpmailer->isSMTP();     
	$phpmailer->Host = SMTP_HOST;
	$phpmailer->Port = SMTP_PORT;
	$phpmailer->SMTPSecure = SMTP_SECURE;
	$phpmailer->SMTPAuth = SMTP_AUTH;
	$phpmailer->Username = SMTP_USER;
	$phpmailer->Password = SMTP_PASS;
	$phpmailer->From     = SMTP_FROM;
	$phpmailer->FromName = SMTP_NAME;
}
add_action( 'phpmailer_init', 'my_mailer_use_SMTPS' );
```

I poked around the source code and it looks like your mail functions shouldn't be a problem but I'm no expert. Maybe there is a clash / priority issue here. Or maybe it has something to do with the initial choice to email the report instead of downloading the file?

**To Reproduce**

1. Go to `/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Frevenue&period=custom&compare=previous_year&before=2020-11-30&after=2020-11-01&per_page=50`
2. Click on 'Download'

**Expected behavior**
I was able to directly download all monthly reports up to October on Nov 23rd. None of them went the email route. I expected the same outcome today.

**Desktop (please complete the following information):**

* OS: macOS Mojave
* Browser: Firefox and Chrome

**Additional context**
Running WordPress 5.5.3 and WooCommerce 4.7.1

**Comment by becdetat** [comment]
Hi @luboslives. Unfortunately I don't know how much we can help you out with this as it seems like a configuration issue with your email settings rather than an issue with WooCommerce Admin - the email generated when the CSV is generated on the server is pretty solid and regularly used.

Is your server sending other emails, such as when orders are created?

**Comment by cgsmith** [comment]
I am running into a similar issue. It is happening just for November 1st, 2020 though. Is there a way to generate the SQL that this report should be generating?

The report for 11/2/2020 generates a CSV and downloads. 10/31/2020 generates a CSV and downloads. Anytime 11/1/2020 is included it prompts a message 'Emailing report' but nothing generates.

![image](https://user-images.githubusercontent.com/570018/104354918-8ddd8300-54cf-11eb-866b-04da89f884d7.png)

**Comment by luboslives** [comment]
@cgsmith I just tried generating my report from the 2nd to the 30th out of curiosity, but I still don't get the instant download or the generated email, so nothing's wrong with Nov 1st in particular on my end.

@becdetat sorry I haven't followed up on this issue. I recently noticed that my email server provider switched to a whole new system some time mid-2020 and this particular domain is still on the old system, which appears to not be sending a DKIM DNS record, which is supposed to work in concert with the DMARC record they recommended. So there might be some sort of domain ownership confirmation issues, but realistically every other email from the site gets sent out aside from one or two that I can remember in the last few months I've been using this setup.

If that's what is to blame for the emails not being sent, I'll find out soon enough when I transfer the domain's emails to the new system in the near future.

**Comment by cgsmith** [comment]
Is there a way to see what the query is for this so I can try to duplicate the issue or provide some SQL to see if anyone else can duplicate the issue?

**Comment by cgsmith** [comment]
Posted here as well: https://wordpress.org/support/topic/november-1st-showing-two-days-data-not-exporting/

Here are the pictures. Nov 1st, 2020 shows '2 days' in bottom and download button doesn't work. 

![image](https://user-images.githubusercontent.com/570018/104538341-4cd59380-55e1-11eb-8100-381cfda73f42.png)


Nov 2nd, 2020 shows '1 day' in bottom and button works.

![image](https://user-images.githubusercontent.com/570018/104538365-59f28280-55e1-11eb-8d59-c513862a442b.png)

I deleted orders one by one to narrow down the issue but it never went away.

**Comment by luboslives** [comment]
Some more details to report here – I simplified my reports by removing 3 columns (gross sales, returns and coupons) and I was able to get the direct download of a CSV for the month of December (which was going the email to purgatory route as well) _and_ for Nov 2-30, but not for Nov 1-30 so maybe there _is_ a glitch in the matrix with Nov 1st 2020.

I tried using Woocommerce > Status > Tools > Clear analytics cache, but that had no effect.

**Comment by becdetat** [comment]
@cgsmith 
> Is there a way to see what the query is for this so I can try to duplicate the issue or provide some SQL to see if anyone else can duplicate the issue?

You could try logging the value of `$this->interval_query->get_query_statement()` around here: https://github.com/woocommerce/woocommerce-admin/blob/main/src/API/Reports/Orders/Stats/DataStore.php#L382

**Comment by becdetat** [comment]
@luboslives 
> I was able to get the direct download of a CSV for the month of December (which was going the email to purgatory route as well) and for Nov 2-30, but not for Nov 1-30

When you say you weren't able to get the direct download for Nov 1-30, is it trying to email the CSV instead?

**Comment by luboslives** [comment]
> When you say you weren't able to get the direct download for Nov 1-30, is it trying to email the CSV instead?

Yes it's trying to email the CSV. Which then gets stuck in purgatory as mentioned earlier.

It could be an email misconfiguration as to why it never gets sent, but the strange thing is whatever is happening on Nov 1st that's dictating whether it should email the CSV or offer it as a direct download.

**Comment by JScott-MSI** [comment]
It's not just luboslives issue, same thing not receiving any email, no way to set what email address the report is being sent to, and the csv files being generated into the uploads folder only show the 1st 50 entries. Right now the download function is useless.

The email solution is a bad idea in the first place. As a store owner, complete reports should be downloadable immediately, not received sometime in the arbitrary future. If you're going to use the email route the email needs to be sent to the specific user requesting the report. If it's being sent to the site admin, then they would need to forward the email to whoever actually requested the report. Generating the report to the uploads folder doesn't help since no-one has access to the folder who might be requesting the report. I'm not understanding the logic behind this functionality at all.

**Comment by luboslives** [comment]
@JScott-MSI you've inadvertently added a knew wrinkle to this - I didn't know the CSVs get stored in the uploads folder, so I decided to take a look. The exported CSV for November did not include the column headers. 🤔

1. I downloaded the existing files in there to my local machine and then deleted them off the server.
2. I generated a new revenue report for December and it actually emailed it this time!
3. I generated a new revenue report for November and... it did not get emailed.
4. I grabbed it from the uploads folder and... it's missing the column headers.

**Comment by becdetat** [comment]
@luboslives 
> the strange thing is whatever is happening on Nov 1st that's dictating whether it should email the CSV or offer it as a direct download
The size of the table is what determines whether it gets emailed or directly downloaded. If it spills over two pages (which it would for a whole month with 25 rows per page selected) it gets emailed. So I'm not sure why 2-30 Nov would be available as a direct download.

**Comment by becdetat** [comment]
@JScott-MSI 
> As a store owner, complete reports should be downloadable immediately, not received sometime in the arbitrary future

Can you create a separate issue for this? It is something we should consider.

**Comment by becdetat** [comment]
@JScott-MSI 
> the csv files being generated into the uploads folder only show the 1st 50 entries

I don't know what would be causing this, in my local testing for two months worth of data in the Revenue report the email is sent and the CSV generated contains all of the data (62 lines including a header). Where is the data being truncated?

**Comment by johndcoy** [comment]
This appears to be similar to the issue reported and actively worked on and looked at here:

https://github.com/woocommerce/woocommerce-admin/issues/4483

**Comment by luboslives** [comment]
> @luboslives
> 
> > the strange thing is whatever is happening on Nov 1st that's dictating whether it should email the CSV or offer it as a direct download
> 
> The size of the table is what determines whether it gets emailed or directly downloaded. If it spills over two pages (which it would for a whole month with 25 rows per page selected) it gets emailed. So I'm not sure why 2-30 Nov would be available as a direct download.

@becdetat Thanks for the clarification on that – I was wondering if that was the case in my original post. So the problem with that is I'm displaying 50 rows, and it's choosing the email route instead of the download route. And like I mentioned the column headers don't actually get added to the CSV that's created in the uploads folder. Hopefully those two facts are clues as to where this bug might be generated or at least captured.

**Comment by timmyc** [comment]
I spent some time trying to reproduce this bug on a site running WooCommerce 4.9.x - and I was unable to encounter the bug myself. I also was given credentials to a site where the bug was happening, and wanted to share a few things I saw:

- Visiting the Scheduled Actions page under WooCommerce > Status ( `wp-admin/admin.php?page=wc-status&tab=action-scheduler` ) I noticed some jobs for email export, hook name `woocommerce_admin_report_export` were failing due to timing out.
- I noticed that some of the date ranges attached to those exports were for a long period of time, like a full year's worth of data.

Using those clues, I then opted to try exporting a smaller date range from the Revenue Report of 2 months, and I was able to get a correct csv export + email.

A few items to note about the background job processing which could result in a state where a large report export might time out and fail, this info is via the [ActionScheduler documentaiton](https://actionscheduler.org/perf/).

> By default, Action Scheduler will only process actions for a maximum of 30 seconds in each request. This time limit minimises the risk of a script timeout on unknown hosting environments, some of which enforce 30 second timeouts.

ActionScheduler does provide a filter to increase this time limit ( `action_scheduler_queue_runner_time_limit` ), and on the documentation page linked above even gives some known timeouts for web requests on some popular WP hosts for guidance. When in doubt, I would say it might be good to contact your host to see what the timeout threshold is on http requests for your plan.

For high volume sites, ActionScheduler recommends using `wp-cli` to process the job queues to eliminate the bottleneck of http timeouts too.

## Some Troubleshooting Steps

As it has been mentioned on this thread, the background processing of CSV exports is only triggered when your data set in the report table exceeds a single page of results. When the data set fits on one page, the logic will take the data displayed in the table, and allow for immediate csv download. So with that knowledge in hand, some steps I would encourage users to try is:

- Reducing the number of results you are trying to export. For example, instead of attempting to export an entire year's worth of data, try to do a few months first. You can then use the `rows per page` option in the Table footer to bump the rows displayed to 100, and can then download 2 months worth of data at a time directly from the browser.

<img width="745" alt="rows-per-page" src="https://user-images.githubusercontent.com/22080/105538742-ba03bb80-5ca8-11eb-8ad4-ba0280141654.png">

- If exporting smaller date ranges is not acceptable, please look at the Scheduled Actions page `wp-admin/admin.php?page=wc-status&tab=action-scheduler` for jobs entitled `woocommerce_admin_report_export`. If a job fails to run, the output will be logged there. That could yield further clues to see if the request is timing out, or perhaps there might be a fatal error happening during the export.

**Comment by louwie17** [comment]
Just following up here, @luboslives are you still encountering this bug? and if so are you seeing time out tasks as @timmyc mentioned above?

**Comment by luboslives** [comment]
> Just following up here, @luboslives are you still encountering this bug? and if so are you seeing time out tasks as @timmyc mentioned above?

I have something new to report, yes. The site owner wanted the Nov 2020 report to look like all the other CSVs so I tried again.

Again the problem is with Nov 1st itself. What I did was export Nov 2-30th as its own CSV – no problems. Then I did Nov 1st & 2nd so I could see how the output differs. I'll just post it here so you can see for yourself.

**Correct CSV output (Nov 2-30):**

```
Date,Orders,"Gross Sales",Returns,Coupons,"Net Sales",Taxes,Shipping,"Total Sales"
"2020-11-30 00:00:00",5,228,0,5.5,222.5,0,124.5,347
...
"2020-11-02 00:00:00",2,69,0,10.5,58.5,8.47,25.9,92.87
```

**Mangled output from Nov 1-2:**

_Header row is missing!_

```
"2020-11-02 00:00:00",2,92.87,0.00,10.50,8.47,25.90,58.50
"2020-11-01 00:00:00",1,22.18,0.00,0.00,2.08,4.10,16.00
```

So, check out these differences in output:

- the order of rows is incorrect
- numbers are not rounded down
- the header row is missing

**A comparison of Nov 2nd in the correct output (line 1) and the mangled output (line 2):**

```
"2020-11-02 00:00:00",2,69,0,10.5,58.5,8.47,25.9,92.87
"2020-11-02 00:00:00",2,92.87,0.00,10.50,8.47,25.90,58.50
```

Hopefully this can help you.

As I've mentioned a few times, I have it set to display 50 items so I can cover all days in a month. So by its own logic it should not be attempting to email the CSV, but it does every time for Nov 2020. Previously I had looked into scheduled actions and they were reported as completed.

**Comment by louwie17** [comment]
@luboslives thanks for replying with the update, and sorry to hear that the issue is still happening. I left some extra questions below, I hope there is no duplicates from what has been asked before, this certainly seems to be a tricky one.

> Again the problem is with Nov 1st itself. What I did was export Nov 2-30th as its own CSV – no problems. Then I did Nov 1st & 2nd so I could see how the output differs. I'll just post it here so you can see for yourself.

Thanks for adding the examples, I am also perplexed on why the issue is with Nov 1st. I see from your example there was just one order on that day? is there anything unique about that order and does it display fine within the table?

The fact that the column's are in a different order is also strange, on our end we use a static list for the columns (when generated by email), but it does get run through a filter. Could an external plugin be changing these?

The header gets added at the end of the process, when it parsed all the rows, so an error of some sorts could have happened that caused it to not be added. Does anything show up in the logs? 
It could be worth trying it with a smaller batch size:
`add_filter( "woocommerce_admin_revenue_report_export_batch_limit", function() { return 10; } );` (default is 50).

**Comment by louwie17** [comment]
@JScott-MSI we appreciate your input and concern about the download functionality.
One of the reasons we decided to go the route of batching the export process and emailing it, is because not every machine WooCommerce is run on can handle large data sets and/or has little memory to work with.
That being said we can certainly improve upon our current flow.

I will create an issue to explore moving away from the email-based export to a more streamlined approach.

**Comment by becdetat** [comment]
@luboslives Great catch :-). Please let us know if the problem appears again. Otherwise we will leave this issue as closed.

**Comment by jaimyborgman** [comment]
Somehow i've got the same problem, all other reports generated which will be e-mailed are mailed to me. But for the revenue I see tasks coming into the background (3) and nothing is being mailed. Is there already a solution for this? It btw looks like it broke after an update or maybe its using a wrong mail provider? If for instance its using phpmail directly it will not work. But I don't think so since other reports are being sent.

Not sure where to look for at this moment but will troubleshoot further; it looks like it only isn't working for revenue a few months ago (a quarter) it worked however.

**Comment by becdetat** [comment]
> or maybe its using a wrong mail provider? If for instance its using phpmail directly it will not work

Sorry @jaimyborgman , I'm not sure I understand this fully. Are you saying that if you don't use phpmail is _does_ work?
