### ISSUE TITLE
WooCommerce 4.8.0-rc.1: cannot save plugins with WP beta 5.5.4

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce-admin#5805]
After upgrading to WooCommerce 4.8.0-rc.1 I cannot activate other plugins. The error message on screen is:

```
Deprecated: Automattic\WooCommerce\Admin\Notes\WC_Admin_Note::set_status is deprecated since version 1.7.0 with no alternative available. in [...]wp-includes/functions.php on line 4783

Deprecated: Automattic\WooCommerce\Admin\Notes\WC_Admin_Note::save is deprecated since version 1.7.0 with no alternative available. in [...]/wp-includes/functions.php on line 4783
```

Rolling WooCommerce back to 4.7.1 fixes the error. 

This is on WordPress multsite, with WordPress BETA testing activated, version 5.5.4-alpha-49501.

**Comment by joshuatf** [comment]
>I suppose this is a PHP Notice displayed with DEBUG enabled only. The same things applies to WC Payments or probably any plugin using WC_Admin_Note.

I believe this is the case.  Those deprecation notices aren't errors, but are intentional warnings to plugin authors to help them update used methods to the newer versions.  They should continue to work for a few versions and will only be shown when debugging is enabled.

Please let me know if you're still seeing any errors or something preventing you from activating plugins @EdithAllison and we can take another look.

**Comment by EdithAllison** [comment]
Hi @joshuatf For me this issue can be closed, I understand it's a deprecation warning which only causes an issue when debug messages are being shown (dev site), happy to have this closed down.

**Comment by joshuatf** [comment]
Thanks for the update, @EdithAllison!  Will close this issue.
