### ISSUE TITLE
Navigation: Inbox message to inform users of the Nav

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5813]
Create an inbox message to inform users of the new Navigation.

### Deliverables

* Create a notification
* Apply correct copy (@pmcpinto for wording)
* Add only for eComm plan users
* Decide if this should live in wc-calypso-bridge

**Comment by pmcpinto** [comment]
@psealock we're thinking about reframing one of the inbox messages that was created in #5334 instead of creating a new one.

Our idea is to change the one that's supposed to be triggered immediately upon rollout:
> Headline: You now have access to the new WooCommerce navigation
> Body: We're introducing the new navigation for a more intuitive and improved user experience. We'd like to hear your thoughts and first impressions.
> CTA: [Share feedback] https://automattic.survey.fm/new-navigation

The new copy is:

Headline: Welcome your new WooCommerce Navigation
Body: Introducing a streamlined, commerce-first navigation experience, to help you save time and find the things that matter.
CTA: Learn more (this is going to link to a support doc with more info about the changes)

Sounds good?

**Comment by psealock** [comment]
This has been addressed in wc-calypso-bridge
