### ISSUE TITLE
Navigation: Importer defaults to All products

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5927]
When running the Importer, All Products is the active Nav item.

<img width="1151" alt="Screen Shot 2020-12-22 at 1 54 22 PM" src="https://user-images.githubusercontent.com/1922453/102836134-70337580-445d-11eb-8202-fb519ab8bb47.png">

Should the product importer:

* Keep Tools > Import/Export as active?
* Have its own Nav item under Products?
* Or stay with All Products?

### Steps to Reproduce

1. WooCommerce > Tools > Import / Export
2. Choose WooCommerce CSV Importer

cc @elizaan36

**Comment by elizaan36** [comment]
> Or stay with All Products?

I'd stay with All products since that's where the products will import to. Would make sense to stay in All products once they're successfully imported from there.

The only thing that might be weird is there's also the product importer from the Home screen task list that navigates back to the Home screen after import. That makes sense since we want people to continue the setup process. 

What do you think?

**Comment by psealock** [comment]
>Would make sense to stay in All products once they're successfully imported from there.

I just confirmed this is the case

>I'd stay with All products since that's where the products will import to

Cool, thanks for the input. I'll go ahead and close this issue.
