### ISSUE TITLE
[WC 4.9 RC2] `Setup additional payment providers` card doesn't work

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-admin#6023]
**Describe the bug**

Happens on both Atomic and JN sites. Clicking on the button `Setup payments` in the `Setup additional payment providers` card reloads the page without redirecting the user to set up payments. 

**To Reproduce**

1. Create a brand new Atomic or JN site with WC 4.9 RC2 build. 
2. Complete onboarding with US address, the fashion industry, and installation of all the free business plugins. 
3. Complete all tasks on the Home screen and hide the task list. 
4. Try clicking on the button `Setup payments` in the `Setup additional payment providers` card.
5. Note that the page reloads without redirecting the user to set up payments. 

![http://g.recordit.co/XCY2Mz2TzW.gif](http://g.recordit.co/XCY2Mz2TzW.gif)

**Expected behavior**

I expected to be taken to the payments set up page (`WooCommerce/Settings/Payments`) when clicking on the button `Setup payments` in the `Setup additional payment providers` card.

**Screenshots**

See gif above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome
* Version: 87.0.4280.88 (Official Build) (x86_64)

**Additional context**

N/A

**Comment by juliaamosova** [comment]
JN site:

![](http://g.recordit.co/oOemlPovQe.gif)

**Comment by moon0326** [comment]
So the issue is that we don't render the payment task component if `woocommerce_task_list_hidden` is set to `yes`. You can see the code [here](https://github.com/woocommerce/woocommerce-admin/blob/45c0ae9103753eb5c2b7de6ab42254267fd81b24/client/task-list/index.js#L130).

I think we have two options.

1. Display the task components regardless of `woocommerce_task_list_hidden` value. I think users should be able to perform the task even after hiding the task list.

2. Remove the note when the user hides the "Finish setup" panel.

cc @timmyc and @pmcpinto

**Comment by timmyc** [comment]
Great sleuthing @moon0326 - I think we could consider a potential third option here, where if the payments task URL is accessed, but the payments task has been hidden, we then do a page redirect to the Settings > Payments page instead.

Pedro is probably offline until tomorrow at this point, so I think we should ready a PR for option #1 above though, and test it out a bit to ensure no other possible regressions can occur with this logic. The main reason I think we should still direct the to the payments task is it will allow the featured payment extensions for their locale to appear again.

**Comment by moon0326** [comment]
@timmyc Thank you. That's a good idea. In the meantime, I will make a PR for option #1.
