### ISSUE TITLE
Add @woocommerce/blocks-checkout to dependency extraction

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-admin#6025]
WooCommerce Blocks released a new package `@woocommerce/blocks-checkout` that exports checkout related components.
Taking from woo dependency extraction docs, it would be extracted automatically (under the `@woocommerce/$1 -> wc-$1 -> wc["$1"]`) but it didn't.
I tried to add it to `packages/dependency-extraction-webpack-plugin/assets/packages.js` but it seems that file is ignored and I'm not sure where is it being generated or how is it generated, so I can't make a PR, just an issue.

`@woocommerce/blocks-checkout` has a wp handle of `wc-blocks-checkout` and is exposed under `wc` in `blocksCheckout`.

cc @psealock

**Comment by psealock** [comment]
Thanks @senadir 

>`@woocommerce/blocks-checkout` has a wp handle of `wc-blocks-checkout` and is exposed under wc in `blocksCheckout`.

That all checks out according to the established pattern, so there is another issue.

`packages/dependency-extraction-webpack-plugin/assets/packages.js` is not under version control because it is a file generated by webpack. I think a note added to the file would avoid confusion, sorry about that.

That file is generated here from packages included in wc-admin.

https://github.com/woocommerce/woocommerce-admin/blob/8b34c29abca0bb1b65adddd5834aa4ce69d85862/bin/packages/build.js#L223

So the problem is that Blocks packages will never make it on the list 😞. This is a symptom of multiple packages in different repos. We could hard code the Blocks package names in the `buildDependencyExtractionAssets` function, but that is less than ideal. We could check out the code somehow and iterate from there. Any thoughts?

**Comment by psealock** [comment]
Another alternative is to keep a hard coded list of all the packages we support, including those from Blocks. Do you think we can maintain it without issue?

**Comment by senadir** [comment]
I think that would be a good low effort solution, I don't think WCBlocks or WC admin is pumping out packages this fast so this file would be low maintenance and wouldn't require an over the top build process.
I actually came back because I also needed to add `@woocommerce/block-settings` aliased to `wcSettings`.
