### ISSUE TITLE
New WooCommerce Navigation: Issues accessing new nav on mobile, cannot easily access WooCocommerce pages in general

### ISSUE THREAD

**Issue by JoshuaGoode** [woocommerce/woocommerce-admin#6079]
**Describe the bug**
Users accessing their WP-Admin via a mobile browser are having issues accessing the new nav.  

Clicking `WooCommerce` doesn't take the user to the new nav. Instead, it just expands and displays Reports which also doesn't lead to the new nav.

Navigating directly to `/wp-admin/admin.php?page=wc-admin` works.

**To Reproduce**

1. Visit a site's WP-Admin in a mobile browser or inspect at mobile screen dimensions using browser dev tools
2. WooCommerce on the left-hand WP-Admin menu.
3. See error

**Expected behavior**
Clicking WooCommerce should direct the mobile user to `/wp-admin/admin.php?page=wc-admin` 

**Screenshots**
Attempting to click WooCommerce just expands the WP-Admin button, does not direct to new nav. 

![image](https://user-images.githubusercontent.com/4887830/104763199-87e7dc00-5733-11eb-8aff-6b50caaccf34.png)

**Additional context**
Discussed internally:  p1610734272050600-slack-C9K5T0XSP

**Comment by timmyc** [comment]
So I think the clicking of a top-level menu item in wp-admin not triggering a navigation action is by design. At least when I use wp-admin on my Pixel 5 with mobile Chrome, any top-level menu item click only expands the navigation section and does not trigger a page load.

As such, I think the proper fix here is the maybe display the "Home" menu item under the WooCommerce menu in the narrow viewport, and the click on "Home" would then trigger the navigation. Seems like we should honor the existing mobile pattern in wp-admin in this way, but keen to hear @elizaan36 thoughts on the topic too.

**Comment by JoshuaGoode** [comment]
Sounds good.

However, that's a bit different than the desktop navigation which doesn't expand anything and goes /wp-admin/admin.php?page=wc-admin` to when clicked.

![image](https://user-images.githubusercontent.com/4887830/104775805-fa15ec00-5746-11eb-8af7-faaac6ba3df6.png)

**Comment by elizaan36** [comment]
Thanks for flagging this @JoshuaGoode 

> As such, I think the proper fix here is the maybe display the "Home" menu item under the WooCommerce menu in the narrow viewport, and the click on "Home" would then trigger the navigation. Seems like we should honor the existing mobile pattern in wp-admin in this way, but keen to hear @elizaan36 thoughts on the topic too.

Yep, that's the current pattern on wp-admin and I agree we should stick to it for the WooCommerce subnav, especially since we'd like to preserve the flyout (full subnav access) in the near future.

Ideally clicking or tapping `WooCommerce` in the nav would expand the full submenu on smaller screen sizes. But if we could start with `Home` as you suggested that would be a great step forward from here.

**Comment by nagpai** [comment]
Came up in a user report 
26084260-hc
