### ISSUE TITLE
Missing option to enable Setup task list

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#6087]
**Describe the bug**
Once the setup task list is dismissed, there's no option to Enable it again. In Settings > General > Help (accordion) > Setup wizard, only the `Disable` action shows even when the task list is already dismissed.

**To Reproduce**

1. Go to Settings > General > Help (accordion) > Setup wizard
2. Click on `Disable`
3. Go back to Settings > General > Help (accordion) > Setup wizard
4. See error (Action still shows as `Disable`)

**Expected behavior**
The action should say `Enable` when the task list is dismissed, and allow the user to enable the task list.

**Screenshots**
[GIF showing issue](https://share.getcloudapp.com/YEuQxdWb)

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/5121465/104937481-6ecd6e00-5973-11eb-9ccf-42b0bd7b93a6.png">

**Comment by octaedro** [comment]
Hi @elizaan36,
Nice catch! I added the fix for this issue in the [PR 6081](https://github.com/woocommerce/woocommerce-admin/pull/6081). This is an issue related to having 2 different task lists (the extended and the core list) but only one button to Enable/Disable them. In the PR a new button will be added in order to have 2 different enabling buttons (one per task list).

**Comment by elizaan36** [comment]
oh thanks Fer, that makes sense.
