### ISSUE TITLE
Main branch does not pass linters/pre-commit making it impossible to merge

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#6133]
## **Describe the bug**
`main` branch does not pass linters defined in `pre-commit` hook. This makes it impossible to merge the `main` branch to any PR branch. (without `--no-verify`)

## **To Reproduce, case 1**

1. Create and checkout any branch (like `git co fix/5925-summarynumber-float`)
2. Try merging `maint` into it: `git merge main`
3. Resolve the conflict if any, and `git commit`

## **Expected behavior, case 1**
If the conflict resolution brings no new errors, `pre-commit` should pass.

## **To Reproduce, case 2**

1. Clone the repo `git clone git@github.com:woocommerce/woocommerce-admin.git`
2. Install it `npm install && composer install`
2. Run linters `npm run lint`

## **Expected behavior, case 2**
The fresh clone should pass its linters.

![image](https://user-images.githubusercontent.com/17435/105391038-fe944600-5c19-11eb-94af-fbf59199ec01.png)

**Comment by samueljseay** [comment]
Thanks @tomalec I don't think there is anything wrong with the checks themselves, but it looks like we're incorrectly linting generated files from storybook so it shouldn't fail here since those files are gitignored. 

As a general tip I personally do just use `--no-verify` a lot anyway because things will get caught in CI and although the hooks have been sped up its still time consuming (and usually fairly pointless) for them to run on merge.
