### ISSUE TITLE
Admin toolbar is hidden by the new Navigation

### ISSUE THREAD

**Issue by tivnet** [woocommerce/woocommerce-admin#6162]
The new admin.php?page=wc-admin completely hides the admin toolbar. Important stuff such as debug bar are hidden. Very inconvenient.

**Comment by joshuatf** [comment]
@tivnet I'm able to reproduce the issue when the new WooCommerce navigation is enabled and visiting a WooCommerce page.

<img width="553" alt="Screen Shot 2021-01-25 at 5 51 17 PM" src="https://user-images.githubusercontent.com/10561050/105776118-0152ac00-5f36-11eb-9b7b-ce55d9e68c67.png">

With the navigation turned off, I can see the admin bar.

<img width="389" alt="Screen Shot 2021-01-25 at 5 51 43 PM" src="https://user-images.githubusercontent.com/10561050/105776136-09aae700-5f36-11eb-9960-ca72d58bbb39.png">

Are you expecting to see the admin bar on the new WooCommerce pages?  The admin bar and admin menu were intentionally removed from these pages since those contain links pertaining to the rest of the dashboard, though I know some plugins take advantage of them for other information.

I'm wondering if we possibly use a filter or constant here (`WP_DEBUG` or most likely a new one) to show this bar on WooCommerce pages.  Any thoughts?  @elizaan36 @psealock @joelclimbsthings

**Comment by tivnet** [comment]
Yes, @joshuatf, seeing the bar is a Good Thing. Not only for development (debug notifications) but for many other things. The bar is there for a reason :) What's wrong if the links there lead away from Woo navigation?

**Comment by joshuatf** [comment]
>What's wrong if the links there lead away from Woo navigation?

I'm not the designer behind it, but I believe the intent is to create a separate dashboard that is decluttered and simplified from the original WP dashboard.

I'll let @elizaan36 share her viewpoints on this though.

>Not only for development (debug notifications) but for many other things.

I understand that certain plugins like https://wordpress.org/plugins/debug-bar/ add in some level of debugging to the admin bar, though this is not the original functionality behind the admin bar; it is primarily used to navigate around the WP dashboard.

I can see how allowing it may be useful though, so I'm not opposed to creating some kind of filter to enable it in the new WooCommerce Navigation experience.

Can you speak to the many other benefits of having the WP admin bar on these pages?

**Comment by tivnet** [comment]
@joshuatf 

Standard WP:
- Visit site/store
- New ...
Plugins:
- Debug Bar
- Query Monitor
- Language switchers (WMPL, WPGlobus, etc.)

P.S. And just the ability to navigate quickly to any WP w/o first clicking the "WordPress Dashboard" link - that's a general "con" of the new Navigation, in my opinion. Especially when you two levels down, you have two clicks to go back to the regular WP admin.

**Comment by tivnet** [comment]
Oh, yes, the standard WP sidebar can be collapsed.

**Comment by elizaan36** [comment]
hey @tivnet, thanks so much for creating this issue. It's really good for us to hear your perspective on the wp-admin toolbar as we iterate on the new navigation. This is a beta feature so any input is valuable as our team works on ways to improve it.

As @joshuatf mentioned, hiding the toolbar is intentional allow for better focus on all things Woo, but can see how this would be frustrating for you since it sounds like your workflow heavily relies on this toolbar even when you're working within Woo. I'm sorry for the inconvenience this has caused you. I think the filter idea is a good one and I could see it being useful to have something like a builder mode within the new nav.

A couple things you can do in the meantime:
- If you haven't discovered it already, there's a way to disable the new navigation so you can have access to the wp-admin toolbar again. Go to **WooCommerce > Settings > Advanced > Features** and uncheck the box. After saving and refreshing the page, you'll be back to the wp-admin nav.
- If it's not too much trouble, share your email [in the survey here](http://automattic.survey.fm/new-navigation) and we may reach out to you for more details and a screenshare to learn more about your workflow.

I know that's probably not the best answer but we appreciate your perspective and hope to have a better solution for you asap.

**Comment by joshuatf** [comment]
For this issue, we'll look at showing the admin bar on WooCommerce dashboard pages via a filter `woocommerce_admin_navigation_show_adminbar` that should default to `false`.

As a note, we should be cautious with how we set the heights and position of the navigation alongside other issues like https://github.com/woocommerce/woocommerce-admin/issues/5459 that may affect where the navigation and header should sit in these scenarios.

**Comment by joshuatf** [comment]
Estimate: 2

This will also play into all the other header height issues we've experienced so we should probably work together to come up with a better way to avoid these issues going forward.

**Comment by tivnet** [comment]
May I ask a simple question: why all this? Woo is an integrated part of WP. Why to have a separate navigation? "Less clutter"? It's not less, especially if you return the bar back. More clicks - yes, you achieved that, thank you!
I am only using it because I develop Woo extensions. Otherwise - surely back to the regular navigation.

**Comment by joshuatf** [comment]
@tivnet Because while you and I have learned where menu items are over years of experience, we've learned this is not the case for new users.  Just because we know where items are from experience does not make the old design intuitive.

In testing, the new navigation design performed well which is why we decided to give it a shot.  It may not be the best iteration of the design and we may continue to tweak it going forward or it's always possible we remove it entirely, but in order to improve we have to iterate and test new features.  The new design is much more opinionated which is why it's behind a feature flag that can be toggled on or off.

We appreciate your feedback on this and I recommend, if you have a moment, to complete the survey above.  The survey is probably a better medium to voice your concerns than Github, which we primarily used for handling bugs and feature requests.

**Comment by joelclimbsthings** [comment]
> Oh, yes, the standard WP sidebar can be collapsed.

Just wanted to mention @tivnet , you can collapse the new navigation by clicking on the logo in the top-left corner.

**Comment by tivnet** [comment]
@joelclimbsthings Thank you!

**Comment by joshuatf** [comment]
As a heads up to whoever grabs this issue: make sure we have a decision on https://github.com/woocommerce/woocommerce-admin/pull/6247 before working on this filter.

**Comment by tivnet** [comment]
For reference:

```
if ( apply_filters( 'woocommerce_navigation_wp_toolbar_disabled', true ) ) {
				$classes .= ' is-wp-toolbar-disabled';
			}
```
