### ISSUE TITLE
Extensibility: Compare report periods to future periods

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6171]
See report in https://developer.woocommerce.com/2021/01/15/call-to-action-create-access-for-your-extension-in-the-new-woocommerce-navigation/#comment-8269

Investigate if Reports can be compared to a future period (or any period) populated by data fetched from alternate endpoint.

## UI Extensions

This dropdown would need to accept custom buttons

<img width="347" alt="Screen Shot 2021-01-25 at 4 41 07 PM" src="https://user-images.githubusercontent.com/1922453/105658816-35c16a80-5f2c-11eb-9ecc-73c710b831c8.png">

## API

I'm not sure what would be involved here. Can our API accept future or arbitrary parameters? If so, can a different query be executed because past data wouldn't be queried but rather some other data table. Also, can additional query parameters for products or advanced filters be passed as well?

**Comment by jakevoelcker** [comment]
Hi psealock, thanks for opening an issue for this.

## UI Extensions
What I have in mind is something like this
<img src="https://user-images.githubusercontent.com/77966855/105697482-8325e380-5efc-11eb-9af4-228e22be879e.png" width="350" />

## API
To keep things simple to start with, for my use a single sales target would be sufficient. Instead of being a new table of future data, it could simply be a single field stored as a setting 
<img src="https://user-images.githubusercontent.com/77966855/105697733-d9932200-5efc-11eb-81cf-75baf43da870.png" width="350" />

(Future development could then include adding more granular sales targets for different future dates, products, categories etc. As you say, this could get quite complex and may require a new table. Or alternatively some way of creating dummy orders, but marking them as being targets rather than real sales).

## Questions
Where can I read about how the standard reports work? Is there any documentation available, other than the source code itself?

How extensible are the standard reports? Are there any hooks available, perhaps similar to the "woocommerce_admin_report_data" filter in the old reports?

**Comment by ilyasfoo** [comment]
Hi @jakevoelcker,

>Where can I read about how the standard reports work? Is there any documentation available, other than the source code itself?

We do have some documentation on how to extend reports here: https://github.com/woocommerce/woocommerce-admin/tree/main/client/analytics/report#extending-reports.

>How extensible are the standard reports? Are there any hooks available, perhaps similar to the "woocommerce_admin_report_data" filter in the old reports?

Unfortunately, we don't have a list of JavaScript filters readily available. If you're familiar with modern code editors like  VSCode, you can try to search for all `applyFilters(` under the path `./woocommerce-admin/client/analytics` to get all filters available like so:

![image](https://user-images.githubusercontent.com/3747241/109904468-478af000-7cd8-11eb-9ac4-f94cffcb4993.png)
