### ISSUE TITLE
Navigation: Toggle on/off from Homescreen

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6210]
For better discoverability of the new navigation, we can present a toggle in the Display dropdown on the Home screen. A new section appears in the Display dropdown called Enable. From there, merchants can quickly have access to the new nav when they need it, and turn it off if they need better access to other areas of WordPress.

![enabledisable](https://user-images.githubusercontent.com/1922453/106083632-af05cb00-6181-11eb-8b2b-e33c9ddfa73e.gif)

**Comment by pmcpinto** [comment]
@psealock in terms of tracking, we already have two events that are triggered when the user clicks in the display:
- `wcadmin_homescreen_display_click`: click in the display icon
- `wcadmin_homescreen_display_option`: click in one of the options
I think that it will be enough to just add `navigation` as a value in the `display` prop of `wcadmin_homescreen_display_option`. Do you agree?

One thing that we also need to consider is displaying the usage tracking modal here if they don't have tracking enabled cc @elizaan36

**Comment by joshuatf** [comment]
@psealock @pmcpinto Is this meant to be toggleable without a page refresh?  I think that would definitely be nice, but we may need to preload more of the nav feature in order to toggle on/off this way.

Estimate: 2 with current page refresh.
Estimate: 7 with toggle client-side.  Would need to preload data and build out the menu migrations in JS, though this might make things a bit easier with the flyout and other potential changes in the future 🤔

**Comment by elizaan36** [comment]
> One thing that we also need to consider is displaying the usage tracking modal here if they don't have tracking enabled cc @elizaan36

Ah yes, the usage tracking modal. I'll have a think about how to present that here! We could include a `Requires usage tracking` subcopy in the dropdown but that feels messy to me.

> Is this meant to be toggleable without a page refresh?

@joshuatf Yes this would only work without requiring a page refresh. If that's not possible I can explore other locations for the toggle that could include a "Save" action.

**Comment by pmcpinto** [comment]
> Estimate: 2 with current page refresh.

I'd go with the current page refresh and improve it in the future, depending on usage.

**Comment by joshuatf** [comment]
@elizaan36 This is most likely possible but we'll need to dive into it to be absolutely sure.  A dependency of this would be [this endpoint](https://github.com/woocommerce/woocommerce-admin/issues/6223) which it sounds more and more like we'll need.

I think this is worth investigating at the very least.

**Comment by timmyc** [comment]
From our sprint planning session today we decided that we need some more design iteration on this issue, so placing it in the backlog.

**Comment by elizaan36** [comment]
**Update on the Enable/Disable toggle exploration**

I've been exploring options for the Enable/Disable toggle (some in the thread on `pbIJXs-Ak`) and keep coming back to relying on Inbox messages and the existing Advanced Settings toggle.

I'm leaning in this direction for two reasons: 1. We know that people discovered and enabled the new navigation from Advanced Settings with no other prompt. and 2. I have a hunch that an "escape hatch" won't be as critical once we fix the "missing" extensions bug and preserve the flyout.

With the work in #6214, we'll provide a guided intro to the new nav and users can potentially enable it directly from a new Inbox message as well. The usage tracking flow adds another layer of complexity to the enable path, but we can try to include this language in the intro video modal and new Inbox message if we create one.

**Comment by elizaan36** [comment]
Here's one reasonable idea we could have in our back pocket as needed, based on my convo with @joelclimbsthings and @mattsherman on P2.

An ellipses appears while hovering over the WooCommerce category item. Clicking the ellipses will present a popover menu with the option to Turn off WooCommerce navigation.
<img width="916" alt="image" src="https://user-images.githubusercontent.com/5121465/106801825-cfbd9d00-6627-11eb-88fd-a66bd8326965.png">

On mobile the popover could appear upon tapping the WooCommerce category item.

**Comment by joshuatf** [comment]
@elizaan36 Would it be okay for a page refresh when toggling off using this method?

**Comment by elizaan36** [comment]
Yep I also worked on a modal that could appear upon disabling the new navigation, which could trigger the page refresh.

![Disable survey](https://user-images.githubusercontent.com/5121465/106803445-d816d780-6629-11eb-9085-d752b928ec0e.png)

**Comment by joelclimbsthings** [comment]
Thanks @elizaan36 . Just wanted to confirm that we've bottomed out on how we want to handle this, with the ellipsis + modal approach? If so, I think it's helpful to edit the original issue description and include any updated requirements/designs.

Also, we already have a different modal that pops up when we disable the navigation feature via the _Settings -> Advanced -> Features_ checkbox:

![image](https://user-images.githubusercontent.com/444632/107578428-94cbe400-6ba8-11eb-86bf-4caeccd272ea.png)

Do we want to have an entirely different modal here, or perhaps change both modals to match the new one you presented above?

**Comment by elizaan36** [comment]
hey @joelclimbsthings , thanks for the ping on clarification as we've definitely gone back and forth on the best way to handle this. The solutions presented here and in the P2 range from more discoverable to less discoverable and I'll list them out here.

First, I'll mention that we already have one method, which is the checkbox in Advanced Settings ✅ Done
And I'd recommend sticking with that for now until we gather more data, but if we all feel the "escape hatch" is necessary I'd lean towards the [ellipses + modal](https://github.com/woocommerce/woocommerce-admin/issues/6210#issuecomment-772783358) solution.

**Toggle off options**
- Visible persistent link/toggle in nav: Most discoverable but too noisy (pbIJXs-Ak#comment-1871)
- Display dropdown toggle: 🚫 We've ruled this out due to complexities with the data usage opt-in flow
- Ellipses + modal: This feels like the right level of discoverability. It's there when you need it, if you're looking, but it's not going to distract from your workflow.
- Last option is to do none of the above and stick with only the checkbox in Advanced Settings. This would be my recommendation because of the [reasons stated here](https://github.com/woocommerce/woocommerce-admin/issues/6210#issuecomment-772773833)

Thoughts on that?

**Modal**

If we implement any toggle off option, we should use the existing modal that's already been implemented (in your screenshot above.)

If we feel it's worth the effort and want to go in the direction of the modal survey, I imagine we'd want to create a separate issue to be implemented consistently in both places. Sorry, I only became aware we were already collecting feedback in the opt-out survey after I posted the comment above.☺️ 

Some thoughts on that as we start thinking about appetite for updating the modal - the new survey modal is beneficial from the user standpoint because there's only one click and you don't have to navigate to a separate link, but it would require creating a separate way to capture the feedback ourselves, outside of Crowdsignal.

**Comment by psealock** [comment]
>Last option is to do none of the above and stick with only the checkbox in Advanced Settings. This would be my recommendation because of the reasons stated here

In the absence of more data, this seems like the way to go. We can concentrate on improving the experience so merchants won't want to opt out 😄 

I'm going to apply the `On Hold` label so we can come back to this when a direction presents itself.

**Comment by joelclimbsthings** [comment]
Closing prior to the merge as it's been on hold for over a year, and there's uncertainty around this project.
