### ISSUE TITLE
Intro video about the new navigation

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6214]
**User story:**
As a merchant
I want to learn more about the new navigation without leaving WooCommerce
So I can easily understand the benefits of using the new experience

**Description:** we think that presenting a short video via an Inbox message with a run-down of the new navigation and its benefits could help users understand why the new experience can be better than the old one. 

![video-intro.gif](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/c88ad8a3-1feb-439a-8b78-f82cdf8e43f9)

**Acceptance criteria:**
- [ ] Display an inbox notification when the user enables the navigation (copy TBD)
- [ ] Open a modal with an embedded video if the users click "learn more" in the navigation
- [ ] Play the video directly in the modal

**Event tracking:**
TBD

**Comment by pmcpinto** [comment]
@joshuatf thanks for the heads up. Would it simplify the implementation if we just show the modal when the user visits the home screen after enabling the navigation?

**Comment by joshuatf** [comment]
@pmcpinto That would be a much simpler option.  Should we go ahead with that approach?

**Comment by pmcpinto** [comment]
> @pmcpinto That would be a much simpler option. Should we go ahead with that approach?

cc @elizaan36 using a modal will make it easier to implement the intro video

**Comment by elizaan36** [comment]
ok, good to know thanks! Just to clarify, a modal with no video is what you're suggesting @joshuatf?

**Comment by joshuatf** [comment]
@elizaan36 We can do a modal with a video.  With or without the video won't require too much difference in the time it takes to complete this.

The challenge with the original approach is trying to trigger a modal from a note, which can't be done at the moment.

**Comment by elizaan36** [comment]
Thanks @joshuatf for the clarification, makes sense to skip the Inbox message then and present the modal upon landing on the Home screen.

@pmcpinto I'm curious if we'd like to give people the option to enable the new nav directly from this modal? In that case, we'd have to include language about data usage tracking.

**Comment by elizaan36** [comment]
I put together a rough concept for a modal with four steps to introduce the new navigation. I'm thinking the right side of the modal would be animated as you page through, and each page will highlight a different feature of the nav.

![Screen Recording 2021-02-05 at 03 44 48 PM](https://user-images.githubusercontent.com/5121465/107092826-d84dd900-67c9-11eb-92f3-a15cebc6aa17.gif)
[All images are here](https://share.getcloudapp.com/DOu28109)

Static images would work but animating the right side to show the features in action would be more fancy.☺️

Have a look at the flow and let me know what you think. Any thoughts on copy or what to feature would be great too.

**Comment by pmcpinto** [comment]
@elizaan36 this option looks good to me. Nice job!
On the second screen (Focus on all things Woo), I think the copy should be focused on store management instead of Woo. Eg: Focus on store management/Focus on managing your business/store, etc.

**Comment by elizaan36** [comment]
Thanks @pmcpinto! I made that adjustment to the copy in page 2. 

@joshuatf I'll share the first two videos here - let me know if these work with the modal or if we need any other format/ resolution for them. 

[intro video 1 and 2.zip](https://github.com/woocommerce/woocommerce-admin/files/5982587/intro.video.1.and.2.zip)

The navigation dots in the modal are part of an existing component ([part of this "guide" modal](https://wordpress.github.io/gutenberg/?path=/story/components-guide--default)). 

![Intro video 1](https://user-images.githubusercontent.com/5121465/107968009-72084980-6f73-11eb-9986-ce33e5aca1fa.png)

The design I have here is slightly different to the existing component:
- The primary action is directly to the right (horizontally aligned) to the navigation dots because there's no copy in the actual modal.
- If possible, the video is full-bleed to the edge of the modal (not sure if this is possible but nice-to-have)
- If we can do full-bleed there's no X to close icon. Clicking anywhere outside would close the modal, as well as the "Close" primary action on the last page.

Happy to work through all of the details here or in Slack.

**Comment by elizaan36** [comment]
Update: I'm reworking the videos so that the text on the left can be written in HTML to allow for translations.

**Comment by elizaan36** [comment]
@joshuatf here's a zip file with 3 videos. (I scrapped the fourth one because I don't have a video that would work to view the front end of the site, and I think the three steps are enough.)

[Nav intro videos](https://share.getcloudapp.com/xQun6GYd)

Here's the copy to correspond with each:

Nav intro video 1
> **A new navigation for WooCommerce**
All of your store management features in one place

Nav intro video 2
> **Focus on managing your store**
Give your attention to key areas of WooCommerce with little distraction

Nav intro video 3
> **Easily find and favorite your extensions**
They'll appear in the top level of the navigation for quick access

Some more details in addition to the ones in [this comment](https://github.com/woocommerce/woocommerce-admin/issues/6214#issuecomment-779309380):
- I recorded the videos at 2x so the width is 680. This was with the intention of better resolution but let me know if that's a problem
- The width of the default modal can be widened to 680px with the video appearing in the right half (so 340px if it goes to the edge)

![Intro video 2](https://user-images.githubusercontent.com/5121465/108379851-f05f2880-71cb-11eb-8691-fe0c3e9b9f6b.png)

Here are the text styles I'm using:
- Header text: SF Pro Display Bold 32px
- Body text: SF Pro Text Regular 16px
- Line height is pretty generous for both of these, like 1.4 - 1.8

And yeah, this way the left side can be localized. Let me know how it goes and feel free to ping me to take a look anytime.
