### ISSUE TITLE
Calypso navigation items and REST API routes

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#6223]
Part 2 of https://github.com/woocommerce/woocommerce-admin/issues/6129 requires us to add this menu to Calypso.  In order to do this, we probably need a REST API to pull information from as @psealock suggested.

We may want to expose an endpoint to get all items as well as filters and/or an additional endpoint to get the flyout menu items.

![image](https://user-images.githubusercontent.com/10561050/106195980-e45ce980-617e-11eb-8b75-fe934a79905f.png)

**Comment by joshuatf** [comment]
Estimate: 3 for the REST API routes.  I don't expect these to be hard, but I am a little concerned whether or not all the hooks for `admin_menu` and other used events will fire during a REST request.  This could be very problematic if not.

Estimate: 3 for Calypso- mostly around unfamiliarity with the nav unification.

**Comment by timmyc** [comment]
@mattsherman and other folks on Mothra are working a bit with nav unification too, perhaps we can have a collab on this one 🌟

**Comment by mattsherman** [comment]
The way the Nav Unification works, it relies on the normal wp-admin building of the admin menu and uses that to construct the menu that gets sent back through the REST API to Calypso. So, as long as we get the WooCommerce menu in general (including its flyout) working with Nav Unification you shouldn't have to do anything special.

See https://github.com/automattic/wp-calypso/issues/49209

**Comment by mattsherman** [comment]
> The way the Nav Unification works, it relies on the normal wp-admin building of the admin menu and uses that to construct the menu that gets sent back through the REST API to Calypso. So, as long as we get the WooCommerce menu in general (including its flyout) working with Nav Unification you shouldn't have to do anything special.
> 
> See [Automattic/wp-calypso#49209](https://github.com/Automattic/wp-calypso/issues/49209)

Just to re-iterate, I don't think we should need to do anything special to get the flyout menu working in Calypso. Any issues we see with this flyout not being returned properly by the `admin-menu` API endpoint should be discussed with the Nav Unification team (Ajax). As long as we are adding menu items in a "legal" WordPress fashion, Nav Unification should ideally handle those.

We would want to avoid any special handling of this in Calypso. Because any special handling we need to do is duplicated effort, and also effort that other 3PDs will not be able to do (add special handling to Calypso to support their plugin's menu items).

**Comment by joshuatf** [comment]
I think you're correct @mattsherman and we can probably close this issue.  @psealock noted here that the flyout menu was already working - https://github.com/woocommerce/woocommerce-admin/pull/6165#issuecomment-772131483

We can probably register favorited extensions in a similar manner so I think we won't need an additional REST API.

**Comment by psealock** [comment]
>Just to re-iterate, I don't think we should need to do anything special to get the flyout menu working in Calypso.

Yeah, I think you're right here in that an API isn't necessary and definitely agree that we want to avoid doing anything special because 3PD will also need to so.

>we can probably close this issue. @psealock noted here that the flyout menu was already working - #6165 (comment)

That comment was on the wp-admin side of things only, sorry about that. Some things are off on Calypso. I tested my site with `main` of wc-admin zipped, which now has the flyout menu.

* All the Woo items are in the flyout
* Products, Analytics and other top level items should be under WooCommerce with WC Nav enabled but they remain

<img width="276" alt="Screen Shot 2021-02-05 at 8 52 36 AM" src="https://user-images.githubusercontent.com/1922453/106948050-1f1edd00-6790-11eb-941a-407db2618911.png">
<img width="437" alt="Screen Shot 2021-02-05 at 8 53 58 AM" src="https://user-images.githubusercontent.com/1922453/106948064-22b26400-6790-11eb-8bc4-afdbf5ba3901.png">

**Comment by psealock** [comment]
@joshuatf It looks like none of Woo Nav's functions hooked to filter `add_menu_classes` get executed by the public API's `admin-menu` route. It does respect the `admin_menu` filter though. Is there a way we can change our logic to only use `admin_menu` filter with carefully crafted priorities?

**Comment by joshuatf** [comment]
@psealock My gut feeling is that we can't or that we'll need to solve another problem by doing this.  I seem to recall there was a reason we needed to hook into `add_menu_classes` to work around this.

But let me dig into this a bit and get you a better answer.

**Comment by psealock** [comment]
Maybe we can add `do_action( 'add_menu_classes' )` to the api

**Comment by psealock** [comment]
Closing in favour of https://github.com/woocommerce/woocommerce-admin/issues/6299 to modify the actions used instead of an API approach.
