### ISSUE TITLE
[1.9] Inbox: Email Notification Received for Adding First Product, when Products Exist

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#6231]
**Describe the bug**
This was reported in [a8c slack today](https://a8c.slack.com/archives/C3ECCGUVC/p1611946299031800) by @ChaosExAnima 

The site in question was auto-updated to `woocommerce-admin` 1.9.0, and after that, the email notification from introduced in https://github.com/woocommerce/woocommerce-admin/pull/6024 was triggered on the site. It seems there are established products, but they are in draft form, and as such the email notif was triggered.

The site is established, and has been running Woo for over 2 years, so thinking we need to make the logic on this notif a bit more restricted @octaedro / @pmcpinto - maybe have it only send to sites that are _between_ 3 and 30 days old maybe?

Another great idea from Echo: perhaps we should also check and make sure the site has zero sales to cover for the case where products get published and subsequently unpublished.

**Comment by elizaan36** [comment]
Hey, I know this issue is about something else but wanted to also make sure the theme color is being pulled in so that colors are consistent on the email. Would be great to avoid situations like this one that was shared in the issue if possible. If that's not possible let me know @octaedro and I'll share a new design with different colors for the header and illustration.

<img width="997" alt="image" src="https://user-images.githubusercontent.com/5121465/106323829-ad99d880-623d-11eb-9e2c-f6356e50e2b5.png">

The box illustration also looks a bit pixelated but it may be the screenshot that was shared.🤔

**Comment by ChaosExAnima** [comment]
> The box illustration also looks a bit pixelated but it may be the screenshot that was shared.🤔

No, it seems pixelated in the email. Here's the raw file:

![unnamed](https://user-images.githubusercontent.com/1760168/106324447-25b8cc00-6247-11eb-8f91-3756734e9154.png)

**Comment by pmcpinto** [comment]
> more restricted @octaedro / @pmcpinto - maybe have it only send to sites that are between 3 and 30 days old maybe?

> Another great idea from Echo: perhaps we should also check and make sure the site has zero sales to cover for the case where products get published and subsequently unpublished

These restrictions make sense to me

**Comment by octaedro** [comment]
Hi @elizaan36 and @ChaosExAnima, thank you for reporting that 🙂

Answering Elizabeth's questions:

> Hey, I know this issue is about something else but wanted to also make sure the theme color is being pulled in so that colors are consistent on the email. 

The colors we use in the emails are set in `/wp-admin/admin.php?page=wc-settings&tab=email` and the user chooses them.

![screenshot-one wordpress test-2021 02 01-11_20_13](https://user-images.githubusercontent.com/1314156/106470865-c72a6280-647f-11eb-892a-f39bcbaf4a96.png)

So the control we have over the colors is limited.

> The box illustration also looks a bit pixelated but it may be the screenshot that was shared.🤔

Sorry for that, I have bad eyes and I'm still not able to see the pixels in the small picture 🤣
I transformed the original image to PNG since the original format is problematic on some email clients.
Could you re-send me the image in PNG format?

**Comment by elizaan36** [comment]
Thanks @octaedro, makes sense that the WooCommerce email theme color is being pulled in. I had made a couple assumptions when sharing the original design - I thought the WP theme color would be pulled in, and I also thought the theme color would adjust the box image. I believe the default email color is purple `#96588a`?

Here I'll share the box PNG with the default purple color: https://share.getcloudapp.com/YEuXKzWB - Let me know if the download is high resolution enough.

**Comment by octaedro** [comment]
Hi @elizaan36,

> I believe the default email color is purple #96588a?

That's right 🙂

> Here I'll share the box PNG with the default purple color: https://share.getcloudapp.com/YEuXKzWB - Let me know if the download is high resolution enough.

Could you send me the image with no blank space around it? I can crop it but I think that it would be better if you do it to be sure that the image has the right properties.

![screenshot-one wordpress test-2021 02 02-10_23_52](https://user-images.githubusercontent.com/1314156/106606826-551a5200-6541-11eb-9f96-0be6e5816b59.png)

**Comment by elizaan36** [comment]
No problem, let me know if this works. https://share.getcloudapp.com/d5uwzzOz

**Comment by octaedro** [comment]
Great! That's what I needed.
Thanks @elizaan36 🙂
