### ISSUE TITLE
Could Report* components be added to components package?

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#6243]
## **Is your feature request related to a problem? Please describe.**
I'm implementing report pages for [a plugin](https://github.com/woocommerce/google-listings-and-ads/), that would look just like [`/analytics/products`](http://localhost/wordpress/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fproducts). To serve consistent UX I'd like to make them look and behave exactly the same, therefore reuse the components. To improve DevX and reduce the costs of maintenance on A8C side, it would be nice to import them from the same source, instead of duplicating the code.

## **Describe the solution you'd like**
I'd like to have [`ReportError`](https://github.com/woocommerce/woocommerce-admin/blob/main/client/analytics/components/report-error/index.js), [`ReportChart`](https://github.com/woocommerce/woocommerce-admin/blob/main/client/analytics/components/report-chart/index.js), [`ReportSummary`](https://github.com/woocommerce/woocommerce-admin/blob/main/client/analytics/components/report-summary/index.js), [`ReportTable`](https://github.com/woocommerce/woocommerce-admin/blob/main/client/analytics/components/report-table/index.js) published, so I could do
```
import { ReportError, ReportChart, ReportSummary, ReportTable } from '@woocommerce/components';
```
Fill it with my data, and serve consistent UX and DevX.

## **Describe alternatives you've considered**
~D~RY: copy'n'paste, and replace data source with some config.

## **Should this be prioritized? Why?**
I think this should be solved before going live with GLA plugin.

## **Additional context**
I can start a PR with that, but I'm not sure if there are any rules/policies regarding our components package.
- Maybe we would like to limit the number of published components, to reduce the public API we expose to external parties? 
- Or are there any rules/requirements `@woocommerce/components` have to meet?

**Comment by adrianduffell** [comment]
Hi @tomalec ,

Thanks, I've brought this up with the team and it sounds like a great idea. You could start a PR for this as you suggested.

There are perhaps some complexities with WC Admin-specific behavior needing to be made optional. This is mentioned in a similar issue https://github.com/woocommerce/woocommerce-admin/issues/5763

An approach we could take is to fork the report components into the new package, so that modifications can be freely made to make it suitable for external use. WC Admin would continue to use the existing internal components until the package is stable. Let me know what you think or if you have other ideas?

There is documentation for creating a new package in the [README](https://github.com/woocommerce/woocommerce-admin/tree/main/packages).

> Or are there any rules/requirements @woocommerce/components have to meet?

We would need to have documentation in the package README, similar to the existing packages. Tests are also good 🙂

**Comment by kingkero** [comment]
Any news on this?

Seems like `ReportFilters` is part of the package (https://github.com/woocommerce/woocommerce-admin/blob/main/packages/components/src/index.js#L30), but other `Report*` components are still missing.

**Comment by ilyasfoo** [comment]
It has been a while, we can't find contributors able to help with this feature request. I may close this issue in a few days if no one picks this up.

**Comment by ilyasfoo** [comment]
Closing this for now.
