### ISSUE TITLE
Add product email notification: change the from and reply-to

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6362]
We should try to find ways to differentiate the sender and the recipient, as this is a common spam pattern. WordPress core uses wordpress@domain.com, something similar could work for us. AFAIK the WooCommerce Core emails have the same issue: the sender and recipient is the same.

**Comment by psealock** [comment]
Estimate: 1

**Comment by ilyasfoo** [comment]
@pmcpinto Since it's an automated mail with no intention to reply to, I think we can just remove reply-to altogether. Let me know if you think otherwise!

>AFAIK the WooCommerce Core emails have the same issue: the sender and recipient is the same.

I've found out that this isn't true, we can configure the from address and name in the WooCommerce > Settings > Email:

![image](https://user-images.githubusercontent.com/3747241/111631733-b7e45600-882e-11eb-907e-abec2ffd0b49.png)

Sample email headers:

![image](https://user-images.githubusercontent.com/3747241/111631625-971c0080-882e-11eb-9dd4-dc75e5c21313.png)

**Comment by pmcpinto** [comment]
> @pmcpinto Since it's an automated mail with no intention to reply to, I think we can just remove reply-to altogether. Let me know if you think otherwise!

Good call. Makes sense!

> Other than removing no-reply that I suggested, I don't think we can do anything here, since we'll just be using the values set by WordPress, and it's customizable by the user.

Gotcha. Thanks for the clarification!
