### ISSUE TITLE
[GlobalStep - WooCommerce 5.1 Beta 1][Mac] Dropdowns appears truncated on “Business details” step during Onboarding setup wizard.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-admin#6372]
## Bug Description:
Dropdowns appears truncated on “Business details” step during Onboarding setup wizard .

## Environment:
macOS High Sierra v10.13.6
Safari: v13.1.2(13609.3.5.1.5)
Chrome: v85.0.4183.83
                
## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all the required plugins
1. Complete the Onboarding setup wizard till "Business details".
1. Click on How many products do you plan to display? and Currently selling elsewhere? dropdowns.
1. Observe dropdowns appears truncated on “Business details” during Onboarding wizard setup.

## Actual Result:
Dropdowns appears truncated on “Business details” step during Onboarding setup wizard .

## Expected Result:
Dropdowns should display properly on “Business details” step during Onboarding setup wizard.

## Screenshot/Video:

![#6372_1](https://user-images.githubusercontent.com/41110392/108390645-e1619000-7236-11eb-90ca-fee33a414283.png)

https://user-images.githubusercontent.com/41110392/108390682-ec1c2500-7236-11eb-9506-be3227214ec6.mov

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by joelclimbsthings** [comment]
Thanks for reporting this, @gglobalstep !

Also able to reproduce this on `main`. One odd characteristic that I noticed is that it does _not_ appear if you allow the onboarding wizard to be activated normally and follow the steps to this page. 

It _is_ visible, though, if you refresh the page while on the business details page, or directly navigate to `admin.php?page=wc-admin&path=%2Fsetup-wizard&step=business-details`. You'll notice the gap on the bottom that results in the drop-downs appearing truncated. 

It seems to involve the `overflow-x: hidden` style on `#wpbody-content`. 

Since this doesn't actually prevent the user from selecting these options I'd consider it a low priority.

**Comment by hsingyuc** [comment]
I'll push a PR shortly.
