### ISSUE TITLE
Browser console error

### ISSUE THREAD

**Issue by octaedro** [woocommerce/woocommerce-admin#6593]
**Describe the bug**
There is a browser console error in the payments task
![screenshot-separate-caribbean jurassic ninja-2021 03 15-14_15_35](https://user-images.githubusercontent.com/1314156/111193544-07115900-8599-11eb-9668-97fdab4c8520.png)

This is the error:
```
GET https://separate-caribbean.jurassic.ninja/wp-json/wc-paypal/v1/onboarding/get-status?_locale=user 404
```

**To Reproduce**

1. Create a brand new site and install `WooCommerce Admin` v2.1.3
2. In the `Business Details` step in the OBW, under `Free features` unselect the first option `Accept credit cards with WooCommerce Payments`.
3. Finish the OBW.
4. Go to the payments task `Choose payment methods` (`/wp-admin/admin.php?page=wc-admin&task=payments`)
4. The error will be visible after a couple of seconds

**Expected behavior**
No JS errors

**Screenshots**
![Captura de Pantalla 2021-03-15 a la(s) 14 04 12](https://user-images.githubusercontent.com/1314156/111193352-d7625100-8598-11eb-88ec-1a7c2855ae1c.png)

**Desktop (please complete the following information):**

* OS: Mac OS
* Browser Chrome

**Comment by louwie17** [comment]
In a way this is expected behaviour, but should probably not be triggered if the paypal payments plugin is not installed or enabled. The get-status checks if a user has finished the onboarding flow of the paypal plugin.
We could also move this to the back-end I suppose and use a `rest_do_request` adding it to the onboarding data.

**Comment by hsingyuc** [comment]
I have a fix for this; push shortly.
