### ISSUE TITLE
Reports for sales by category are broken (Leaderboards > Top Categories - Items Sold)

### ISSUE THREAD

**Issue by andreigusan** [woocommerce/woocommerce-admin#6627]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Reports for sales by category are broken (Leaderboards > Top Categories - Items Sold).

We can't reset/reimport the reports data because the Analytics > Settings page has a error:
<img src="https://p199.p4.n0.cdn.getcloudapp.com/items/yAu6p4Gz/a15baf92-93ec-4693-94df-a43986f3ce10.jpg?v=a4e75a49cf92db96561c9dde6824a67b">
WordPress 5.7
WooCommerce 5.1

**Comment by aheckler** [comment]
I do not see the JS error mentioned above, but I do see data inconsistencies between these two reports:

- Analytics > Overview, scroll down to Leaderboards and look at Top Categories - Items Sold.
- Analytics > Categories, filter to use the same category.

For the same data range, the data is different. Screenshots:

![Markup on 2021-04-29 at 09:55:32](https://user-images.githubusercontent.com/5512652/116562348-14786d80-a8d1-11eb-9ba0-cc258ca5989f.png)

![Markup on 2021-04-29 at 09:55:41](https://user-images.githubusercontent.com/5512652/116562369-180bf480-a8d1-11eb-8bc7-4ef4e7b76665.png)

You can see there the Items Sold and Net Sales data is different, but I'm looking at data for the same category over the same date range.

**Comment by andreigusan** [comment]
The JS error was related to WordPress core and was fixed with the latest update. The reports inconsitency is still there :(

**Comment by samueljseay** [comment]
I could only reproduce this in wc-admin if I generated some new orders and then without a page refresh went between the 2 different reports that were inconsistent. It seemed one was correct immediately and the other after a page refresh was in sync with the other. Otherwise I cannot reproduce this inconsistency with latest wc-admin in development.


Here's what I see:

<img width="1206" alt="Screenshot 2021-05-12 at 12 28 34 PM" src="https://user-images.githubusercontent.com/1281828/117900605-a47cd500-b31d-11eb-80ac-16e693d9f4bf.png">
<img width="1219" alt="Screenshot 2021-05-12 at 12 28 52 PM" src="https://user-images.githubusercontent.com/1281828/117900616-a777c580-b31d-11eb-9c7d-c09a513fe556.png">

**Comment by andreigusan** [comment]
Analytics numbers are still off:

![Untitled-1](https://user-images.githubusercontent.com/373113/124351212-b08c6100-dc01-11eb-9b19-11d0918641e9.jpg)

Issue seems to be with table from Analytics > Overview > Leaderboards > Top Categories - Items Sold.
Numbers from Analytics > Categories > Single category reports are correct.

Tried a number of things on a staging environment, nothing seems to work for us:
- updated all software to latest version;
- disabled all plugins except WooCommerce and installed and activated Storefront theme - just to rule out any issues from customisations;
- cleared all transients;
- regenerated product lookup table data;
- deleted previously imported data;
- reimported historical data;

Setup details:
- WordPress 5.7.2
- WooCommerce 5.4.1
- PHP 7.4.19
- MariaDB 5.5.5-10.2.38

Help! :)
