### ISSUE TITLE
Remote inbox system: automatically install extensions from wp.org when clicking in the inbox CTA

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6689]
**Description:** in order to remove friction, and increase the remote inbox effectiveness, the remote system should be able to autoinstall extensions from wp.org

**Acceptance criteria:**
- [ ] Automatically install extensions when the user clicks in the main call to action of a remote inbox message

**Comment by ilyasfoo** [comment]
Estimate: 5

We will probably need at least a new rule to ensure see if the target plugin is not installed yet (and possibly also check whether the site has satisfied all the plugin's dependencies?). Also, I think this functionality is a big enhancement to remote inbox since our current implementation only allows for link-based actions.

**Comment by becdetat** [comment]
> We will probably need at least a new rule to ensure the target plugin is not installed yet (and possibly also check whether the site has satisfied all the plugin's dependencies?)

There is already a rule that covers this - `plugins_activated`
