### ISSUE TITLE
Unclear translations / unprecise wording

### ISSUE THREAD

**Issue by giacogiaco** [woocommerce/woocommerce-admin#6694]
**Describe the bug**
The translations of the terms _Gross Sales_, _Total Sales_ and _Net Sales_ don't make sense, especially when translated to other languages

**To Reproduce**
1. Change language to German
2. Go to Analytics > Revenue
3. Try to understand the difference between _Bruttoumsatz_, _Umsatz insgesamt_ and _Nettoumsatz_

**Expected behavior**

- **_Total Sales_** should be all revenue, without any deductions. Basically the top line.
- **_Gross Sales_** should be _Total Sales_ – _refunds_ – _coupons_
-  **_Net Sales_** should be _Gross Sales_ – _taxes_

(The user should be able to decide whether shipping cost should be included in _Net Sales_ or not.)

This would be much more intuitive. 

---
(Also, please see #6692 – this issue only adds to the confusion)

**Comment by moon0326** [comment]
@giacogiaco Thank you for taking the time to report this bug, we really appreciate your help. I feel like this is a feature request than a bug since functionalities are working as expected. 

We won’t be able to include this change in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

If you are interested to submit a PR to fix it, it will be welcomed.

**Comment by chihsuan** [comment]
I'm closing this since this is low impact and is over 6 months.

I think changing these term definitions would cause many following issues since they are already defined in our document. As for the translation issues, please feel free to give us some suggestions to improve the German terms `Bruttoumsatz, Umsatz insgesamt and Nettoumsatz`
