### ISSUE TITLE
WooCommerce knowledge base pagination link changes size with disabled pagination links

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce-admin#6709]
**Describe the bug**

Under Marketing > Overview, there are pagination buttons under the `WooCommerce knowledge base` section, which allows you to go through various articles. When you navigate using these buttons, the size changes when there is a disabled previous or next link:

https://user-images.githubusercontent.com/71906536/113061206-f226ef00-916e-11eb-9a15-4da7843b3890.mov

**To Reproduce**

1. Go to Marketing > Overview
2. Scroll down to the `WooCommerce knowledge base` section
3. Click the navigation buttons and note the size changes based on if there are disabled forward/previous links:

<img width="501" alt="Screen Shot 2021-03-30 at 3 46 24 PM" src="https://user-images.githubusercontent.com/71906536/113061373-29959b80-916f-11eb-9a11-9919d957c2c9.png">

<img width="497" alt="Screen Shot 2021-03-30 at 3 46 28 PM" src="https://user-images.githubusercontent.com/71906536/113061383-2d292280-916f-11eb-81f0-7cdddcc26627.png">

**Expected behavior**

The navigation link buttons should retain the same size when used.

**Desktop (please complete the following information):**

* OS: macOS
* Browser: Firefox, Chrome
* Version: Firefox 87.0 ; Chrome 89.0

**Comment by joshuatf** [comment]
Thanks for opening this issue and also for the video @zhongruige!  Made it very easy to see the issue.

I'm able to replicate this on `main`.  Looks like the culprit is from the selector `.woocommerce-pagination__page-arrows-buttons .components-button:not(:disabled):not([aria-disabled='true'])`.  The button height is set on non-disabled buttons, but the first slide's button is disabled, leaving it without a specified height.

**Comment by hsingyuc** [comment]
I have a fix for this; push shortly.
