### ISSUE TITLE
Task list shipping step only available through onboarding wizard

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#6761]
**Describe the bug**
If a user skips the onboarding wizard the `Set up shipping` task will not show in their task list. This happens because WooCommerce automatically adds the default `all other locations` zone. 

The [current condition on the task list item being complete is `> 0`](https://github.com/woocommerce/woocommerce-admin/blob/main/client/task-list/tasks.js#L232). It should be `> 1` which verifies that a zone has been created by the merchant.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a new site
2. Skip onboarding, dismiss HQ modal
3. Set up shipping task is not included in the list
4. Add a store address through settings
5. Check for the shipping task

**Expected behavior**
An alternative/addition would be to change the render logic so that when the shipping task is considered complete it is still included in the list with the check as complete.

**Comment by samueljseay** [comment]
> An alternative/addition would be to change the render logic so that when the shipping task is considered complete it is still included in the list with the check as complete.

I think this solution sounds like a good way forward.

**Comment by octaedro** [comment]
This issue was created a few months ago. AFAICS the `Set up shipping` task [visibility depends on the product's types](https://github.com/woocommerce/woocommerce-admin/blob/main/client/task-list/tasks.js#L325) that the store sells. That makes sense since this item shouldn't be visible when the store doesn't sell physical products.
On the other hand, the item is visible as soon as a physical product is added.

Since it looks like the current behavior is the expected, if it's ok with you @rrennick I'll close this issue.

**Comment by rrennick** [comment]
> Since it looks like the current behavior is the expected, if it's ok with you @rrennick I'll close this issue.

Closing.
