### ISSUE TITLE
Why wc_remote_inbox_notifications_specs option is autoload enabled?

### ISSUE THREAD

**Issue by Mte90** [woocommerce/woocommerce-admin#6781]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
We are working on a customer website to optimize the database I saw that option in the `wp_options` table with autoload as `yes` but to me is not clear why should be loaded in every page of the website.

I have this `wc_remote_inbox_notifications_specs` option with autoload yes in 2 different website with different plugins/themes and is just an admin option.
I just changed by DB as `no` for autoload and the website works well anyway.

**Comment by moon0326** [comment]
@Mte90 Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. My test website works without an issue when I set the autoload to 'no'

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

If you are interested to submit a PR to fix it, it will be welcomed.

**Comment by Mte90** [comment]
I don't know if https://github.com/woocommerce/woocommerce-admin/pull/6995 can consider this ticket closed.

**Comment by becdetat** [comment]
Thanks @Mte90 , #7060 changes the autoload to `no` so this ticket can be closed. Thanks for bringing this to our attention.
