### ISSUE TITLE
Blank Analytics Screen with 5.2.2

### ISSUE THREAD

**Issue by langhenet** [woocommerce/woocommerce-admin#6857]
After updating to 5.2.2 I get an empty analytics page (and it looks like it doesn't recognize the position in the left menu). See screenshot

![ScreenClip](https://user-images.githubusercontent.com/16612477/115663896-72410e80-a341-11eb-9686-863529c7e3f0.png)

Unfortuntately I do not have any error in the console / error log.

* OS: Win 10
* Browser: Chrome
* Version: 89

**Comment by ilyasfoo** [comment]
Hi @langhenet, thank you for taking your time to report this issue. I have tested installing WooCommerce 5.2.2 on a fresh site and was able to navigate to Analytics screen without a problem. The blank page looks like the problem occurred somewhere in your browser, it's peculiar that no error is produced in console. 

Unfortunately without much information, we're unable to identify the problem. It may also be a conflict of plugins or something specific on your site.

**Comment by langhenet** [comment]
Yes, I made a local Install and everything works fine for me too :-/

I'll try to see if it's a confict with another plugin

**Comment by langhenet** [comment]
Hi,
After some digging I've found the issue.

This is a Multisite installation. As a superadmin, even if I was not directly added to the Shop/WooCommerce subsite as a user, I've always been able to view the Analytics/Reports.

With the last update, if the superadmin is not added as a user on the subsite, he's no longer able to see the reports. Even more setup wizard is completely broken / non functional, and the whole ajaxified part of the backend such as WooCommerce -> Home is no longer working.

Hope this helps :-)

**Comment by ilyasfoo** [comment]
Hi @langhenet. That's a great catch, I've tested this out in multiple versions and found out that this had been broken since WooCommerce 5.2.0 which ships with WooCommerce Admin 2.1.5 (it's broken since WCAdmin 2.1.2).

Thank you for reporting this, I will create another issue in order to address the exact problem.

**Comment by ilyasfoo** [comment]
Hi @langhenet,

That's a great catch, I've tested this out in multiple versions and found out that this had been broken since WooCommerce 5.2.0 which ships with WooCommerce Admin 2.1.5 (it's been broken since WCAdmin 2.1.2).

Thank you for reporting this, I've created another issue in order to address the exact problem. I'm closing this now, you can track the progress of the issue by following #7004.

**Comment by moon0326** [comment]
@langhenet I've submitted a bug ticket in the core and it looks like this is actually expected (or correct) behavior.

You can check the comment on [here](https://core.trac.wordpress.org/ticket/53231#comment:3) 

To get around your situation, you can add your super admin to the site.

You can do so by performing the following steps.

1. Navigate to :your-site/wp-admin/network/sites.php
2. Click on the 'edit' on the site
3. Click on the "Users" tab
4. Add your super admin from the "Add Existing User" section.

**Comment by langhenet** [comment]
Hi @moon0326, yes, I know how to add a user to a MU site :-)

It's a pity because it was much easier / less complicated as it was before ;-)

Thanks!
