### ISSUE TITLE
Remote Payment Recommendations: Add SlotFill for WC Pay "Recommended"

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#6868]
In https://github.com/woocommerce/woocommerce-admin/pull/6766 @joelclimbsthings created a new card for WC Pay's recommended payment method. 

<img width="988" alt="Screen Shot 2021-04-22 at 2 42 32 PM" src="https://user-images.githubusercontent.com/1922453/115649138-dc29da00-a37a-11eb-8efa-1238930d4515.png">

Since design and functionality are unique to WC Pay, lets move this to that repo and use SlotFill to populate the UI. Another reason to move the card to WC Pay, is it will be used in the empty state view of WC Pay. See https://github.com/Automattic/woocommerce-payments/issues/1436 for details.

**Comment by psealock** [comment]
Estimate 1

**Comment by joelclimbsthings** [comment]
I believe it was mentioned elsewhere already, but the purely SlotFill from WCPay approach won't work here since the card is displayed prior to the plugin being installed. 

We also have a [very similar component](https://github.com/Automattic/woocommerce-payments/pull/1600/files) in the WCPay Connect page, and it would be great to manage both of these with a single component. Unfortunately for the above reasons this isn't as easy as slotfilling from WCPay, but perhaps we could house this in a 3rd package, like `@woocommerce/components` for both to utilize?

Options:
- Have two separate but similar components in wc-admin and WCPay repos.
- House component in wc-admin, and utilize in WCPay via slotfill/otherwise. This unfortunately ties us to very long release cycles.
- Put in another package. such as `@woocommerce/components`.

If there aren't any obstacles I'm not appreciating, #3 seems attractive. Thoughts?
cc @psealock @joshuatf @adrianduffell

**Comment by adrianduffell** [comment]
@joelclimbsthings thanks agreed we should try to share this component between WC Admin and WC Pay.

Though my understanding of this component is it displays after the plugin is installed. ie the flow is:

1. Install the plugin.
2. Display this component and the user proceeds by pressing the `Finish Setup` button. 

Is the present flow in WC Admin different to this?

I do agree though, a package seems attractive if SlotFill is not possible.

**Comment by joelclimbsthings** [comment]
> Is the present flow in WC Admin different to this?

Yup, there is an initial state before it is installed on the payment task page:
![image](https://user-images.githubusercontent.com/444632/117851888-9d7d9600-b23b-11eb-9df6-f6dc5f9efc5e.png)

**Comment by adrianduffell** [comment]
Thanks @joelclimbsthings, +1 from me then to make it a package to hare between WC Admin and WC Pay.

**Comment by joshuatf** [comment]
To throw out another alternative for the sake of conversation - what if we kept the pure SlotFill approach in place and fetched a remote script from the WCCOM server (assuming marketplace suggestions are opted in)?  This is similar to how the plugins work, but with the exception that the registered plugin script would be hosted on WCCOM instead of the plugin directory.

The flow would look like this:

1. Add a Slot for the spot.
2. Check if marketplace suggestions are opted in.
3. Fetch the remote script.
4. Enqueue the script and Fill

**Comment by joelclimbsthings** [comment]
> To throw out another alternative for the sake of conversation - what if we kept the pure SlotFill approach in place and fetched a remote script from the WCCOM server (assuming marketplace suggestions are opted in)? 

Intrigued @joshuatf . The logic to manage this would have to appear in both WCPay and wc-admin, then? Would the requirement of being opted in to Marketplace suggestions be a significant obstacle for either use case (wondering moreso on the WCPay side)? I wonder what we could default to in the case that they're _not_ opted in, since this is an entire component, and not just configuration.

Also, I'm not all too familiar with the release process and such around the packages. What are the downsides to that approach?

**Comment by joshuatf** [comment]
>The logic to manage this would have to appear in both WCPay and wc-admin, then?

Only the Slot would be in WooCommerce Admin.  The component itself would be housed at WCCOM.  The problem with placing in WCPay is that we don't have access to it until after it's installed.  The problem with placing in WooCommerce Admin is we have to wait until the next release cycle.  WCCOM avoids both of those issues.

>Would the requirement of being opted in to Marketplace suggestions be a significant obstacle for either use case (wondering moreso on the WCPay side)?

I don't think so.  I believe marketplace suggestions are on by default, meaning that this would show until someone went into settings to turn of marketplace suggestions.

>Also, I'm not all too familiar with the release process and such around the packages. What are the downsides to that approach?

Even if we place this into a package, we're still at the whim of the release cycle of whichever plugin consumes this package.  So while this may or may not be advantageous to share this component in a package, I don't think it solves the main issue that we have another chicken and egg scenario with the SlotFill.

**Comment by joelclimbsthings** [comment]
Thanks @joshuatf , definitely clarifies things. Is the release cycle issue _only_ an issue WooCommerce Admin, and _not_ WCPay? As in, is it not an issue to wait for release cycles to update this component in WCPay?

If so, we could house a generic component in a package, and then use this package normally within WCPay, _and_ use it to generate the script that we're publishing to WCCOM. That way we don't have redundant components & meet the requirement of breaking away from the release cycles for WC-Admin. 

That said, one thing that is entirely a mystery to me thus far is what is involved in publishing scripts/etc to WCCOM and where that code would live.

**Comment by joshuatf** [comment]
>As in, is it not an issue to wait for release cycles to update this component in WCPay?

I think it depends on what you mean.  If you mean injecting the plugin's script, then release is not an issue, but this screen is shown prior to WCPay install so this won't work.  If you're referring to WCPay possibly being bundled in core, then we still have release cycle issues.

>If so, we could house a generic component in a package, and then use this package normally within WCPay, and use it to generate the script that we're publishing to WCCOM.

Is placing the component in WCPay mostly an organizational concern?  As long as it's in a package, I suppose we can release whenever it's needed so we won't be tied to the plugin release cycle.

>That said, one thing that is entirely a mystery to me thus far is what is involved in publishing scripts/etc to WCCOM and where that code would live.

I'm not sure either, but if something's not in place already and we don't generate a script from packages, it could be as simple as the work you did in the [remote payments tester](https://github.com/joshuatf/woocommerce-admin-remote-tester/blob/main/src/index.js).

**Comment by joelclimbsthings** [comment]
> I think it depends on what you mean. If you mean injecting the plugin's script, then release is not an issue, but this screen is shown prior to WCPay install so this won't work. If you're referring to WCPay possibly being bundled in core, then we still have release cycle issues.

I'm referring simply to whether, within WCPay, we _care_ about this component being able to update more frequently than their release cycles as well, or if that's just a concern for the use case in WC-Admin. If we don't care, then we can just import it from the package normally for WCPay, and then generate the WCCOM hosted script from that same package for remote payments.

**Comment by psealock** [comment]
If I may boil this debate down to simple terms:

The original solution to the chicken/egg issue was to supply the config with a url pointing to built assets that can be loaded and executed on the fly without requiring a page refresh. For example `/woocommerce-payments/dist/obw-slotfill.js`. That file, `obw-slotfill.js` is built by WC Pay and included in the plugin.

The solution being debated here is to host the built file `obw-slotfill.js` on WCCOM. The mechanism is the same, but the executable javascript is coming from WCCOM.

Would you say thats a correct synopsis? If so, I'm not seeing too much benefit. The JS still needs to be built from WC Pay somehow, it excludes Marketplace suggestions opted-out folks, and invites a whole 'nother legal debate and possible opt-in mechanism. Its easy to draw a conclusion that the configs being implemented this sprint are indeed suggestions from our marketplace, but using that flag to pull down a script is a different beast altogether.

**Comment by joelclimbsthings** [comment]
> Would you say thats a correct synopsis?

I think it's a bit dicier than that, although I'm still a little unclear on a few of the requirements here. This particular Slotfill _needs_ to display before WCPay is ever installed at all to support the initial state, which is the deal-breaker in terms of housing it exclusively within WCPay.

To clarify, we have two use-cases for this component:
- The _Connect_ page within WCPay.
- The _Payment Task_ screen within WC-Admin.

And here's my (perhaps incomplete) understanding of the requirements:
- Since we have the above two use cases for this, we're trying to have both utilize the same component to avoid redundant ui/logic.
- We can't house this component within WC-Admin since we want to break away from the release cycles in that plugin.
- We can't house this component within WCPay due to the fact that it needs to be displayed in the payments task screen before WCPay is ever installed, as mentioned previously.
- One **unknown** requirement is this -> do we want this component (specifically the iteration shown on the Connect page) to be free of the WCPay release cycle as well? 

### Options:
- The _only_ solution I can see that satisfies all of the above is to house the component within a completely separate package, and use it to generate a remote script on WCCOM for it's usage on the payment connect screen. That way we can regenerate this script any time outside the release process. Also, **if** WCPay doesn't need to have that flexibility, they can just consume the aforementioned package normally. If they **do** require that, then they'd also need a similar WCCOM hosted slotfill solution.
- The only alternative to this I believe comes from not worrying about having both use cases utilizing the same component and developing this separately, accepting redundant logic/ui. However WC-Admin would still need to utilize the remote script approach to satisfy the 2nd requirement, and I don't really see what benefits this has over just housing it in a separate package as mentioned.

That's the status as I understand it, although it may be flawed. Can anyone confirm or clarify this further? @psealock @joshuatf @adrianduffell

**Comment by joshuatf** [comment]
I think that's a great summary of the issues @joelclimbsthings.  💯 

From a technical perspective, if we don't want to be bound to both WCPay and WooComerce Admin release cycles, then we need to host a script elsewhere like WCCOM.  That process looks like this:

1. Publish component changes to WCCOM.

Both WooCommerce Admin and WCPay are already consuming this component via SlotFill so no further steps are required.  If we don't do this then the component probably should live inside WCPay which would require:

1. The component to be published first by WCPay.
2. Bump version of WCPay in WooCommerce Admin.
3. A new version of WooCommerce Admin needs to be published.
4. WooCommerce would need to bump to the latest WooCommerce Admin.
5. Wait for WooCommerce release to see this component.

>Its easy to draw a conclusion that the configs being implemented this sprint are indeed suggestions from our marketplace, but using that flag to pull down a script is a different beast altogether

@psealock This area is not my forte.  If this is a blocker for hosting the script elsewhere, then we are bound by the above 3 release cycles.  I'm not seeing a way we can circumvent that right now.

**Comment by psealock** [comment]
>I'm not seeing a way we can circumvent that right now.

This seems bound by the WC Admin release cycle because the code is needed before installation of WC Pay. Unfortunately this means some code duplication within WC Pay, which also has this screen.

One solution to that would be a Slot created by WC Pay and filled by WC Admin. This solves the code duplication but still leaves us beholden to the WC Admin release cycle.

At this stage, my vote is to simply duplicate the code in each repo. Thats pretty unfortunate, but I'm seeing diminishing returns relative to the amount of effort required to make this happen.

**Comment by joelclimbsthings** [comment]
> At this stage, my vote is to create a new package that can house the component and be updated at any time and is consumed by WC Admin and WC Pay. 

Agreed. I can finally start looking at refactoring this component into its own package (or an already existing package?). Perhaps it is worthwhile to reach out to those who make these calls on whether it's feasible to host our Slotfill script on WCCOM as well, which would just add an additional step if it's approved.

> There is a challenge in creating a public package for our own benefit.

Could you expand on this, @psealock ? Are you saying that we want to create a private package?

**Comment by psealock** [comment]
>Could you expand on this, @psealock ? Are you saying that we want to create a private package?

No, it will need to be a public package but I was thinking the naming should reflect that this package is only meant to be used for WooCommerce (the company) purposes instead of the community. I probably am overthinking this and some kind of generic name is fine.
