### ISSUE TITLE
[WC Beta Tester] Bug report for version "5.3.0-RC.1"

### ISSUE THREAD

**Issue by larsenlarsson** [woocommerce/woocommerce-admin#6899]
**Describe the bug**
When using the 5.3.0-RC.1, the menu
WooCommerce -> Settings -> Advanced -> Features
is not available when using WooCommerce Admin 2.2.1, so the "new WooCommerce navigation experience" cannot be turned on or off. When it has been activated in WooCommerce 5.2.2 it doesn't show up as before, the menu is not complete and it cannot be turned off again.

**To Reproduce**
1. Go to WooCommerce -> Settings -> Advanced 
2. Submenu "Features" is not available

**Screenshots**
In Version 5.2.2:

<img width="1051" alt="Bildschirmfoto 2021-04-28 um 11 17 29" src="https://user-images.githubusercontent.com/2648926/116379509-5c38bf80-a813-11eb-9189-ab12f0d9bdd9.png">

In Version 5.3.0-RC.1:

<img width="1038" alt="Bildschirmfoto 2021-04-28 um 11 18 34" src="https://user-images.githubusercontent.com/2648926/116379653-82f6f600-a813-11eb-8e2a-a65660f6ad08.png">

**Expected behavior**
Submenu "Features" should still be there and the "new Woocommerce navigation" should still be activated

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by joshuatf** [comment]
@larsenlarsson The new WooCommerce navigation feature is not available in the bundled version of WooCommerce Admin.  Currently this feature is only available in the standalone feature plugin - https://wordpress.org/plugins/woocommerce-admin/

Was the navigation feature active at some point and now that it's disabled it's causing an issue?  Or were you just expecting to be able to toggle it on/off here?

**Comment by larsenlarsson** [comment]
@joshuatf 

I'm using the standalone feature plugin.

When using
WooCommerce Admin 2.2.1
WooCommerce 5.2.2
WordPress 5.8-alpha-50793

I can go to
_WooCommerce -> Settings -> Advanced -> Features_
and activate "**Adds the new WooCommerce navigation experience to the dashboard**".

After using "WooCommerce Beta Tester" and switch to WooCommerce 5.3.0-rc.1 ,
the menu "Features" is not available anymore, the "new WooCommerce navigation" feature is not activated anymore.

See:

https://user-images.githubusercontent.com/2648926/116437613-e867d880-a84d-11eb-8fdb-acdf10852687.mp4

**Comment by joshuatf** [comment]
Thanks for the extra information @larsenlarsson!

It looks like the autoloader will pick out the newer version, favoring the bundled version of WooCommerce Admin in core if both the installed feature plugin version and bundled version are the same.  We're not seeing the navigation feature since the bundled version generally does not turn on as many of the newer features.

In my opinion, the feature plugin should always override the bundled plugin if installed, even if it's an older version.  However there may be pre-existing reasons for this not being the case.  cc @jeffstieler in case you have any insight into this.

On a side note, if you want to force the navigation feature to be available, you can also do so with this PHP snippet:

```php
	add_filter( 'woocommerce_admin_features', function( $features ) {
		if ( ! in_array( 'navigation', $features ) ) {
		  $features[] = 'navigation';
		}
		return $features;
	} );
```

**Comment by jeffstieler** [comment]
The behavior of "use the newest version wherever it is" came with the fixes in this PR: https://github.com/woocommerce/woocommerce-admin/pull/4920

IIRC the previous behavior of "the plugin always overrides core" only happened because of our incorrect usage of the Jetpack Autoloader. I don't know if we'll be able to revert to the old way without either hacking around the autoloader or modifying it to suit our needs.

**Comment by mattsherman** [comment]
Closing this issue. The larger question of whether the plugin should always override core is a separate issue.
