### ISSUE TITLE
"We're here for help" pop-up blocks the screen when clicking on "Add products"

### ISSUE THREAD

**Issue by mattsherman** [woocommerce/woocommerce-admin#7035]
Originally logged to the https://github.com/Automattic/wp-calypso repository by @AtrumGeost on May 2, 2021.

### Steps to reproduce the behavior

1. Install Woo on an AT site (Business plan)
2. Finish the setup wizard
3. Go to WooCommerce > Home
4. In the "Get ready to start selling" checklist click on "Add products"
5. Notice a "We're here for help" message shows which is cropped and blocks the whole screen

#### What I expected to happen

To be able to add products using one of the options on the screen

#### What actually happened

A pop-up message blocked the screen

### Context

A user reported the issue here:

29358084-hc

#### Browser / OS version

- Chrome Version 90.0.4430.93 (Official Build) (x86_64)
- macOS Big Sur 11.3 (20E232)

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Atomic

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It affects to more than one site since I was able to reproduce the issue

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/3696121/116817751-8fd65b00-ab2d-11eb-96bf-cd9f5f819101.mp4

**Comment by mattsherman** [comment]
Workaround posted by @Konamiman on original issue:

Hi, as a workaround while we work on fixing this you can reduce the horizontal size of your browser window and then you'll see a clickable "Got  it" button that will close the popup:

![image](https://user-images.githubusercontent.com/937723/118935217-934e4c80-b94b-11eb-943d-c99fbe9ab283.png)

**Comment by mattsherman** [comment]
This only appears to happen on a Business plan site.

**Comment by mattsherman** [comment]
I think this bug is caused by...

```
.woocommerce-layout__header { width: calc( 100% - 160px); }
```

When, it should be...

```
.woocommerce-layout__header { width: calc( 100% - 272px); }
```

as the admin sidebar is 272px wide. I think this is related to the Nav Unification changes to the sidebar. I will investage further and come up with a fix.

**Comment by mattsherman** [comment]
Since this only affects Atomic sites, the fix for it really should lie in the `wc-calypso-bridge` plugin, specifically the `assets/css/ecommerce.css` file.

Unfortunately, I do not have enough time left to implement and test this fix today, and have a long weekend starting in which I am unavailable. Perhaps somebody else on @woocommerce/isotope can pick this up before I am back.

Since I cannot reproduce this exact issue (the popup does not auto-show for me), and I believe the issue has likely existed since the end of March (and was only reported at the beginning of May), I think that it is reasonable for the fix to wait until next week.

**Comment by ilyasfoo** [comment]
I've looked into this a little as well and was able to reproduce your findings. E-commerce plan users with default settings are not affected because they would have the WooCommerce new navigation enabled, which overrides Nav Unification.

**With new navigation:**

![image](https://user-images.githubusercontent.com/3747241/119482800-dd3d9500-bd86-11eb-9bbf-c34dce65342f.png)

**Without new navigation:**

![image](https://user-images.githubusercontent.com/3747241/119482824-e4fd3980-bd86-11eb-93a3-6956a334c8c0.png)

I think the fix that you've proposed will not affect users with new navigation since its `width` attribute will be overridden by a nested CSS rule `.has-woocommerce-navigation .woocommerce-layout__header` which should take over priority.

Unfortunately, I've also run out of time before getting further, but I'll make sure to continue first thing tomorrow.

**Comment by ilyasfoo** [comment]
>Since this only affects Atomic sites, the fix for it really should lie in the wc-calypso-bridge plugin, specifically the assets/css/ecommerce.css file.

@mattsherman I just figured that we can't use `wc-calypso-bridge` plugin for this fix because it would only apply to e-commerce plan users. As far as I tested, business plan users do not get `ecommerce.css` loaded (or any of the `wc-calypso-bridge` features) unless I'm missing something. I think the only path moving forward would be to apply it in `wpcomsh`, even though I feel it isn't ideal.

Do let me know if you have any suggestions, I would make the fix.

**Comment by mattsherman** [comment]
@ilyasfoo The `wc-calypso-bridge` does load on Business plan sites. But, it loads a different main class, which is probably why `ecommerce.css` doesn't get loaded. See: `wc-calypso-bridge.php#L69`, which is where `store-on-wpcom/class-wc-calypso-bridge.php` gets loaded.

You could probably modify that "Store" (certainly a misnomer now) version of the bridge to enqueue a stylesheet that fixes this.

**Comment by ilyasfoo** [comment]
@mattsherman Thank you for clearing that up! I've made a PR in bridge https://github.com/Automattic/wc-calypso-bridge/pull/680.

**Comment by moon0326** [comment]
@ilyasfoo I've reviewed and approved the PR 👍

**Comment by ilyasfoo** [comment]
I have just realized my fix breaks width < 961px because of the greedier CSS ruling:

![image](https://user-images.githubusercontent.com/3747241/120608087-63db2c00-c483-11eb-881e-7ded81540387.png)

Fix incoming soon.

**Comment by samueljseay** [comment]
This issue is interesting. I believe this modal is the cause of intermittent e2e failures on the payment tasks as well. 🤔

**Comment by ilyasfoo** [comment]
@samueljseay I wouldn't think so, because this bug only affects Atomic sites due to nav unification. I believe the modal bug in 7093 is caused by a different issue.
