### ISSUE TITLE
Fatal error when deleting sub-sites (relates to Action Scheduler)

### ISSUE THREAD

**Issue by barryhughes** [woocommerce/woocommerce-admin#7141]
**Describe the bug**

If WooCommerce is network activated, and a sub-site is deleted, a fatal error may be triggered **and the sub-site will not be deleted**. This seems to stem from WC Admin's use of Action Scheduler, within the context of the `'remove_user_from_blog'` action.

When this happens, the customer will typically see the WC Fatal Error Handler's standard _"There has been a critical error on this website. Please check your site admin email inbox for instructions"_  message. 

<details>
<summary>The actual fatal error can be seen here.</summary>

```
Uncaught RuntimeException: Error saving action: Table 'wc_local.wp_4_actionscheduler_actions' doesn't exist 
    in /.../plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:85

Stack trace:
#0 /.../plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): 
   ActionScheduler_DBStore->save_action(Object(ActionScheduler_Action))

#1 /.../plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): 
   ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action))

#2 /.../plugins/woocommerce/packages/action-scheduler/functions.php(36): 
   ActionScheduler_ActionFactory->single('wc-admin_delete...', Array, 1623176003, 'wc-admin-data')

#3 /.../plugins/woocommerce/includes/queue/class-wc-action-queue.php(44): 
   as_schedule_single_action(1623176003, 'wc-admin_delete...', Array, 'wc-admin-data')

#4 /.../plugins/woocommerce/packages/woocommerce-admin/src/Schedulers/SchedulerTraits.php(311): 
   WC_Action_Queue->schedule_single(1623176003, 'wc-admin_delete...', Array, 'wc-admin-data')

#5 /.../plugins/woocommerce/packages/woocommerce-admin/src/Schedulers/CustomersScheduler.php(177): 
   Automattic\WooCommerce\Admin\Schedulers\ImportScheduler::schedule_action('delete_user', Array)

#6 /.../wp-includes/class-wp-hook.php(294): 
   Automattic\WooCommerce\Admin\Schedulers\CustomersScheduler::schedule_user_delete(1)

#7 /.../wp-includes/class-wp-hook.php(316): 
   WP_Hook->apply_filters('', Array)

#8 /.../wp-includes/plugin.php(484): 
   WP_Hook->do_action(Array)

#9 /.../wp-includes/ms-functions.php(261): 
   do_action('remove_user_fro...', 1, 4, 0)

#10 /.../wp-includes/ms-site.php(830): 
   remove_user_from_blog(1, 4)

#11 /.../wp-includes/class-wp-hook.php(292): 
   wp_uninitialize_site(Object(WP_Site))

#12 /.../wp-includes/class-wp-hook.php(316):
   WP_Hook->apply_filters('', Array)

#13 /.../wp-includes/plugin.php(484): 
   WP_Hook->do_action(Array)

#14 /.../wp-includes/ms-site.php(259): 
   do_action('wp_uninitialize...', Object(WP_Site))

#15 /.../wp-admin/includes/ms.php(97): 
   wp_delete_site(4)

#16 /.../wp-admin/network/sites.php(145): 
   wpmu_delete_blog(4, true)
```
</details>

See also [Action Scheduler #699](https://github.com/woocommerce/action-scheduler/issues/699): this bug was initially reported there, but on review I feel it's best handled from WC Admin (but, if after further review you disagree, then please do let me know!).

**To Reproduce**

1. Create a multisite network with at least one sub-site (do not directly activate anything there). Network activate WooCommerce.
2. Delete that sub-site.
3. See fatal error.

**Expected behavior**
The fatal error would not occur, and the sub-site would be deleted.

**Additional context**
Some detail as to why I think this is a problem in WC Admin, vs Action Scheduler itself (admittedly, it's somewhat debatable):

* WC Admin [hooks into the `'remove_user_from_blog'`](https://github.com/woocommerce/woocommerce-admin/blob/v2.3.1/src/Schedulers/CustomersScheduler.php#L34) action, which is fired for all users belonging to the blog being deleted.
* Before the callback fires, WP changes context to that of the sub-site (ie, via a call to `switch_to_blog()`). Consequently, the WPDB table prefixes are those of the sub-site, not the primary site.
* WC Admin then tries [to schedule an action](https://github.com/woocommerce/woocommerce-admin/blob/v2.3.1/src/Schedulers/SchedulerTraits.php#L311) but Action Scheduler will try to use tables that do not exist (because they haven't been created within the sub-site).

My feeling is—again, let me know if you disagree—that it is the responsibility of WC Admin, as the component hooking into `'remove_user_from_blog'`—to be aware of this and ensure the action is scheduled in the context of the parent site.

**Comment by louwie17** [comment]
Thanks for creating this issue in WooCommerce Admin @barryhughes, it is indeed an issue with our code.
I did some further research, and it appears the `CustomersScheduler.php` action is what breaks it, in particular the change added in this PR: #6574, which adds the `remove_user_from_blog` action as you mentioned above. Reverting this change allows a site to be deleted correctly.

One thing to note, this issue only happens when you haven't visited the new site's dashboard yet, once you visit the site it can be deleted correctly.

Maybe the above action should only be added if the `action_scheduler/migration_hook` has finished or started?

cc: @joshuatf as he worked on the original PR.

**Comment by joshuatf** [comment]
Thanks for the issue and detailed context, @barryhughes!

Just to make sure I understand the issue fully, this is stemming from:
* Action Scheduler has not yet created tables when a new network site is created.
* Hooking into any action/filter that uses `switch_to_blog()` sets Action Scheduler to use that site's table prefixes.
* In this case, the Action Scheduler tables for that site have not yet been created, so an error occurs.

Does that sound right?

I'm happy to put a fix in WooCommerce Admin for this, but if my understanding of the above is correct this seems like it should be handled in Action Scheduler for the following reasons:
* A consumer of Action Scheduler should only need to focus on consumable methods from Action Scheduler.  The setup process of Action Scheduler seems like business logic that should stay housed in Action Scheduler (or possibly not exposing the scheduling methods if they are not able to be used).
* A plugin concerning itself with the business logic of another is brittle and prone to bugs.  For example, Action Scheduler actions historically were not stored in the current tables (they were stored in the `wp_posts` table IIRC) and have the potential to change again in the future.
* There are probably a number of other cases where network hooks can be fired prior to Action Scheduler setup.  Instead of repeating this logic across a number of consumers and methods using network hooks, it would be great to have it at the source in Action Scheduler.

Please let me know if my understanding of the above is not correct or any of these points need clarification.

**Comment by barryhughes** [comment]
Thanks for checking it out, @joshuatf!

It may not be a binary choice between fixing the problem in Action Scheduler vs fixing it here in WooCommerce Admin—instead it might be the case that adjustments are merited in both locations. For example, here's a scenario where the fatal error is avoided:

* WooCommerce is network activated.
* A subsite is created (let's suppose the db prefix for the new subsite is `wp_10_`).
* An admin visits the subsite dashboard to set things up and, in the process, various other tables are created.
    * We will now have a set of Action Scheduler tables, such as `wp_10_actionsheduler_actions`
    * We will also have various lookup tables, like `wp_10_wc_order_stats`
* If the network admin now deletes that site, no error takes place (because this time, when the callback we discussed executes and the site has switched to use `wp_10_`, the relevant tables all exist).

However, if my reading of things is correct, there is still a problem for WC Admin in the above—because if the current context is that of the subsite (`wp_10_*`) then _that_ is where the action will be scheduled. However, that site is in the process of being deleted and so, in all probability, the action will never execute.

Given that, doesn't it make sense for the caller to change the context to that of the parent site, if it wants to be sure the action will execute? I'm not sure Action Scheduler can safely or reliably infer that that is what you want to do.

**Comment by joshuatf** [comment]
>An admin visits the subsite dashboard to set things up

@barryhughes Potentially stupid question, but curious why Action Scheduler doesn't set up those tables on a site install hook like `wp_insert_site`.

It seems like any functions making use of Action Scheduler after `wp_insert_site` or on any site deletion hooks where a race condition is imminent will face a similar issue.

>However, that site is in the process of being deleted and so, in all probability, the action will never execute.

That's a good point.  What do you think the logic in WooCommerce Admin should be in order to prevent this?

My current WIP solution would be to hook in to the latest possible hook and the highest priority and run any remaining actions before those tables get deleted.  But this logic feels like it belongs in Action Scheduler.

I'm open to alternatives if you have a better way of handling clean-up for actions on those deleted sites.

**Comment by barryhughes** [comment]
> Potentially stupid question, but curious why Action Scheduler doesn't set up those tables on a site install hook like wp_insert_site.

I'm not sure—would need to dig in some more and feel that out. 

It's worth noting though that when a new site is created, all of the expected core WP tables are also created (everything except the user and user meta tables, in essence)—but we don't see any custom tables from AS **or** WC until a later point.

So, for instance, in a completely hypothetical situation where we replace the attempt to schedule an action (in the `'remove_user_from_blog'` callback) with a query against the `wc_orders_stats` table, we'd see basically the same error (if we re-used the steps to replicate from the opening post). Of course, there's no reason we'd do that—but I just mean it as an illustration of the fact that AS isn't doing anything particularly atypical in respect of table creation.

> My current WIP solution would be to hook in to the latest possible hook and the highest priority and run any remaining actions before those tables get deleted. But this logic feels like it belongs in Action Scheduler.

It looks to me like all of this is all happening within the context of a call to `wp_uninitialize_site()` and, before that function is even finished, `remove_users_from_blog()` will have been called and all of the site's tables will have been deleted.

Seen through that lens, I think it's more the case that Action Scheduler is the wrong tool for the job **unless** you want the async task to run in the context of the primary/parent site, of course. I'm not sure if you do—but if you do, you'd want to switch back to that blog before scheduling the action.

Does that make sense? I could be misunderstanding the role of your async task.

**Comment by joshuatf** [comment]
>but I just mean it as an illustration of the fact that AS isn't doing anything particularly atypical in respect of table creation.

That's a fair point @barryhughes.

>Seen through that lens, I think it's more the case that Action Scheduler is the wrong tool for the job

Typically, when only a user is being deleted and the whole site is not being deleted, it is the tool we'd want to use.

However, in this case, we really don't even need to delete the user assuming the blog deletion is successful.

It doesn't appear there are any flags defining when a site deletion is in progress, but maybe we can hook in early in WooCommerce Admin and create one.  When a site deletion is occurring, we can skip scheduled actions altogether, which circumvents both the uninitialized table issue and unfinished queue issue.

**Comment by barryhughes** [comment]
> Typically, when only a user is being deleted and the whole site is not being deleted, it is the tool we'd want to use. However, in this case, we really don't even need to delete the user assuming the blog deletion is successful.

Makes perfect sense; I was a little unsure if you still wanted to do _something_ (whether moving some metrics to network level, or something along those lines) but it sounds like there is no need. 

> It doesn't appear there are any flags defining when a site deletion is in progress

Not verified, just a bit of spit-balling, but I wonder if you could do something like this within the `remove_user_from_blog` callback:

```php
// Sub-site is being deleted, we don't need to do anything else.
if ( doing_action( 'wp_uninitialize_site' ) ) {
	return;
}

// Existing logic...
```

**Comment by joshuatf** [comment]
That may work, definitely worth giving a shot.  Thanks for the discussion and ideas @barryhughes!

**Comment by christofervas** [comment]
Was this merged on WooCommerce 5.5.1? Because I still get a fatal error when I try to delete a user or a subsite [#30266](https://github.com/woocommerce/woocommerce/issues/30266)

**Comment by louwie17** [comment]
> Was this merged on WooCommerce 5.5.1? Because I still get a fatal error when I try to delete a user or a subsite [#30266](https://github.com/woocommerce/woocommerce/issues/30266)

I originally thought we added it to the `2.4` patch release for wc-admin, but that is not the case. This will be in wc-admin `2.5`, which will be included in WC `5.6.0`.

**Comment by christofervas** [comment]
Thanks for the quick respond @louwie17. Just to be sure, I also get the fatal error [#30266](https://github.com/woocommerce/woocommerce/issues/30266) when I am trying to delete a user (WooCommerce is activated only on main site). Will this fix take care of it?

**Comment by louwie17** [comment]
> Thanks for the quick respond @louwie17. Just to be sure, I also get the fatal error [#30266](https://github.com/woocommerce/woocommerce/issues/30266) when I am trying to delete a user (WooCommerce is activated only on main site). Will this fix take care of it?

Hi @christofervas, sorry for the late reply on this one. I tried reproducing the error you mentioned for deleting a user (on the broken version), but wasn't able to, as I was able to reproduce the error for deleting the sub site.
Would you have some exact steps that show the error when deleting a user?

The steps that I tried that worked fine (on a new multi site install with WC 5.5.1):
- Go to **Network admin > Users** and create a new users
- Go to **Network admin > Users** and delete the newly created user (it deletes fine)

- Create a new subsite in **Network admin > Sites**
- Go to the new subsite dashboard
- Create a new user for the sub-site -> **Users > Add New**
- Go to **Users > All Users** and remove this user (user removed fine).

**Comment by christofervas** [comment]
Hey @louwie17, thanks for your reply. Is the WooCommerce activated only on the main site (and maybe never network activated)?

1. Go to Network admin > Users and create a new user.
2. Create a new subsite in Network admin > Sites and assign the new user.
3. Go to Network admin > Users and delete the user with the option "Delete all content." selected.
4. I get this [#30266](https://github.com/woocommerce/woocommerce/issues/30266) fatal error.

**Comment by louwie17** [comment]
Thanks @christofervas for the detailed steps. I was able to reproduce it this time even with the fix of this issue.
Although the issues do seem to be related, given the fix for this didn't fix the other, I opened a new issue -> https://github.com/woocommerce/woocommerce-admin/issues/7398

Thanks for following up on this :)
