### ISSUE TITLE
Remove tasks/status endpoint

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7372]
After is resolved, the `/wc-admin/onboarding/tasks` endpoint contains redundant information about tasks.

This issue will involve:

* Removing the endpoint `/wc-admin/onboarding/tasks`
* Removing the selector `getTasksStatus`
* Using the `getTasks` data selector from https://github.com/woocommerce/woocommerce-admin/issues/7370 in various components that previously used `getTasksStatus`

Notes:
- A large part of what this endpoint conveys is various properties that are _for the most part_ used in tasks, but also may be used elsewhere. They're also not provided by the `GET /tasks` endpoint. For example, the activity panel uses `hasHomepage`, `automatedTaxSupportedCountries` & `themeMods`. We'll need to figure out how to source this information elsewhere before removing this endpoint.

**Comment by joelclimbsthings** [comment]
Looking at this a little closer, it really looks like there isn't _exactly_ a lot of redundancy here. 

The `/tasks/status` endpoint relays a number of miscellaneous properties (ie `hasHomepage`, `hasPaymentGateway`, `hasPhysicalProducts`, etc) that are often used for tasks, but are not currently provided by the `/tasks` endpoint. In some cases I can't really see that these are used for tasks currently at all, so we've probably just added properties to this over time that were needed in other circumstances. 

Instead of removing this endpoint, we might clean it up (remove unused properties), and rename it to something more intuitive? It doesn't relay "task status" in a way we would expect at this point, but it does relay a few properties that are useful and in use currently. 

Something like `GET onboarding/settings` might be clearer, although I do fear that this just becomes a catch-all for misc properties that we need in various places. 

Thoughts @joshuatf @louwie17 ?

**Comment by joshuatf** [comment]
>The /tasks/status endpoint relays a number of miscellaneous properties (ie hasHomepage, hasPaymentGateway, hasPhysicalProducts, etc)

Good point, @joelclimbsthings.  `hasHomepage` is used inside the task itself.  Maybe this task should be responsible for fetching that setting/option.

The other two options I think are just used for completion checking and will no longer be needed.

There may other cases, but I'd favor removing them wherever possible.

>although I do fear that this just becomes a catch-all for misc properties that we need in various places. 

My fear as well.  If we can move responsibility to the task itself, I think we may still be able to clear this endpoint.

>It starts to sound like something more of a cool-down task, given that a lot of the usage that I see doesn't really involve tasks.

I'm also okay if this moves to cooldown.  It is not imperative to get the new task list REST API working.

**Comment by joelclimbsthings** [comment]
> My fear as well. If we can move responsibility to the task itself, I think we may still be able to clear this endpoint.

Only issue here is that a few of these _are_ utilized elsewhere. For example, the activity panel uses `hasHomepage`, `automatedTaxSupportedCountries` & `themeMods`. It might be fairly limited, so we'd just have to audit these props and figure out if there's a better way to source that data in other components. 

I'll add some notes to the description for this issue, and mark it as a cool-down task. I'm glad to take a look at it next week.

**Comment by mattsherman** [comment]
@joshuatf @joelclimbsthings Is this issue still valid? Is it something we need to do right now?

**Comment by joshuatf** [comment]
This issue is still valid but not urgent for the performance of the task list.

The issue as @joelclimbsthings mentioned is that some other components still use this task status and will need to be updated before the endpoint can be removed.  From what I can see the only components using this are the activity panel and the task fills.  Adding an `additional_info` property to tasks that gets passed via the endpoint could allow a lot of flexibility and resolve this.

I'd like to tackle this, but I'm also aware it may cut into cycle 18 work by a day or two.
