### ISSUE TITLE
Please install WooCommerce & try again after uninstalling woocommerce

### ISSUE THREAD

**Issue by ukenpachi** [woocommerce/woocommerce-admin#7441]
### To Reproduce

I uninstalled woocommerce on my website however after uninstalling it. I am unable to access the site anymore. All I get is a whitespace saying **Please install WooCommerce & try again** but how can I install it when I cannot access anything else? 

### Screenshots

![image](https://user-images.githubusercontent.com/5822229/127583985-8cc5b7fc-39cf-4c8a-b5f6-7cc6f23dbf07.png)

**Comment by samueljseay** [comment]
@ukenpachi I'm so sorry you're experiencing this problem, thats super frustrating.

I was going to transfer this issue over to our main WooCommerce repo but before doing that I want to make some suggestions:

1. I have a high suspicion that this message "Please install WooCommerce & try again" is actually not coming from WooCommerce but probably from another plugin that expects WooCommerce to be installed and is crashing because its not there.

2. It is possible to deactivate all your plugins if you have access to the plugin directory on your site, this would allow you to try and narrow down which plugin is causing the problem. These instructions should help: https://wordpress.org/support/article/common-wordpress-errors/#the-white-screen-of-death but will only help if you have file access to the server you're running WordPress on.

If you can successfully do `2` then you can reinstall and activate the plugins you need one at a time (probably avoid any plugins that are woo related).

**Comment by ilyasfoo** [comment]
Closing this as no feedback was received from the author.
