### ISSUE TITLE
Exporting Orders from Analytics is not being sent by email when filtering by a specific product

### ISSUE THREAD

**Issue by ahmedzeidan** [woocommerce/woocommerce-admin#7584]
When exporting orders from the Analytics Tab, it works well for all orders for example or any other form of export. The issue is when filtering to a specific SKU/Product to export its orders data, it triggers `woocommerce_admin_email_report_download_link ` successfully but not getting the exported file by email. Also, the email log plugin is not showing any trace of an email sent out.

To Reproduce the Issue: I have tested this on Live and Staging. The staging has no plugins installed except for woocommerce only and still got this issue when exporting the Orders data for a specific product.

Any help would be appreciated here.

Thanks...

**Comment by shohanhossainnab** [comment]
Couldn't reproduce this on my end.

**Comment by ilyasfoo** [comment]
Hi @ahmedzeidan, thank you for reporting this issue! You're right, it seems analytics email export does not work with product filter.

I was able to reproduce it by the following steps:

1. In a fresh site where you can receive notification emails from, create at least 1 product.
2. Create at least 20 orders with the product.
3. Go to Analytics > Orders.
4. Add "Product" filter, set to the product that has at least 20 orders and filter it.
5. In the table below, click on Download.
6. Observe a snackbar with the message "Your Orders Report will be emailed to you." appears.
7. Wait for a while and notice that you're not receiving any emails.
8. To confirm, clear the filter and try to download again.
9. Wait for a while and see that you can receive email reports without filters.

**Comment by ahmedzeidan** [comment]
Thanks @ilyasfoo for confirming that the error can be re-produced... I was able to temporarily get around this by exporting a report for the whole store then filtering the CSV file manually.

Exporting less than 20 orders will download the CSV file directly.

Looking forward to a future fix...

**Comment by gabrielbonifacio** [comment]
Also reported on 4432754-zen.

### To Reproduce

1. Go to **Analytics → Products**.
2. Select a date range that shows some products on the results. In my test, I selected `Year to date`.
3. Look for a product with some orders associated with it. Click on the link with the number of orders ("Orders" column) to open the Orders report for that specific product - I worked with a product that had 5 orders.
4. On the Orders report, click on the `Download` button.

### Actual behavior:

A message `Orders Report will be emailed to you` shows up on a tooltip on the bottom left corner of the screen. No emails are actually sent - I checked that both by looking at my inbox and WP Mail Logging, which shows that no email was actually sent.

### Screenshots

![https://d.pr/i/zkKV46](https://d.pr/i/zkKV46+)
_Link to image: https://d.pr/i/zkKV46_

![https://d.pr/i/jLZjpG](https://d.pr/i/jLZjpG+)
_Link to image: https://d.pr/i/jLZjpG_

### Expected behavior

The email with the CSV report attached should have been sent to the email associated with the account I'm logged into.

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Chrome
* Version: 95.0.4638.69 (Official Build) (x86_64)

**Comment by selectedselections** [comment]
Also reported in 4461131-zen

**Comment by ahmedzeidan** [comment]
the issue seems resolved on the latest WC version as testing to export products went through and got it by email... Thanks for the support here.

**Comment by imanuelgittens** [comment]
I'm getting this issue in WooCommerce version 6.0.0. I see the scheduled action but no email is sent. I checked my sendgrid activity and inbox and I see no email. @ahmedzeidan did you change anything to get it to work?

**Comment by ahmedzeidan** [comment]
> I'm getting this issue in WooCommerce version 6.0.0. I see the scheduled action but no email is sent. I checked my sendgrid activity and inbox and I see no email. @ahmedzeidan did you change anything to get it to work?

@imanuelgittens  I did nothing to make it work,,, Try to check your schedule status as it could be stuck there... a workaround is to export all the store's numbers and filter that in manually.
