### ISSUE TITLE
Add global mobile property to Tracks

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7644]
### Is your feature request related to a problem? Please describe.
Currently all mobile devices are separated by [device OS in Tracks](https://mc.a8c.com/tracks/trends/?compareby=prop&eventname=wcadmin_tasklist_add_product&interval=day&prop=deviceos&startdate=20210807&stat=uniques). This makes it challenging to have a holistic view of all mobile behavior to make improvements to mobile web and improve alignment between core and mobile.

### Describe the solution you'd like
For better visibility of mobile usage, we want to combine all of these into one global `mobile` property in Tracks. This property will include tablet devices.

**Comment by mattsherman** [comment]
@elizaan36 Would the `devicefamily` property suit your needs? It groups things into "Mac", "iPhone", "iPad", "Other", etc.

If not, we would need to come up with a definitive list of what OSes we consider mobile vs desktop. We might want to do this on the backend, in Tracks too, instead of adding this logic to WooCommerce directly. It's something we should probably discuss with the Tracks/Data developers to determine what would be the best solution to accommodate our needs.

**Comment by elizaan36** [comment]
Thanks for this suggestion, Matt! Is there anyone on the Tracks/Data team that we could ping and ask on this issue?
@Garance91540 to confirm, but I think `devicefamily` would still require a decent amount of manual work.

**Comment by mattsherman** [comment]
> Thanks for this suggestion, Matt! Is there anyone on the Tracks/Data team that we could ping and ask on this issue?

@elizaan36 I'll DM you a few suggestions on who to ping.

**Comment by mattsherman** [comment]
Update: I'll dig into this a bit more and reach out to the Tracks team to see how to best accomplish this.

**Comment by mattsherman** [comment]
I've posted a question to discuss the best approach for this: p4qSXL-45Y-p2
