### ISSUE TITLE
OBW: Post Code should not be a required field

### ISSUE THREAD

**Issue by lanej0** [woocommerce/woocommerce-admin#7782]
### Describe the bug
There are a number of countries that don't use zip/postal codes. There are a number of documented exceptions [here](https://tosbourn.com/list-of-countries-without-a-postcode/) and [here](pn5zZ-1A-p2).  Additionally, officially, there may be postal codes in use but most folks don't actually use/know them (Ireland for example).  As such, the Postal Code field should be optional/non-blocking during the Setup Wizard.

It could be bypassed by entering any non-blank value (for example, "1" is accepted as a valid postal code).

### To Reproduce

1. Go to /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard
2. Complete Address Line 1
3. Select a country (I'd suggest Aruba as they have no postal codes)
4. Leave Postal Code blank

### Actual behavior:

The continue button is disabled.  Removing focus from the Post code field highlights it and yields the message "Please add a post code"

### Screenshots

![Screen Shot 2021-10-11 at 11 39 06 AM](https://user-images.githubusercontent.com/80276/136838593-5389a9da-18d8-4a34-b038-14d602d53d15.png)

### Expected behavior

Post code should be an optional field and allow continuing with the Setup Wizard flow with a blank value (similar to Address line 2).  An alternative would be to conditionally make this field required if a country employs postal codes/zip codes.  I think that's less desirable because it's a barrier for individuals who don't know their postal codes!

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Chrome
* Version: 94.0.4606.71

## Dev notes

These can/should be separate PRs if possible:

- Will require a new endpoint
- Will require a new data store
- Labels
- Required

Details:
- Prioritize handling postal code first
- Handle other fields if possible
- Probably push the field ordering/priority to a future story

**Comment by elizaan36** [comment]
Thank you @lanej0 ! This is a great issue to bring up, and something our team has chatted about in the past. 

Taking a little step back, there's another UX issue where users need to scroll endlessly through the Country/Region list in order to find their location.

I'd propose the following solution - use progressive disclosure and only surface the address and country fields fields first, then present the remaining fields dynamically based on the country chosen. If the country doesn't use postal codes, this field would be marked as optional.

![Screen Recording 10-15-2021 at 2 53 PM](https://user-images.githubusercontent.com/5121465/137538925-74d394bc-c9b1-4bb0-984a-3ff5c8bade55.gif)

Thoughts on this?

**Comment by lanej0** [comment]
@pmcpinto That's a good idea too.  I have to admit that there are times (usually soon after I had moved houses) where I didn't know my postal code.  I could look it up, but would I be motivated to do so when signing up on a website?

**Comment by mattsherman** [comment]
> I'd propose the following solution - use progressive disclosure and only surface the address and country fields fields first, then present the remaining fields dynamically based on the country chosen. If the country doesn't use postal codes, this field would be marked as optional.
> 
> ![Screen Recording 10-15-2021 at 2 53 PM](https://user-images.githubusercontent.com/5121465/137538925-74d394bc-c9b1-4bb0-984a-3ff5c8bade55.gif)
> 

@elizaan36 This mockup shows a separate state field, and the state and "zip code" (post code) fields on the same line, which is not how the form is currently implemented. I'm just double-checking that these design changes are not expected to be part of this specific fix.

<img width="513" alt="Screen Shot 2021-12-12 at 08 06 42" src="https://user-images.githubusercontent.com/2098816/145713595-e5679f55-8217-4846-8585-bca4fa332db8.png">

I think the basic progressive disclosure idea still will work well, as specified. Ideally, in the future, we could take things further and further tailor this form to specific locales by putting the "Country/Region" first, above the address lines (since the intent for those can vary based on locale).

**Comment by elizaan36** [comment]
> I'm just double-checking that these design changes are not expected to be part of this specific fix.

**Comment by mattsherman** [comment]
Location in WooCommerce core where the country locale information is available. This is where whether postal code (and other address fields) is required and what they should be labeled:

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-countries.php#L795-L1546

@pmcpinto @elizaan36 This brings up a related point... this issue specifically refers to just post code, but:

1. There are locales where other address fields are not required
2. In some locales, the address fields have different names (for example, in the US "post code" is "ZIP code"
3. In some locales, the order of the address fields are different

We should consider a future followup story to enhance the localization of the address fields in the OBW.

**Comment by elizaan36** [comment]
Ideally the post code/zip code field would localize based on the country/region selected. Is that not possible as part of this work?

I'm not too worried about the order of address fields or locales where address fields aren't required.

**Comment by mattsherman** [comment]
> Ideally the post code/zip code field label would localize based on the country/region selected. Is that not possible as part of this work?

I think that the implementation required to make post code conditionally optional will get us most of the way to localizing the field labels as well. But, that seems like a distinct/larger issue. We could change this story to encompass that if agreed. /cc @pmcpinto 

> I'm not too worried about the order of address fields or locales where address fields aren't required.

Localized address formats are super "fun"... I agree that it isn't an immediate concern, but I'd love to see more complete localization support in this area in the future.

**Comment by pmcpinto** [comment]
> I think that the implementation required to make post code conditionally optional will get us most of the way to localizing the field labels as well. But, that seems like a distinct/larger issue. We could change this story to encompass that if agreed. /cc @pmcpinto

I think this and other suggestions should be part of a follow-up story, as most likely we'll have significant changes to the profiler during Q1 (eg.: merging the profiler with the wcccom nux).

**Comment by elizaan36** [comment]
@pmcpinto To confirm, any additional localization efforts beyond the Post code label would be outside the scope of this issue? @mattsherman mentioned that the implementation would get us most of the way there for the label change anyway.

**Comment by joshuatf** [comment]
My vote is for handling this all at once (optionally over multiple PRs but I'd like to see it done in the same sprint).  The information required for localizing all fields and various requirements is contained in https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-countries.php#L795-L1546

The more time consuming portion of this is creating a REST API and potentially a data store to retrieve this information.  Since we are already carrying the mental overhead for changes in some of the step, I don't think it's much a stretch to get all the fields working as expected in different locales.

**Comment by pmcpinto** [comment]
>  Since we are already carrying the mental overhead for changes in some of the step, I don't think it's much a stretch to get all the fields working as expected in different locales.

That is a good point. What will be the difference in terms of effort to implement it altogether?
