### ISSUE TITLE
The source of `@woocommerce/settings` processed by DEWP is confusing

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#7810]
### Describe the bug

As a plugin developer, I tried to use Dependency Extraction Webpack Plugin to use a package to obtain the WooCommerce settings. (https://github.com/woocommerce/pinterest-for-woocommerce/pull/224, https://github.com/woocommerce/google-listings-and-ads/issues/1050)

I checked that `wc.wcSettings` delivers the data I need. So I checked the [README of DEWP](https://github.com/woocommerce/woocommerce-admin/blob/main/packages/dependency-extraction-webpack-plugin/README.md) to check which plugin I should actually import in my local `package.json`, and which package I should inspect to check its API and behavior. README states:
> <table>
> <tr>
> 	<th>Request
> 	<th>Global
> 	<th>Script handle
> <tr>
> 	<td><code>@woocommerce/settings</code>
> 	<td><code>wc['wcSettings']</code>
> 	<td><code>wc-settings</code>
> </table>

But the thing is, it's not the [`@woocommerce/settings`](https://www.npmjs.com/package/@woocommerce/settings). It is `wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-settings.js`

Which AFAIK is not published anywhere, therefore, could not even be my plugins dependency.

### To Reproduce

1. Install and setup Woo DEWP on your plugin repo.
2. Add `import foo from @woocommerce/settings`
3. Install locally `npm install --save @woocommerce/settings`
4. Run unit tests

### Actual behavior:

The local `@woocommerce/settings` package is different than externalized.

### Expected behavior

The README points to the exact package that would be externalized. 

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by psealock** [comment]
Hi @tomalec 

The `@woocommerce/settings` is a webpack alias in wc-admin and probably blocks too 😭 . What data are you trying to access?

This is a huge area of technical debt with [perhaps some changes coming](woocommerce/woocommerce#32208) and these decisions continue to haunt us. Sorry for the confusion. 

You can get data that is added on page load using `wc.wcSettings.getSettings` directly. However, we have stepped away from that because you can't guarantee the data is up to date. Instead, the data package is preferable https://github.com/woocommerce/woocommerce-admin/tree/main/packages/data/src/settings

Hope this helps.

**Comment by joelclimbsthings** [comment]
It looks like this issue is redundant with ongoing efforts to improve the technical debt in this area. Closing for now.
