### ISSUE TITLE
Payments task - Tracks issues

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7836]
**Description:** the finance team spotted some weird trends in the Tracks events we're using to track the payment's method selection:

`wcadmin_tasklist_payment_setup`
`selected` prop

There's a strange drop after June 8. The numbers started ramping up again on Sep 22, but they're still way below what we were seeing before the drop:
![screen-shot-2021-10-21-at-3.52.27-pm.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/1cff86a8-9456-4502-8383-b316c93d1cb0)

`wcadmin_tasklist_payment_connect_method`
`payment_method` prop

Around the same time, COD jumped significantly on June 9 2021 and then around mid-August 2021 all payment_methods except ‘cod’ and ‘bacs’ dropped to low single digits.

![screen-shot-2021-10-21-at-3.47.06-pm.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/6bc7fbe6-5c52-45e5-b17a-8dc43313efbb)

I wonder if this was caused by a bug in the payments task changes to be powered by the remote endpoint.

**Comment by joelclimbsthings** [comment]
@pmcpinto @mattsherman 
Alright, after looking into this today I've discovered the following for each event:

### wcadmin_tasklist_payment_setup

It looks like the inconsistencies here are largely due to the iteration on the remote payment suggestions feature. Judging from the dates the initial issue cropped up in WCAdmin `2.3.1`, and dropped off in `2.6.0`. A small typo unfortunately lead to this event not being fired at all in `2.3.1`, which was fixed in [this PR](https://github.com/woocommerce/woocommerce-admin/pull/7304).  

After the above issue was fixed you can see the event being fired again starting in `2.6.0`. To bottom out on any further inconsistencies I focused on differences between `2.3.1` and `2.6.0` with WCPay, Bacs, Paypal & Stripe.

**Stripe**: In the previous iteration this event is fired when the Setup button is initially clicked _as well as_ repeat clicks (before it's fully configured). On the newer iteration this event is only fired on the initial click, so that could result in slight differences.

**WCPay**: This event actually isn't being fired at all for WCPay in the newer iteration, I believe due to a flag for the gateway handling it's own setup. 

**Paypal**: Paypal was (probably unintentionally) renamed from `paypal` to `ppcp-gateway` for this event. Behavior the same otherwise.

**Bacs**: There's a slight difference in the two versions in how this is fired for BACS. If an account is already configured before enabling BACS, it will _not_ fire this event on `2.3.1`, but _will_ for `2.6.0`. Probably an edge case and generally you wouldn't have a preexisting account before enabling.

It's worth noting that I didn't find any other reasons way the overall rate would have dropped other than the above variables (which may not account for everything), so it's likely they legitimately dropped, or other factors are at play. I'd be curious if segmenting the data by environment or other relevant variables would reveal anything more.

### wcadmin_tasklist_payment_connect_method

The relevant versions here are `2.3.1`, when COD skyrocketed, and `2.5.0` when most of the gateways went down dramatically.

The first issue is simple - this event wasn't previously fired _at all_ for COD, and now it is as soon as the user hits the toggle, every time they may hit the toggle. 

The second issue is fairly clear as well. When we completed the payment gateway suggestions feature, the "step" that fires this event became dependent on a few simple changes in the various gateways to give us the needed information. 

For instance, look at Stripe. We created [this PR](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1569) to provide us with the `get_required_settings_keys`, `needs_setup`, and other callbacks that are necessary for us to understand how to treat the gateway in the task list. Without that PR being merged it fails to render this step:

![image](https://user-images.githubusercontent.com/444632/138977503-7b87b633-47d8-4d16-b921-9e858fa4f0ac.png)

Which _does_ render as pictured for previous versions. Without that data, we skip that step and the `payment_connect_method` event never ends up firing for those gateways.

To provide the information and render these steps correctly, we have [a list of PRs](woocommerce/woocommerce#32258) in other repos that still need to be merged. 


### Suggested next steps
- Revisit PRs associated with gateway suggestions feature, as detailed on [this issue](woocommerce/woocommerce#32258) (I last commented here about a week ago wondering if we were still responsible for these). 
- Optionally create issue to address why `wcadmin_tasklist_payment_setup` is not fired for WCPay (I assume this is desired?)
- Optionally create issue to find a way to identify PayPal as `paypal` again instead of `ppcp-gateway` for relevant events.
- Optionally create issue to suppress the `tasklist_payment_connect_method` event for COD, if we don't want that to fire as it is now.

**Comment by pmcpinto** [comment]
@joelclimbsthings thanks for investigating this!

> wcadmin_tasklist_payment_setup

Do you think it's safe to use `wcadmin_tasklist_payment_install_method` as a fallback event until we fine-tune `wcadmin_tasklist_payment_setup`? Are they being triggered at the same time?

> Stripe: In the previous iteration this event is fired when the Setup button is initially clicked as well as repeat clicks (before it's fully configured). On the newer iteration this event is only fired on the initial click, so that could result in slight differences.

This is happening with all the extensions, right?

> It's worth noting that I didn't find any other reasons way the overall rate would have dropped other than the above variables (which may not account for everything), so it's likely they legitimately dropped, or other factors are at play. I'd be curious if segmenting the data by environment or other relevant variables would reveal anything more.

The drop seems to be consistent across countries, browsers, devices and OS:

<img width="1414" alt="Captura de ecrã 2021-10-28, às 07 17 45" src="https://user-images.githubusercontent.com/3380168/139241389-f836d4ff-861b-451d-9477-8491c6e8c04d.png">
<img width="1404" alt="Captura de ecrã 2021-10-28, às 07 18 21" src="https://user-images.githubusercontent.com/3380168/139241424-7351dc3e-d16f-4d18-a99a-c1d4b5614d76.png">
<img width="1391" alt="Captura de ecrã 2021-10-28, às 10 46 32" src="https://user-images.githubusercontent.com/3380168/139241448-65e8481c-daa1-4f76-83b7-5dcf2b9ebc37.png">
<img width="1396" alt="Captura de ecrã 2021-10-28, às 11 54 53" src="https://user-images.githubusercontent.com/3380168/139242331-508879e5-18ce-47c1-9ec1-b8222635d3c5.png">

However, if you look at the absolute diff of some other onboarding before and after the issue, the difference is significantly higher with this event. I wonder if there's something else happening apart from the bug that was fixed:

<img width="695" alt="Captura de ecrã 2021-10-28, às 12 00 25" src="https://user-images.githubusercontent.com/3380168/139243450-84aad6e3-5e81-45d4-b9d1-02c15a837cc4.png">

> Revisit PRs associated with gateway suggestions feature, as detailed on this issue (I last commented here about a week ago wondering if we were still responsible for these).

Is this the only way to fix the flow?

> Optionally create issue to address why wcadmin_tasklist_payment_setup is not fired for WCPay (I assume this is desired?)

That would be great. Including WCPay is important to spot trends in installs among other things.

> Optionally create issue to find a way to identify PayPal as paypal again instead of ppcp-gateway for relevant events.

 Sounds good to me. 

> Optionally create issue to suppress the tasklist_payment_connect_method event for COD, if we don't want that to fire as it is now.

let me think about this.

**Comment by pmcpinto** [comment]
@joelclimbsthings do you have feedback on the questions i posted in my previous comment? tks

**Comment by joelclimbsthings** [comment]
Sorry for the delay @pmcpinto , I've been AFK. 

> Do you think it's safe to use wcadmin_tasklist_payment_install_method as a fallback event until we fine-tune wcadmin_tasklist_payment_setup? Are they being triggered at the same time?

There are a couple differences, such as the fact that `wcadmin_tasklist_payment_install_method` isn't fired until after any required plugins are installed successfully. The other, `wcadmin_tasklist_payment_setup` pretty much fires when the button is clicked. So if there are no required plugins, or something goes awry before it's installed successfully, the former won't fire.

That said, in practice these will likely be fairly equivalent for most gateways/scenarios. 

> This is happening with all the extensions, right?

Yes, any plugins that render a "Setup" or "Finish Setup" button will behave the same now.

> However, if you look at the absolute diff of some other onboarding before and after the issue, the difference is significantly higher with this event. I wonder if there's something else happening apart from the bug that was fixed

Yeah, I'm not sure how to quantify how much the other factors I mentioned might influence this. 
- Gateways with "Setup" button (like Stripe), _not_ firing this event for repeat clicks any more. 
- WCPay not firing this at all

I didn't encounter any other clear potential causes for this while parsing through the code.

> Is this the only way to fix the flow?

The [decision was made](p90Yrv-2gW-p2) that the gateway's should own this logic, and really it's the only way to do so elegantly without hard-coding gateway-specific behavior within WCAdmin itself. In short this is hard to get around without making changes in the various plugin repos. 

> That would be great. Including WCPay is important to spot trends in installs among other things.

I'll create this issue now 👍🏻 


    Optionally create issue to find a way to identify PayPal as paypal again instead of ppcp-gateway for relevant events.

> Sounds good to me.

I can create this one as well.

**Comment by pmcpinto** [comment]
@joelclimbsthings thanks for the additional clarifications. The current cycle ends next Monday, so ideally the changes that were mentioned in this thread should be wrapped up during the next cycle. Let me know if you need help unblocking  some of the PRs that need to be merged in the third party plugins woocommerce/woocommerce#32258

**Comment by joelclimbsthings** [comment]
@pmcpinto We may need help in unblocking those PRs, but I'm unsure of the next step(s). I've added another comment on [the relevant PR](woocommerce/woocommerce#32258) to better understand this. 

With all of the above, are we safe to close out this issue?

**Comment by pmcpinto** [comment]
> @pmcpinto We may need help in unblocking those PRs, but I'm unsure of the next step(s). I've added another comment on the relevant PR to better understand this.

@joelclimbsthings I'll add a comment in woocommerce/woocommerce#32258 to follow up on this topic. 

> With all of the above, are we safe to close out this issue?

Yes. I'll close the issue. Thanks!
