### ISSUE TITLE
Business features step: tracks not working with marketing extensions

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7903]
### Describe the bug
The `install_mailpoet` and `install_google_listings_and_ads` of `wcadmin_storeprofiler_store_business_features_continue` are not being fired when the extensions are installed in the Business features step

### To Reproduce

1. Create a new store and opt-in to share usage tracking
2. Fill the store profiler until the business features step
3. Install the Mailpoet and Google Listing and Ads extensions in the business step
4. See that `wcadmin_storeprofiler_store_business_features_continue` fires without the `install_mailpoet` and `install_google_listings_and_ads` event props

### Actual behavior:
Some event props of `wcadmin_storeprofiler_store_business_features_continue` are showing the value `undefined` when the extensions are installed, namely: `install_mailpoet` and `install_google_listings_and_ads`	

### Expected behavior
The value should be true or false, depending if the extension is installed

**Comment by pmcpinto** [comment]
@adrianduffell  @mattsherman is it possible to fix this on time to be included in 2.9? I'm assuming it's already too late to include in 2.8.

The internal teams rely on this data to track the number of people installing the extensions. So the sooner we have this fixed the better. This started happening on Sep 22.
Also, how can we prevent this from happening in the future? Thanks

**Comment by mattsherman** [comment]
@pmcpinto 2.8.0 has already shipped (as well as the corresponding 5.9.0 core release). I would think we could include this in 2.9.0... what do you think, @adrianduffell?

It looks like these props were removed as a part https://github.com/woocommerce/woocommerce-admin/pull/7386, when the grow section was removed from the OBW in favor of the marketing task (which was first included in WCA 2.6.0 on Aug 31, 2021). It looks like MailPoet shouldn't have been removed though.

They should have been added back as a part of https://github.com/woocommerce/woocommerce-admin/issues/7780 when Google Listings and Ads was added back into the OBW.

The way these prop are hardcoded though is less-than-ideal and likely why these were removed improperly and not added back in.

To prevent this from happening in the future, we should:

1. Handle these props in a more robust manner, where they are driven by the extensions specs instead of hardcoded.
2. The acceptance criteria for the removal and reintroduction of these extensions should include a list of any affected Tracks events (this may not be reasonable).
3. Tracks events should be tested somehow, to catch any mistakes earlier. Since this started happening on Sep 22 (with the release of 5.7.0 core), it has been over a month since this has been live. And even longer since it was committed and in pre-release versions.

**Comment by mattsherman** [comment]
I'm assigning to @woocommerce/mothra to fix.

**Comment by adrianduffell** [comment]
> I would think we could include this in 2.9.0... what do you think, @adrianduffell?

Sounds good, I've now added this to the 2.9 milestone.

**Comment by pmcpinto** [comment]
> We could make a quick fix to patch things up for 2.9.0-rc.1 and a more ideal fix to make it more robust for 3.0.0.

Thanks! That would be great
