### ISSUE TITLE
(2.9 Beta 4) Welcome Modal re-appears after dismissed

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#7936]
### Describe the bug
In 2.9 Beta.4, the Welcome Modal re-appears on subsequent page loads after it has been dismissed.

### To Reproduce

1. On a new site, finish the onboarding wizard.
2. See the Welcome Modal and dismiss it.
3. Reload the Home Screen.
4. See Welcome Modal.

### Actual behavior:

Welcome Modal is dismissed but re-appears on subsequent page loads.

### Screenshots
<img width="529" alt="Screen Shot 2021-11-12 at 11 54 19 am" src="https://user-images.githubusercontent.com/9312929/141954617-2e226c46-9209-482f-af7e-301c11007d90.png">

### Expected behavior

Welcome Modal should not re-appear after being dismissed.

### Desktop (please complete the following information):

* OS: macOS
* Browser Safari
* Version: 15

**Comment by joshuatf** [comment]
I was not able to reproduce this issue.  Are there other potential steps involved?  Were there any console errors or issues with the network request to `/options` to dismiss the modal?

**Comment by adrianduffell** [comment]
> Are there other potential steps involved? 

It looks like it could be browser related. I can reproduce it on a fresh JN site using Safari but not on Chrome.

> Were there any console errors or issues with the network request to /options to dismiss the modal?

I don't get any console or network errors. Interestingly, the value of `woocommerce_task_list_welcome_modal_dismissed` is set to `yes`.

I also can't reproduce it on the `main` branch at present.

**Comment by adrianduffell** [comment]
Also, I'm only seeing it intermittently today.

https://user-images.githubusercontent.com/9312929/142096280-36e4c5a5-8e81-4d0f-b640-6e4c015a29a2.mov

**Comment by ilyasfoo** [comment]
I was able to reproduce on the latest main with my safari browser

**Comment by ilyasfoo** [comment]
It seems [`welcomeModalDismissed`](https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/layout.js#L312) had the value `false`, [`welcomeModalDismissedHasResolved`](https://github.com/woocommerce/woocommerce-admin/blob/main/client/homescreen/layout.js#L311) was `true` and suspiciously I couldn't find the network request for `woocommerce_navigation_intro_modal_dismissed` option in networks tab.

Is it possible that a request can be bypassed? Maybe an error in request caches?

**Comment by ilyasfoo** [comment]
I just confirmed this issue is pre-existing, I was able to reproduce it in WooCommerce 5.9 and WCAdmin 2.8.


Something unique I've found out when I'm able to reproduce is one of the options requested without specifying the options, i.e: `https://valuable-bug.jurassic.ninja/wp-json/wc-admin/options?options=&_locale=user`:

![image](https://user-images.githubusercontent.com/3747241/142127896-dcd6fd2c-b760-482e-87f8-3ffcfb8bb3ea.png)

I also noticed if I enable "Ignore resource cache..." in the networks tab, I couldn't reproduce anymore with a JN site, but this doesn't work in my local repo.

**Comment by ilyasfoo** [comment]
I may have found the root cause, it's a race condition where an option put in batch array [here](https://github.com/woocommerce/woocommerce-admin/blob/641b86f90fe126d014fa39ca4a5125fa14aadfb7/packages/data/src/options/controls.js#L25) does not have a chance to be [fetched](https://github.com/woocommerce/woocommerce-admin/blob/641b86f90fe126d014fa39ca4a5125fa14aadfb7/packages/data/src/options/controls.js#L36) before it's being [cleared](https://github.com/woocommerce/woocommerce-admin/blob/641b86f90fe126d014fa39ca4a5125fa14aadfb7/packages/data/src/options/controls.js#L42).

![image](https://user-images.githubusercontent.com/3747241/142139084-4dc9320d-c8b9-42d9-bac0-1433f737708b.png)

I'm still unsure of why this only occurs for Safari

**Comment by adrianduffell** [comment]
Ah that reminds me, this bug has come up before and we found the same race condition https://github.com/woocommerce/woocommerce-admin/issues/7478#issuecomment-895649128

**Comment by ilyasfoo** [comment]
Ah, good catch. I think this should be a priority then because it could cause intermittent issues which is super hard to reproduce.

On top of my head, a quick fix should be, instead of `optionNames = [];` we should carefully remove only options which were fetched. But I'm not sure if this would still be fundamentally unstable

**Comment by adrianduffell** [comment]
> On top of my head, a quick fix should be, instead of optionNames = []; we should carefully remove only options which were fetched. But I'm not sure if this would still be fundamentally unstable

Sounds good, I'm also wondering what the purpose of the `setTimeout` wrappers are and if they are contributing to the issue. I'll investigate this some more.

**Comment by ilyasfoo** [comment]
I think the idea of `setTimeout` there is to batch option request into a single API call, that's why it's also set as only 1 millisecond. It's to get the main thread to execute and possibly gather all option requests that are supposed to happen in a single execution.
