### ISSUE TITLE
Duplicate "Subscriptions" items displayed in the Woo Nav Extensions menu with WCPay installed

### ISSUE THREAD

**Issue by joelclimbsthings** [woocommerce/woocommerce-admin#8014]
### Describe the bug
We currently have two "Subscriptions" menu items, both in the original navigation, and the new navigation, which is leading to confusion when WCPay is installed. 

This is especially an issue on the new Woo Navigation since it's displaying both items side-by-side within the _Extensions_ menu:

![Screenshot from 2021-12-01 16-32-56](https://user-images.githubusercontent.com/444632/145113101-1d06d0f0-ec06-4aad-b622-9639405d9382.png)

The "My Subscriptions" item, I believe is simply [imported as a core menu item ](https://github.com/woocommerce/woocommerce-admin/blob/08afe575a26f6b261463149005348fb3ae56987c/src/Features/Navigation/Menu.php#L570)and showing up in the Extensions as a default. This links to the page for managing WCCOM subscriptions. 

The "Subscriptions" item is enabled by WCPay to manage their own subscriptions. 

**Potential Tasks:**
- [ ] Move the "My Subscriptions" item into another category (possibly "Marketplace," although this isn't it's own category yet)
- [ ] Explore other options such as renaming the task (cc @elizaan36 who will expand on this)

### To Reproduce

1. Enable Woo Navigation (WooCommerce -> Advanced -> Features -> Check new navigation)
2. Install and activate WCPay (don't have to complete setup)
3. Notice that the extensions menu in the new nav shows both Subscriptions items

**Comment by andfinally** [comment]
This may change with the release of WooCommerce 6.0 on 14 December, where we are reverting to the previous menu situation for marketplace My Subscriptions. 

https://github.com/woocommerce/woocommerce-admin/pull/7901
https://github.com/woocommerce/woocommerce-admin/pull/7902 

[Slack thread](p1638914677069200-slack-G63C8LS9M)
[Nav prototype](pbIJXs-Ak-p2) shows how the nav is supposed to work

**Comment by elizaan36** [comment]
It looks like the "My subscriptions" submenu will be removed from the Extensions category in the navigation, so that problem will be fixed. I'm a little unclear how users will navigate to "My subscriptions" from the marketplace screens since it's not a category level item, but that's for a separate issue.

**Comment by joelclimbsthings** [comment]
Thanks @andfinally , @elizaan36 . It sounds like we're good to close this issue then 👍🏻

**Comment by andfinally** [comment]
Thanks @elizaan36, people will get to My Subscriptions via a tab on the Extensions page. This is unfortunately rather indirect, but we found that changing this led to an immediate drop in people browsing and buying extensions. Here's how it'll be with the classic nav:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/1647564/146153089-26a21b3f-5ee3-4e78-84da-9e11e4487abb.png">

**Comment by elizaan36** [comment]
Ok thanks, and just to clarify for the new WooCommerce nav - will the navigation item still show as `Marketplace`?
I'm asking because it would be very confusing if that were named `Extensions` because of the extensions section of the new nav.
<img width="113" alt="Screen Shot 2021-12-15 at 12 31 04 PM" src="https://user-images.githubusercontent.com/5121465/146244864-4881090b-2b1b-45c0-8357-2c2ba2deaaa1.png">
