### ISSUE TITLE
Research: assignment exclusion groups

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce-admin#8070]
We want to start the implementation with a small subset of US stores (% tbd). 

Using ExPlat seems to be the best approach to segment the two experiences, but we're not sure if ExPlat supports what we need.

We want to start with a small subset of US stores and expand the % as we go. However, it looks like it's not possible to exclude the users who were previously assigned when we increase % later on. The feature is a highly requested feature in ExPlat. See more details on pbmo2S-Nj-p2#comment-1995 & p1639429770115900-slack-C7HH3V5AS

We should find an alternative.

**Comment by chihsuan** [comment]
I think it's very hard to exclude users who were previously assigned since ExPlat doesn't support that feature.

But if we can get the number of live experiment participants, then we might be able to use a remote control flag to pause the experiment. 

For example, we want to target an initial 10% and expand to 20%. Our experiment can be set to 20% and we implement a remote control flag to stop the experiment when it reaches ~10% and we turn on it when we want to continue the experiment. The challenge point is how to detect the experiment's progress and update the config.

**Comment by ilyasfoo** [comment]
>For example, we want to target an initial 10% and expand to 20%. Our experiment can be set to 20% and we implement a remote control flag to stop the experiment when it reaches ~10% and we turn on it when we want to continue the experiment. The challenge point is how to detect the experiment's progress and update the config.

I may be wrong but I don't think that's how experiments work since the % of our target audience isn't something that's progressive (like 10%, 20% and eventually 100%). I think the number signifies the % of users being assigned to treatment or otherwise.

**Comment by ilyasfoo** [comment]
I'm thinking of another solution of storing a WP site option for every user that's been exposed to our initial experiment. This way, we can properly identify every user that's been exposed to the initial experiment and automatically exclude them from future similar experiments.

However, I'm not sure yet if a `null` variation from assignment API response would actually mean the user is assigned to control, or if the user isn't eligible at all. This may impact our result since we need to be able to identify if the user is actually exposed or not.

**Pros:**
- Relatively simple to implement

**Cons:**
- It's not a scalable solution for the long term since we may flood user's options if we have too many of this
- Requires releases for every change, so future experiments need to be at least a month apart

**Comment by moon0326** [comment]
Closing this as we've decided to launch the experiment in [NZ and IE](woocommerce/woocommerce#32219).
