### ISSUE TITLE
Event wcadmin_tasklist_completed not working

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#8167]
### Describe the bug
The wcadmin_tasklist_completed event is not being fired when the user hides the task list

### To Reproduce

1. Create a new store with usage tracking enabled
2. Go to the home screen
3. Click to hide the task list
4. See that wcadmin_tasklist_completed is not being fired

### Expected behavior
The wcadmin_tasklist_completed should be fired when the user clicks to hide the task list

**Comment by pmcpinto** [comment]
@becdetat can you check if someone is available to take a look at this during the next few days? Thanks!

**Comment by moon0326** [comment]
I've looked into it and this is what I found so far.

It looks like we're using [hideTaskList](https://github.com/woocommerce/woocommerce-admin/blob/main/client/tasks/task-list-menu.tsx#L15) from the data store, but the [function](main/packages/data/src/onboarding/actions.js#L365) doesn't call recordTrack.

I think we can put the recordEvent back in [task-list-menu.tsx](https://github.com/woocommerce/woocommerce-admin/blob/main/client/tasks/task-list-menu.tsx)

cc ing @woocommerce/mothra in case I missing something.

**Comment by joshuatf** [comment]
@moon0326 I think we do call the event in the task list model - https://github.com/woocommerce/woocommerce-admin/blob/64bf00732fe4682425a1ecf9ddd085d33acadc16/src/Features/OnboardingTasks/TaskList.php#L116-L123

I think we generally want to decouple our tracks from the UI as much as possible so that in the future UI changes don't break our tracks.

In this case, if the event is not firing still, I might suspect that the list ID is either not being retrieved or the prefix is incorrect - https://github.com/woocommerce/woocommerce-admin/blob/64bf00732fe4682425a1ecf9ddd085d33acadc16/src/Features/OnboardingTasks/TaskTraits.php#L36-L45

I'll be around tomorrow on Slack if you need any more help sleuthing!

**Comment by moon0326** [comment]
> @moon0326 I think we do call the event in the task list model -
> 
> https://github.com/woocommerce/woocommerce-admin/blob/64bf00732fe4682425a1ecf9ddd085d33acadc16/src/Features/OnboardingTasks/TaskList.php#L116-L123
> 
> I think we generally want to decouple our tracks from the UI as much as possible so that in the future UI changes don't break our tracks.
> 
> In this case, if the event is not firing still, I might suspect that the list ID is either not being retrieved or the prefix is incorrect -
> 
> https://github.com/woocommerce/woocommerce-admin/blob/64bf00732fe4682425a1ecf9ddd085d33acadc16/src/Features/OnboardingTasks/TaskTraits.php#L36-L45
> 
> I'll be around tomorrow on Slack if you need any more help sleuthing!

Thank you! Ah, I did not check the backend. That's actually better 💯 

I'll test it again and see what's going on.

**Comment by becdetat** [comment]
Thanks @moon0326 @joshuatf , I've put this in Cycle 20 and dropped it in Ghidorah's backlog

**Comment by pmcpinto** [comment]
Hey @moon0326 in which release can we include this fix?

**Comment by ilyasfoo** [comment]
Hey @pmcpinto, it'll be included in 3.1-rc.2

**Comment by moon0326** [comment]
> Hey @moon0326 in which release can we include this fix?

@pmcpinto We'll aim to include it in the upcoming 3.1.0 RC2.

**Comment by ilyasfoo** [comment]
Hmm, I've looked into it, it seems the backend is firing `wcadmin_tasklist_completed` just fine. I've tested this in both the old task list and the experimental tasklist.

@pmcpinto Browser console will not be able to see the tracks firing because it's triggered from backend. I've tested it in a fresh JN site with the latest WC 6.1. The way I tested it is I modified the backend's tracks code to log all track when it's triggered from the backend:

![image](https://user-images.githubusercontent.com/3747241/149865252-2a32034e-63f0-494e-bc0e-537bb3341096.png)

**Comment by ilyasfoo** [comment]
@pmcpinto You can also confirm if the tracks is working by using the live tracks tool and filter the eventname with `%tasklist_%`

**Comment by pmcpinto** [comment]
Thanks for checking this. So it looks like the event is working correctly, right?

**Comment by ilyasfoo** [comment]
@pmcpinto Yes

**Comment by pmcpinto** [comment]
👍  I'll leave the issue open in case @moon0326 wants to tweak how this event is being tracked.

**Comment by ilyasfoo** [comment]
I've confirmed with @moon0326 that we aren't changing the way the event is tracked. An issue was filed by Joshua to improve on debugging backend tracks https://github.com/woocommerce/woocommerce-admin/issues/8199
