### ISSUE TITLE
Product management extensibility spike

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce-admin#8207]
We need to have a technical spike to determine the consequences of moving to a React-based, redesigned interface for product management, primarily around allowing third-party extensions to continue to work with the management interface.

We don't have any designs for the new interface, so we can limit this spike to using the current interface.

It is important that we, @woocommerce/mothra, become familiar with the current Products screen functionality and implementation, so that we are well-equipped to help shape the future direction of this area of WooCommerce.

## General areas to investigate

- What are some of the most popular extensions that extend/modify the current Products screen?
- How do these extensions extend/modify the current Products screen?
- What are the most common things modified?

## Technical areas to investigate

- Investigate using Slot/Fill for extensibility in a new React-based UI
- Is there another approach to extensibility that should also be considered? Perhaps a Gutenberg-based approach?

## Technical notes

- Existing plugins will probably use HTML injection (using `ob_start()`, `ob_get_contents()`, and `ob_end_clean()` or similar). We need to capture the buffer and wrap it in a REST call, injecting the extension content using React.
    - As part of the spike, we need to verify this. Is this actually how existing plugins do things?
- [Previous spike](https://github.com/woocommerce/woocommerce-admin/pull/8039) (p90Yrv-2B0-p2) for the Settings pages.

## Acceptance criteria (desired output)

- A P2 post summarizing the findings of the spike (or multiple P2 posts if that seems better suited for discussion and readability)
    - Lots of screenshots/examples, especially when discussing how current extensions extend the Products screen
    - Any caveats/concerns with the potential new approaches

**Comment by mattsherman** [comment]
@woocommerce/mothra will handle this in Cycle 21.

**Comment by mattsherman** [comment]
@joelclimbsthings Please provide a summary of what you have investigated so far.

**Comment by joelclimbsthings** [comment]
Hey @mattsherman , thanks for chiming in. 

I wouldn't say my thoughts are all that organized, as I'm only ~3 days into a 5 point ticket, but in short I've done the following:

- Compiled a list of 15 "popular" extensions that modify the product page. I've made sure to include those both created by Woo, and otherwise.
- Explored the extensions with my local, comparing to a control, and parsed through the code bases. 
- Taken notes on actions/etc that have been used to modify the page, and roughly how they're doing so. 
- Kept track of which actions/etc are most utilized across all the extensions
- Taken note of how data is being recorded in the DB for various extensions. (WIP)
- Notes around other details that jump out, such as the use of inline scripts and how CSS/JS is loaded (WIP)

I've just finished going through all 15 extensions as an initial survey, although it might be worth while to understand the points labeled as WIP above a bit better. That said, my intention is to start experimenting with methods to carry over the above discovered extensibility points to a React-based app, and formulate a P2 post on the topic.

**Comment by mattsherman** [comment]
@joelclimbsthings Thanks for providing a summary!

> I wouldn't say my thoughts are all that organized, as I'm only ~3 days into a 5 point ticket

Completely expected! I just want to make sure that we approach this as discussed during the team call... I don't want a single team member going away for multiple days without any progress update. And, I want to make sure that other team members can also take a look at this (@woocommerce/mothra).

It sounds like you have done some excellent work so far and I look forward to digging into the details once you have organized them into a P2 post. Please make sure to post this by the end of your week. If doesn't have to be complete/final... what is most important at this stage is that we better understand the lay of the land and the possibilities with a React-based app. There will be many details that will desire further spiking!

**Comment by joelclimbsthings** [comment]
Thanks @mattsherman, that makes total sense. Will do!
