### ISSUE TITLE
Top margin/padding with new navigation

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce-admin#8221]
### Describe the bug
If you enable the new navigation on a standalone install the margin/padding for the embedded header applies to all dashboard pages.

### To Reproduce

1. Enable the new navigation on a standalone WooCommerce site
2. Go to the WP Dashboard
3. See screenshot

### Screenshots

<img width="1266" alt="Screen Shot 2022-01-26 at 6 03 03 PM" src="https://user-images.githubusercontent.com/343847/151255410-457e6e8f-7cd3-437b-8f42-f52c33164c47.png">

### Desktop (please complete the following information):

* OS: MacOS
* Browser Firefox
* Version 94.0.2

**Comment by chihsuan** [comment]
Hi @rrennick, thank you for taking the time to report the bug! However, I can't reproduce the issue in my local with Firefox. 

Could you share your system status or additional context so that we can try to reproduce the bug correctly?

https://user-images.githubusercontent.com/4344253/151282776-7af7b2a8-17b5-4df2-8869-28f19fbf5107.mov

**Comment by rrennick** [comment]
> However, I can't reproduce the issue in my local with Firefox.

Thanks for the quick follow up. I tried it in an install with only WC 6.1.1 active and did not see the issue. The site that has the issue has a slightly out of date version of Jetpack active. I suspect that might be the source of the issue.
