### ISSUE TITLE
Shipping task: "Enable shipping label printing" step is missing

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#8254]
### Describe the bug
The "Enable shipping label printing" step is missing in the Shipping task. This option should be available for US users. 

### To Reproduce

1. Create a new store located in the US
2. Install WooCommerce Shipping
3. Visit the Shipping task
4. See that the "Enable shipping label printing" step is missing

### Actual behavior:
We don't inform US users that they can enable shipping label printing directly in the shipping task

### Screenshots
<img width="1280" alt="Captura de ecrã 2022-02-03, às 18 06 00" src="https://user-images.githubusercontent.com/3380168/152402585-fc5808da-47a6-4a09-bf6d-e647c5b4c58f.png">

### Expected behavior
We should display the steps to enable shipping label printing

**Comment by pmcpinto** [comment]
@becdetat @mattsherman this was working well in 6.0 (#8027). So I'm not sure if the bug was introduced after 6.0. Is it possible to check this? Thanks!

**Comment by becdetat** [comment]
Sure, @mattsherman can you get someone on this please?

**Comment by mattsherman** [comment]
> Sure, @mattsherman can you get someone on this please?

This will be investigated and addressed by @woocommerce/mothra

**Comment by louwie17** [comment]
>  this was working well in 6.0 (#8027). So I'm not sure if the bug was introduced after 6.0. Is it possible to check this? Thanks!

@pmcpinto this step only shows up if either Jetpack or `woocommerce-services` are not installed, otherwise this step is hidden (for USA store in particular), [here is that logic](https://github.com/woocommerce/woocommerce-admin/blob/main/client/tasks/fills/shipping/index.js#L166-L177), this doesn't appear to have changed for some time, is there something else you were expected when both of these plugins are installed?

**Comment by pmcpinto** [comment]
Ahhh. I totally forgot that shipping label printing is auto-enabled with WCS. Sorry for the confusion. We don't need to change anything. I'll close the issue
