### ISSUE TITLE
Update to Webpack v5

### ISSUE THREAD

**Issue by chihsuan** [woocommerce/woocommerce-admin#8326]
Recently I tried to build with `explat-client-react-helpers@0.0.3` but encounter an error due to optional chaining operators. I found it's a [webpack issue](https://github.com/webpack/webpack/issues/10227#issue-547480527) that Webpack v4 doesn't support it.

I've updated the `exclude` option of babel-loader as a webpack4 solution in this commit https://github.com/woocommerce/woocommerce-admin/commit/c9867117c0adfe90d538f89f59d553745a091ffe.

But I think we should consider updating to Webpack v5.

**Comment by joelclimbsthings** [comment]
Thanks @chihsuan , I was just about to create this same issue, and came across yours! Just noting here that [this was attempted](https://github.com/woocommerce/woocommerce-admin/issues/5502) shortly after Webpack 5 was released, but aborted due to the lack of support from various plugins.

It's definitely time to revisit, as this is also a blocker for my css-in-js efforts.

**Comment by adrianduffell** [comment]
> Just noting here that https://github.com/woocommerce/woocommerce-admin/issues/5502 shortly after Webpack 5 was released, but aborted due to the lack of support from various plugins.

Thanks for sharing this @joelclimbsthings !

I think our next step will be to investigate whether all the plugins now support webpack 5.

From the previous issue:

> This is blocked currently by issues with several dependant plugins that rely on webpack 4 deprecations. I'd really like those deprecations sorted before we migrate to webpack 5.

**Comment by joelclimbsthings** [comment]
Agreed @adrianduffell , I actually started looking at this the other day. This was a fairly cursory survey, but since it looks like you may pull this into your sprint I'll share my (perhaps incomplete) findings here:

---------------------------------------

**copy-webpack-plugin**
_Supports Webpack 5?_
Yes

**eslint-import-resolver-webpack**
_Supports Webpack 5?_
Yes

**fork-ts-checker-webpack-plugin**
_Supports Webpack 5?_
Yes

**moment-timezone-data-webpack-plugin**
_Supports Webpack **5?_**
Yes

**terser-webpack-plugin**
_Supports Webpack 5?_
Yes.
_Note: This is now built into Webpack if you're not customizing it._ 

**webpack-rtl-plugin**
_Supports Webpack 5?_
Sounds like there are deprecation warnings, with [a PR created](https://github.com/romainberger/webpack-rtl-plugin/pull/37) to fix this.

**@woocommerce/dependency-extraction-webpack-plugin**
Located in our repo, with dependency on [@wordpress/dependency-extraction-webpack-plugin](https://www.npmjs.com/package/@wordpress/dependency-extraction-webpack-plugin) that does seem to support Webpack 5.

**@wordpress/custom-templated-path-webpack-plugin**
_Supports Webpack 5?_
[Sounds like it](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-custom-templated-path-webpack-plugin/).

**@automattic/mini-css-extract-plugin-with-rtl**
_Supports Webpack 5?_
No, hasn't been modified in a couple years. Belongs to A8C, so hopefully not too difficult to work around or update this.

**webpack-bundle-analyzer**
_Supports Webpack 5?_
Yes

**webpack-fix-style-only-entries**
_Supports Webpack 5?_
Yes, but need to use https://github.com/webdiscus/webpack-remove-empty-scripts for WP 5

**Comment by adrianduffell** [comment]
Awesome, thanks @joelclimbsthings !
