### ISSUE TITLE
WooCommerce Orders Missing “Sales” Info but Still Showing “Refund” Amounts

### ISSUE THREAD

**Issue by CarletonTorpin** [woocommerce/woocommerce-admin#8335]
### Describe the bug

WooCommerce is not tracking the **income** from at least two sales from the month of December 2021, but the report is still subtracting their **refund** amounts.

The orders in-question were purchased and refunded on Dec 29th and Dec 30th, respectively

### To Reproduce

From the Wordpress Dashboard on my website:

1. Go to "WooCommerce'
2. Click on 'Reports'
3. Set Custom Date Period to "December 1, 2021 thru Dec 31, 2021"
4. The Report shows the following data: https://www.dropbox.com/s/s4bvtyg96ymwrx5/WordpressSalesDataReportDecember2021.jpg?dl=0

### Actual behavior:
The Report data for Dec 1, 2021 thru Dec 31, 2021 shows that the two orders are being refunded, but the income is not displayed or calculated into the Gross Sales for the period. This is creating an incorrect Gross Income figure, since it's deducting nearly $2,000 in sales, but it never added the initial income from those sales. 

### Screenshots

This is the currently reported sales data. 
https://www.dropbox.com/s/s4bvtyg96ymwrx5/WordpressSalesDataReportDecember2021.jpg?dl=0

I have pasted screenshots from both of the orders below:

Dec 29th Order for $350-ish https://snipboard.io/EnyoQb.jpg

Dec 30th Order for $1,400-ish https://snipboard.io/atFzXd.jpg

### Expected behavior
I expected that the Report would show the sales income for the two problem orders (Dec 29th and Dec 30th), and then it would show the refunded amount from those orders. 

### Desktop (please complete the following information):

* OS: Mac OS 12.2.1
* Browser: Safari, Mozilla Firefox
* Version: Safari 15.3, Mozilla Firefox 97.0

### Additional context

This is the original support thread that I opened at WooCommerce's forum: 

https://wordpress.org/support/topic/two-orders-missing-sales-info-but-still-showing-refund-amounds/#post-15321957

They suggested that I escalate the issue to GitHub.

**Comment by rjchow** [comment]
Hey @CarletonTorpin, thank you for getting in touch with us!

I can confirm that the issue you have reported is indeed reproducible. However, Woocommerce Reports have been deprecated since 4.0 (as noted in your screenshot) and the replacement is Woocommerce Analytics which is also included in Woocommerce.

I have confirmed that the feature that you are looking for works correctly in Woocommerce Analytics as seen in the screenshot below:

![image](https://user-images.githubusercontent.com/27843274/155277460-9b553842-69e8-4fb0-b01f-c8075800d903.png)
